import { useParams, useLocation } from 'react-router-dom'
import { lazy, Suspense } from 'react'
import { useQuery } from '@tanstack/react-query'
import DocsLayout from '../../components/docs-platform/DocsLayout'
import { getPackage } from '../../content/docs-loader'

const ApiReferenceReact = lazy(() =>
  import('@scalar/api-reference-react').then((m) => ({ default: m.ApiReferenceReact })),
)

interface OpenApiSpec {
  openapi?: string
  info?: { title?: string }
}

// Eager glob: every synced OpenAPI doc gets compiled into the SPA chunk so
// version switches don't trigger a network round-trip. Each version's file
// resolves to a `() => Promise<{ default: OpenApiSpec }>`.
const specLoaders = import.meta.glob<{ default: OpenApiSpec }>(
  '../../content/_synced/api/*/openapi.json',
)

function loaderFor(version: string): (() => Promise<{ default: OpenApiSpec }>) | null {
  const key = `../../content/_synced/api/${version}/openapi.json`
  return specLoaders[key] ?? null
}

/**
 * Renders the Oxy REST API reference via Scalar. The OpenAPI document lives
 * in the synced docs tree at `_synced/api/<version>/openapi.json` and is
 * generated by `packages/api/scripts/generate-openapi.ts` from
 * `OxyHQServices`.
 */
export default function DocsApiPage() {
  const params = useParams<{ version?: string }>()
  const location = useLocation()
  const pkg = getPackage('api')
  const version = params.version ?? pkg?.defaultVersion ?? 'main'

  const specQuery = useQuery({
    queryKey: ['docs-api-spec', version],
    queryFn: async () => {
      const loader = loaderFor(version)
      if (!loader) throw new Error(`No OpenAPI document for version "${version}".`)
      const mod = await loader()
      return mod.default
    },
    staleTime: Infinity,
  })

  const spec = specQuery.data ?? null
  const error = specQuery.error instanceof Error ? specQuery.error.message : null

  return (
    <DocsLayout
      pkg={pkg}
      slug=""
      pageTitle="REST API Reference"
      seoTitle="Oxy REST API"
      seoDescription="REST API reference for the Oxy platform — authentication, accounts, files, billing, and more."
      canonicalPath={location.pathname}
    >
      {error ? (
        <div className="not-prose rounded-2xl border border-border bg-surface p-6">
          <h2 className="text-lg font-semibold text-foreground mb-1">API reference unavailable</h2>
          <p className="text-sm text-muted-foreground">
            Run <code>bun scripts/sync-docs.ts</code> from the website root after generating the
            OpenAPI document inside <code>packages/api</code>.
          </p>
          <p className="mt-2 text-xs text-muted-foreground">Detail: {error}</p>
        </div>
      ) : !spec ? (
        <div className="text-sm text-muted-foreground">Loading API reference…</div>
      ) : (
        <div className="not-prose -mx-6 lg:-mx-12">
          <Suspense fallback={<div className="text-sm text-muted-foreground">Loading…</div>}>
            <ApiReferenceReact configuration={{ spec: { content: spec } }} />
          </Suspense>
        </div>
      )}
    </DocsLayout>
  )
}
