// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'chart-cards/sparkline',
  propTypes: {
    'SparklineProps': {
      props: [
        { name: 'data', type: 'readonly number[]', optional: false, description: 'Values left to right. Fewer than two draws nothing.' },
        { name: 'width', type: 'number', optional: true, description: 'Default 72.' },
        { name: 'height', type: 'number', optional: true, description: 'Default 28.' },
        { name: 'tone', type: 'SparklineTone', options: ['accent', 'positive', 'negative', 'neutral'], optional: true, description: "Default `'accent'` (`chart-6-active`)." },
        { name: 'color', type: 'string', optional: true, description: 'Any colour; wins over `tone`.' },
        { name: 'fill', type: 'boolean', optional: true, description: 'A soft gradient under the line (the line colour, 24% → 0%). Default `true`.' },
        { name: 'shape', type: "'curved' | 'sharp'", options: ['curved', 'sharp'], optional: true, description: '`curved` (monotone) or `sharp` (straight segments). Default `curved`.' },
        { name: 'strokeWidth', type: 'number', optional: true, description: 'Default 1.5.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the sparkline as an image (`role="img"`). Without it the sparkline is decorative and hidden from assistive tech — the usual case beside a value and delta that already say the same thing.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Sparkline', propsType: 'SparklineProps' },
  ],
}
