// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'chat-people/contact-row',
  propTypes: {
    'ContactRowProps': {
      props: [
        { name: 'avatarSlot', type: 'ReactNode', optional: true, description: 'Replaces AvatarPresence. Caller owns avatar size, badges and presence semantics.' },
        { name: 'identitySlot', type: 'ReactNode', optional: true, description: 'Replaces the visible name/subtitle block; name and subtitle still name the row accessibly.' },
        { name: 'trailing', type: 'ContactRowTrailing', options: ['none', 'chevron', 'checkbox', 'action'], optional: true, description: 'Defaults to `checkbox` with `onSelectedChange`, `action` with `onAction`, else `none`.' },
        { name: 'trailingSlot', type: 'ReactNode', optional: true, description: 'Replaces the trailing slot entirely.' },
        { name: 'selected', type: 'boolean', optional: true },
        { name: 'onSelectedChange', type: '(next: boolean) => void', optional: true },
        { name: 'actionLabel', type: 'string', optional: true, description: 'The action button\'s label — "Invite", "Add".' },
        { name: 'onAction', type: '() => void', optional: true },
        { name: 'actionDone', type: 'boolean', optional: true, description: 'Swaps the action button for a quiet "Added" mark.' },
        { name: 'actionDoneLabel', type: 'string', optional: true },
        { name: 'onPress', type: '() => void', optional: true },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'size', type: "'small' | 'medium'", options: ['small', 'medium'], optional: true, description: '`medium` 44px avatar (default), `small` 36 for a dense picker.' },
        { name: 'horizontalInset', type: 'number', optional: true, description: 'Horizontal inset around the avatar/text area. Default 10; use 0 in an already-inset widget.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'textStyle', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
        { name: 'id', type: 'string', optional: false },
        { name: 'name', type: 'string', optional: false },
        { name: 'avatar', type: 'PersonAvatarSource', optional: true },
        { name: 'avatarVariant', type: 'string', optional: true, description: '`ImageResolver` rendition for a bare-id `avatar`.' },
        { name: 'subtitle', type: 'string', optional: true, description: '"last seen recently", "@ana", "+34 600 …" — pre-formatted.' },
        { name: 'status', type: 'PresenceStatus', options: ['online', 'idle', 'offline', 'busy'], optional: true },
      ],
    },
  },
  components: [
    { name: 'ContactRow', propsType: 'ContactRowProps' },
  ],
}
