// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'tabs/expo-router',
  propTypes: {
    'RouterTabsProps': {
      props: [
        { name: 'variant', type: 'TabsVariant', options: ['underline', 'filled', 'outlined'], optional: true, description: 'Visual variant for the tab bar.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
        { name: 'fullWidth', type: 'boolean', optional: true, description: 'When true, the tab bar spans the full container width and each trigger takes an equal share of it (edge to edge), instead of the default content-sized, horizontally scrollable layout. Best for a small, fixed set of tabs (e.g. 2–3). Defaults to `false`.' },
        { name: 'items', type: 'RouterTabItem[]', optional: false },
        { name: 'onReselect', type: '(value: string) => void', optional: true, description: 'Called instead of navigating when the ALREADY-active tab is pressed.' },
        { name: 'swipeEnabled', type: 'boolean', optional: true, description: 'Enable the horizontal swipe between neighbouring tabs. Defaults to `true`.' },
      ],
    },
  },
  components: [
    { name: 'RouterTabs', propsType: 'RouterTabsProps' },
  ],
}
