// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'accordion',
  propTypes: {
    'AccordionProps': {
      props: [
        { name: 'value', type: 'string | string[] | undefined', optional: false, description: "Controls which items are expanded. For 'single' type, pass a string or undefined. For 'multiple' type, pass an array of strings." },
        { name: 'onValueChange', type: '(value: string | string[] | undefined) => void', optional: false, description: 'Called when expanded items change.' },
        { name: 'type', type: 'AccordionType', options: ['single', 'multiple'], optional: true, description: 'Whether only one item can be expanded at a time.' },
        { name: 'children', type: 'React.ReactNode', optional: false, description: 'Accordion items.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'AccordionItemProps': {
      props: [
        { name: 'value', type: 'string', optional: false, description: 'Unique value identifying this item.' },
        { name: 'children', type: 'React.ReactNode', optional: false, description: 'Item content: should be AccordionTrigger and AccordionContent.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Whether this item is disabled.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
      ],
    },
    'AccordionTriggerProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false, description: 'Trigger content (label text).' },
        { name: 'icon', type: 'React.ReactNode', optional: true, description: 'Icon to show on the left side.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'textStyle', type: 'StyleProp<TextStyle>', optional: true },
      ],
    },
    'AccordionContentProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false, description: 'Content to show when expanded.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
      ],
    },
  },
  components: [
    { name: 'Accordion', propsType: 'AccordionProps' },
    { name: 'AccordionItem', propsType: 'AccordionItemProps' },
    { name: 'AccordionTrigger', propsType: 'AccordionTriggerProps' },
    { name: 'AccordionContent', propsType: 'AccordionContentProps' },
  ],
}
