// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'address',
  propTypes: {
    'AddressListProps': {
      props: [
        { name: 'sections', type: 'readonly AddressListSection[]', optional: false },
        { name: 'selectedId', type: 'string', optional: true, description: 'The chosen entry\'s `id`. Only meaningful for `variant="picker"`.' },
        { name: 'onSelect', type: '(id: string) => void', optional: true },
        { name: 'variant', type: 'AddressListVariant', options: ['list', 'picker'], optional: true, description: 'Default `list`.' },
        { name: 'density', type: 'AddressDensity', options: ['comfortable', 'compact'], optional: true, description: 'Default `comfortable`.' },
        { name: 'loading', type: 'boolean', optional: true, description: 'Draws placeholder rows instead of the sections.' },
        { name: 'loadingRows', type: 'number', optional: true, description: 'How many placeholder rows. Default 3.' },
        { name: 'empty', type: 'ReactNode', optional: true, description: 'Replaces the whole empty block.' },
        { name: 'emptyTitle', type: 'string', optional: true, description: 'Default `"Nothing here yet"`.' },
        { name: 'emptyDescription', type: 'string', optional: true },
        { name: 'emptyIcon', type: 'BloomIconComponent', optional: true, description: 'The glyph above the empty text. Default a map pin.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the list. Default `"Addresses"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'AddressRowProps': {
      props: [
        { name: 'title', type: 'string', optional: false, description: 'The line a reader identifies the place by — "Home", "Carrer de l’Om 14".' },
        { name: 'subtitle', type: 'string', optional: true, description: 'The rest of it — "Carrer de l’Om 14, Barcelona", "2nd floor, ring twice".' },
        { name: 'kind', type: 'AddressKind', options: ['place', 'saved', 'recent', 'suggestion'], optional: true, description: 'Chooses the default glyph. Default `place`.' },
        { name: 'icon', type: 'BloomIconComponent', optional: true, description: 'The glyph, overriding whatever `kind` would have chosen.' },
        { name: 'leading', type: 'ReactNode', optional: true, description: 'An arbitrary leading node — an `Avatar`, a map thumbnail — instead of the glyph tile. Read for PRESENCE: `leading={null}` draws NO media at all, for a row in a list that already has a gutter of its own (`RouteStops`).' },
        { name: 'meta', type: 'string', optional: true, description: 'A short trailing reading — "1.2 km", "12 min". Drawn before `action`.' },
        { name: 'badge', type: 'ReactNode', optional: true, description: 'A node after the title — a `Badge` ("Default"), a `Chip`.' },
        { name: 'action', type: 'ReactNode', optional: true, description: 'A trailing control — a `GlyphButton`, a `Button`.' },
        { name: 'selected', type: 'boolean', optional: true, description: 'Highlights the row and announces the selection, for the role it is given.' },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'onPress', type: '() => void', optional: true },
        { name: 'density', type: 'AddressDensity', options: ['comfortable', 'compact'], optional: true, description: 'Default `comfortable`.' },
        { name: 'role', type: "'radio' | 'option' | 'listitem'", options: ['radio', 'option', 'listitem'], optional: true, description: 'What the row IS in the tree around it. `AddressList` passes this; a row placed on its own leaves it alone and gets a plain pressable row.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: "The announced name. Defaults to the title, subtitle and meta joined — the row's own text, in reading order, as one utterance." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'AddressList', propsType: 'AddressListProps' },
    { name: 'AddressRow', propsType: 'AddressRowProps' },
  ],
}
