// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'admonition',
  propTypes: {
    'AdmonitionContent': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
      ],
    },
    'AdmonitionText': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'style', type: 'TextStyle', optional: true },
      ],
    },
    'Omit<ButtonProps, "size" | "variant">': {
      props: [
        { name: 'onPress', type: '() => void', optional: true },
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'textStyle', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'icon', type: 'React.ReactNode', optional: true },
        { name: 'iconPosition', type: "'left' | 'right'", options: ['left', 'right'], optional: true },
        { name: 'loading', type: 'boolean', optional: true, description: 'When true, displays a centered loading spinner overlay and prevents presses. Children remain in the layout (but visually hidden) so the button preserves its width. Use this for async actions like submit.' },
        { name: 'loadingColor', type: 'string', optional: true, description: 'Optional color override for the loading spinner. Defaults to the resolved button text color.' },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'accessibilityHint', type: 'string', optional: true },
        { name: 'hitSlop', type: '{ top: number; bottom: number; left: number; right: number; }', optional: true },
        { name: 'testID', type: 'string', optional: true },
        { name: 'className', type: 'string', optional: true },
        { name: 'type', type: "'button' | 'submit' | 'reset'", options: ['button', 'submit', 'reset'], optional: true, description: "HTML button `type` (web only). Defaults to `'button'`. Use `'submit'` to participate in `<form>` submission / HTML5 validation / Enter-to-submit, and `'reset'` to reset a form." },
        { name: 'onClick', type: '(event: React.MouseEvent<HTMLButtonElement>) => void', optional: true, description: 'Web click handler. Aliased to the same logical action as `onPress` — either (or both) may be provided; both fire on click. `onPress` is kept for cross-platform parity.' },
        { name: 'asChild', type: 'boolean', optional: true, description: 'Render as the child element instead of a `<button>` (web only). Use for link-buttons: `<Button asChild><a href="…">Go</a></Button>` applies the button styling to the `<a>` (or a router `<Link>`). The child receives the merged `className`, `style`, and the button\'s event handlers.' },
        { name: 'id', type: 'string', optional: true, description: 'Inline DOM `id` (web only).' },
        { name: 'name', type: 'string', optional: true, description: 'Native HTML `name` for form participation (web only).' },
        { name: 'value', type: 'string', optional: true, description: 'Native HTML `value` for form participation (web only).' },
        { name: 'aria-label', type: 'string', optional: true, description: '`aria-label` (web only). Falls back to `accessibilityLabel`.' },
        { name: 'aria-expanded', type: 'boolean', optional: true, description: 'Whether the surface this button controls is open.' },
        { name: 'aria-haspopup', type: "WebAriaProps['aria-haspopup']", options: ['menu', 'listbox', 'tree', 'grid', 'dialog'], optional: true, description: "What the surface this button opens IS. Forwarded for the same reason as ['aria-expanded']; the value comes from the family." },
        { name: 'title', type: 'string', optional: true, description: '`title` tooltip attribute (web only).' },
        { name: 'autoFocus', type: 'boolean', optional: true, description: '`autoFocus` the button on mount (web only).' },
        { name: 'tabIndex', type: 'number', optional: true, description: '`tabIndex` override (web only).' },
        { name: 'fullWidth', type: 'boolean', optional: true, description: 'Stretch the button to fill its container\'s main axis (web only). Equivalent to passing `className="w-full"`; provided as a prop for ergonomics.' },
      ],
    },
    'AdmonitionRoot': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false },
        { name: 'type', type: 'AdmonitionType', options: ['info', 'tip', 'warning', 'error', 'apology'], optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
      ],
    },
    'Admonition': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'type', type: 'AdmonitionType', options: ['info', 'tip', 'warning', 'error', 'apology'], optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
      ],
    },
  },
  components: [
    { name: 'AdmonitionIcon' },
    { name: 'AdmonitionContent', propsType: 'AdmonitionContent' },
    { name: 'AdmonitionText', propsType: 'AdmonitionText' },
    { name: 'AdmonitionButton', propsType: 'Omit<ButtonProps, "size" | "variant">' },
    { name: 'AdmonitionRow', propsType: 'AdmonitionContent' },
    { name: 'AdmonitionRoot', propsType: 'AdmonitionRoot' },
    { name: 'Admonition', propsType: 'Admonition' },
  ],
}
