// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'agent-progress',
  propTypes: {
    'AgentProgressProps': {
      props: [
        { name: 'steps', type: 'readonly string[]', optional: true, description: 'Ordered task labels. Defaults to a coding workflow (`DEFAULT_AGENT_PROGRESS_STEPS`).' },
        { name: 'stepDuration', type: 'number', optional: true, description: 'Time spent on each step, in ms. Drives the rings; when `completedCount` is uncontrolled it also advances the steps. Default `3000`.' },
        { name: 'completionDelay', type: 'number', optional: true, description: 'Time to keep the completed state visible before calling `onFinished`, ms. Default `1000`.' },
        { name: 'onFinished', type: '() => void', optional: true, description: 'Called `completionDelay` ms after the last step completes.' },
        { name: 'paused', type: 'boolean', optional: true, description: "Freezes the clock: no step advances and `onFinished` doesn't fire while true. The module keeps its current state and resumes when it flips back." },
        { name: 'completedCount', type: 'number', optional: true, description: 'Controlled progress: how many steps are done. When set the internal clock no longer advances steps — the consumer does, as its agent reports them. The rings still animate each step over `stepDuration` as an estimate and jump ahead when a step lands early.' },
        { name: 'minimized', type: 'boolean', optional: true, description: 'Controlled minimized state.' },
        { name: 'defaultMinimized', type: 'boolean', optional: true, description: 'Initial minimized state when uncontrolled. Default `false`.' },
        { name: 'onMinimizedChange', type: '(minimized: boolean) => void', optional: true },
        { name: 'labels', type: 'AgentProgressLabels', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Card style (width, margins…). Default card is 341 wide, `max-width: 100%`.' },
        { name: 'testID', type: 'string', optional: true, description: "Default `'agent-progress'`; parts append `-minimized`, `-expanded`, `-step-<i>`." },
      ],
    },
    'AgentProgressLoadingTextProps': {
      props: [
        { name: 'children', type: 'string', optional: false, description: 'The label. A string, so the shimmer can be laid across its characters.' },
        { name: 'variant', type: 'TypeScaleVariant', options: ['large-title-regular', 'large-title-medium', 'large-title-semibold', 'large-title-bold', 'display-1-regular', 'display-1-medium', 'display-1-semibold', 'display-1-bold', 'display-2-regular', 'display-2-medium', 'display-2-semibold', 'display-2-bold', 'display-3-regular', 'display-3-medium', 'display-3-semibold', 'display-3-bold', 'display-4-regular', 'display-4-medium', 'display-4-semibold', 'display-4-bold', 'title-1-regular', 'title-1-medium', 'title-1-semibold', 'title-1-bold', 'title-2-regular', 'title-2-medium', 'title-2-semibold', 'title-2-bold', 'title-3-regular', 'title-3-medium', 'title-3-semibold', 'title-3-bold', 'headline-regular', 'headline-medium', 'headline-semibold', 'headline-bold', 'body-regular', 'body-medium', 'body-semibold', 'body-bold', 'body-2-regular', 'body-2-medium', 'body-2-semibold', 'body-2-bold', 'caption-1-regular', 'caption-1-medium', 'caption-1-semibold', 'caption-1-bold', 'caption-2-regular', 'caption-2-medium', 'caption-2-semibold', 'caption-2-bold'], optional: true, description: "Type-ramp step. Default `'body-medium'` (the step labels)." },
        { name: 'style', type: 'StyleProp<TextStyle>', optional: true, description: 'Text style; its `color` is ignored while the shimmer runs.' },
        { name: 'numberOfLines', type: 'number', optional: true, description: 'Default `1` (truncates the label). `0` lets it wrap.' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'AgentProgress', propsType: 'AgentProgressProps' },
    { name: 'AgentProgressLoadingText', propsType: 'AgentProgressLoadingTextProps' },
  ],
}
