// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'agent-limits-card',
  propTypes: {
    'AgentLimitsCardProps': {
      props: [
        { name: 'context', type: 'AgentLimitsContext', optional: true, description: 'Context-window usage. Omit to show only the plan limits.' },
        { name: 'plan', type: 'string', optional: true, description: 'Plan name shown after "Plan usage limits ·".' },
        { name: 'limits', type: 'ReadonlyArray<AgentLimitsUsageLimit>', optional: true, description: 'Plan limits, one bar each. Omit (with no `plan`) to show only the context window.' },
        { name: 'onPlanPress', type: '() => void', optional: true, description: 'Shows the arrow button beside the plan heading, and handles its press.' },
        { name: 'expanded', type: 'boolean', optional: true, description: 'Controlled breakdown state.' },
        { name: 'defaultExpanded', type: 'boolean', optional: true, description: 'Initial breakdown state when uncontrolled. Default `false`.' },
        { name: 'onExpandedChange', type: '(expanded: boolean) => void', optional: true },
        { name: 'formatTokens', type: '(tokens: number) => string', optional: true, description: 'Token formatter. Default: `482_800 → "482.8k"`, `1_000_000 → "1M"`.' },
        { name: 'labels', type: 'AgentLimitsCardLabels', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'AgentLimitsCard', propsType: 'AgentLimitsCardProps' },
  ],
}
