// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'ai-profile-card',
  propTypes: {
    'AiProfileCardProps': {
      props: [
        { name: 'name', type: 'string', optional: false, description: 'Display name, `title-2-medium`.' },
        { name: 'handle', type: 'string', optional: true, description: 'Handle beside the badge (`"@sitenley"`).' },
        { name: 'badge', type: 'string', optional: true, description: 'The neutral counter badge after the handle (`"PRO"`).' },
        { name: 'coverSource', type: 'string | ImageSourcePropType | null', optional: true, description: 'Cover photo across the top 165px. Without one the band is `background-tertiary`.' },
        { name: 'coverPosition', type: '{ x: number; y: number; }', optional: true, description: "Where the cover's crop sits, as fractions (`object-position`). Default `{ x: 0.5, y: 0.45 }` — CSS `object-[50%_45%]`." },
        { name: 'avatarSource', type: 'string | ImageSourcePropType | null', optional: true, description: 'Avatar photo. Without one the 80px disc shows `initials`.' },
        { name: 'initials', type: 'string', optional: true, description: 'Initials for the photo-less disc. Defaults to the first letter of `name`.' },
        { name: 'actions', type: 'ReactNode', optional: true, description: "Buttons pinned 20px under the cover's right edge (e.g. secondary small `Share` / `Edit`)." },
        { name: 'contributionsLabel', type: 'string', optional: true, description: 'Label over the headline. Default `"Contributions this year"`.' },
        { name: 'contributions', type: 'number', optional: false, description: 'The headline number; counts up from 0 on mount (1.6s).' },
        { name: 'format', type: '(value: number) => string', optional: true, description: 'Headline format. Default `$7,462`.' },
        { name: 'countUpDuration', type: 'number', optional: true, description: 'Duration of the mount count-up, ms. Default 1600; 0 shows the number at once.' },
        { name: 'delta', type: 'string', optional: true, description: 'Chip beside the headline (`"+14.8%"`), status-purple. No chip when omitted.' },
        { name: 'stats', type: 'readonly AiProfileCardStat[]', optional: true, description: 'The tiles: one row from 640px, two columns below.' },
        { name: 'activityLabel', type: 'string', optional: true, description: 'Label over the heatmap. Default `"Activity"`.' },
        { name: 'periods', type: 'readonly AiProfileCardPeriod[]', optional: true, description: 'Segments of the plain switcher. Default Weekly / Monthly / Yearly. Empty hides it.' },
        { name: 'period', type: 'string', optional: true, description: 'Controlled selected period id.' },
        { name: 'defaultPeriod', type: 'string', optional: true, description: 'Initial period when uncontrolled. Defaults to the first.' },
        { name: 'onPeriodChange', type: '(id: string) => void', optional: true },
        { name: 'cells', type: 'readonly ContributionCell[]', optional: false, description: 'Heatmap cells, column-major (`columns × 7`).' },
        { name: 'columns', type: 'number', optional: true, description: 'Heatmap columns. Default 38.' },
        { name: 'color', type: 'string', optional: true, description: 'Heatmap ramp base. Default violet-500 on the theme.' },
        { name: 'animateIn', type: 'boolean', optional: true, description: 'Pop the heatmap cells in on mount. Default `true`.' },
        { name: 'activeCell', type: 'number | null', optional: true },
        { name: 'onActiveCellChange', type: '(index: number | null) => void', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'AiProfileCard', propsType: 'AiProfileCardProps' },
  ],
}
