// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'alert-dialog',
  propTypes: {
    'AlertDialogProps': {
      props: [
        { name: 'visible', type: 'boolean', optional: false, description: 'Whether the dialog is mounted + visible (controlled).' },
        { name: 'onClose', type: '() => void', optional: false, description: 'Close request — backdrop tap, Escape, cancel, or after confirm.' },
        { name: 'title', type: 'string', optional: false, description: 'Headline.' },
        { name: 'description', type: 'string', optional: true, description: 'Supporting copy.' },
        { name: 'confirmLabel', type: 'string', optional: true, description: "Confirm button label. Defaults to `'Confirm'`." },
        { name: 'cancelLabel', type: 'string', optional: true, description: "Cancel button label. Defaults to `'Cancel'`." },
        { name: 'onConfirm', type: '() => void', optional: true, description: 'Confirm handler. The dialog closes after it runs (sync).' },
        { name: 'onCancel', type: '() => void', optional: true, description: 'Cancel handler. Runs in addition to `onClose`.' },
        { name: 'destructive', type: 'boolean', optional: true, description: 'Style the confirm button as destructive (negative color). Defaults to `false`.' },
        { name: 'hideCancel', type: 'boolean', optional: true, description: 'Render only the confirm button (no cancel). Defaults to `false`.' },
        { name: 'dismissible', type: 'boolean', optional: true, description: "Tap-outside / Escape dismisses. Defaults to `true` — matching the shared `Dialog` default and Mention's `ConfirmPrompt`. A backdrop / Escape dismissal always resolves the confirm as cancelled (`false`), so it is safe by default; pass `false` for a truly blocking confirm." },
        { name: 'cardStyle', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'AlertDialog', propsType: 'AlertDialogProps' },
  ],
}
