// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'animated-check',
  propTypes: {
    'AnimatedCheckProps': {
      props: [
        { name: 'size', type: 'number', optional: true, description: 'Width and height in px. Defaults to `24`.' },
        { name: 'color', type: 'string', optional: true, description: 'Stroke color of the ring and check. Defaults to the theme success color.' },
      ],
      inheritsFrom: ['RefAttributes<AnimatedCheckRef>'],
    },
  },
  components: [
    { name: 'AnimatedCheck', propsType: 'AnimatedCheckProps' },
  ],
}
