// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'appearance',
  propTypes: {
    'BloomScopeProps': {
      props: [
        { name: 'size', type: 'BloomSize', options: ['xs', 'sm', 'md', 'lg'], optional: true },
        { name: 'tone', type: 'BloomTone', options: ['neutral', 'accent', 'support', 'action', 'success', 'warning', 'danger', 'info'], optional: true },
      ],
      inheritsFrom: ['PropsWithChildren<BloomAppearanceProps>'],
    },
  },
  components: [
    { name: 'BloomScope', propsType: 'BloomScopeProps' },
  ],
}
