// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'aspect-ratio',
  propTypes: {
    'AspectRatioProps': {
      props: [
        { name: 'ratio', type: 'number', optional: true, description: 'Width divided by height — `16 / 9`, `1`, `4 / 3`. Defaults to `1`.' },
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'AspectRatio', propsType: 'AspectRatioProps' },
  ],
}
