// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'auth-card',
  propTypes: {
    'AuthCardProps': {
      props: [
        { name: 'mode', type: 'AuthMode', options: ['signin', 'signup', 'verify'], optional: true, description: '`signin` (default), `signup`, or `verify`. `verify` swaps the email fields for OTP boxes and drops the providers: the visitor has already chosen how they are signing in.' },
        { name: 'email', type: 'string', optional: true, description: '`verify` only: the address the code went to, shown in the description.' },
        { name: 'codeLength', type: 'number', optional: true, description: '`verify` only: how many digits. Defaults to 6.' },
        { name: 'onComplete', type: '(code: string) => void', optional: true, description: '`verify` only: fires once the last box is filled.' },
        { name: 'onResend', type: '() => void', optional: true, description: '`verify` only: the resend action.' },
        { name: 'layout', type: 'AuthLayout', options: ['stacked', 'inline', 'grid'], optional: true, description: 'How the provider buttons are arranged. Defaults to `stacked`.' },
        { name: 'providers', type: 'AuthProvider[]', optional: true, description: 'Defaults to Google, Apple, GitHub. An empty array hides the section.' },
        { name: 'title', type: 'ReactNode', optional: true },
        { name: 'description', type: 'ReactNode', optional: true },
        { name: 'media', type: 'ReactNode', optional: true, description: 'Artwork for the right half. Passing it turns the card into the split layout — form left, media right — which drops to the form alone below the `md` breakpoint (768) rather than stacking a tall image above the fields. `AuthMediaCarousel` is the batteries-included option.' },
        { name: 'logo', type: 'ReactNode', optional: true, description: 'Mark above the title. `verify` shows a mail-check glyph when omitted.' },
        { name: 'centered', type: 'boolean', optional: true, description: 'Centre the heading and the mark.' },
        { name: 'confirmPassword', type: 'boolean', optional: true, description: 'Sign-up only: adds a stacked confirm-password field.' },
        { name: 'footnote', type: 'ReactNode', optional: true, description: 'Small print under the card, outside its border.' },
        { name: 'onSubmit', type: '(values: AuthCardValues) => void', optional: true, description: "Fires with the form's values when the CTA is pressed (or Enter on web)." },
        { name: 'onProvider', type: '(provider: AuthProvider) => void', optional: true, description: 'A provider button was pressed.' },
        { name: 'switchHref', type: 'string', optional: true, description: 'Footer link target, e.g. the opposite mode. Rendered as a real `<a href>` on web; routed through `onNavigate` when that is given.' },
        { name: 'onSwitch', type: '() => void', optional: true, description: 'The footer link was pressed ("Create an account" / "Sign in").' },
        { name: 'forgotPasswordHref', type: 'string', optional: true, description: '"Forgot password?" target on web.' },
        { name: 'onForgotPassword', type: '() => void', optional: true, description: '"Forgot password?" was pressed.' },
        { name: 'onNavigate', type: '(href: string) => void', optional: true, description: "Client-side routing for the card's links: called with the `href` instead of letting the browser navigate. Without it a web link is a plain anchor." },
        { name: 'headingLevel', type: '1 | 2 | 3 | 4 | 5 | 6', optional: true, description: 'Heading level for the title. Defaults to `1`, because on a real sign-in screen the card IS the page; drop it to `2`+ where the card is embedded.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'AuthMediaCarouselProps': {
      props: [
        { name: 'slides', type: 'AuthMediaSlide[]', optional: false },
        { name: 'interval', type: 'number', optional: true, description: 'Milliseconds a slide rests at full bleed before the transition begins.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'AuthCard', propsType: 'AuthCardProps' },
    { name: 'AuthMediaCarousel', propsType: 'AuthMediaCarouselProps' },
  ],
}
