// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'badge',
  propTypes: {
    'BadgeProps': {
      props: [
        { name: 'content', type: 'string | number', optional: true, description: 'Text or number to display in the badge.' },
        { name: 'variant', type: 'AccentFill', options: ['solid', 'subtle', 'outlined'], optional: true, description: 'How loudly the badge is painted.' },
        { name: 'color', type: 'AccentTone', options: ['default', 'primary', 'success', 'warning', 'error', 'info'], optional: true, description: 'Semantic color.' },
        { name: 'size', type: 'BadgeSize', options: ['small', 'medium', 'large'], optional: true, description: 'Size preset.' },
        { name: 'dot', type: 'boolean', optional: true, description: "If true, renders as a small dot without content. A dot always paints the tone's fill, whatever the `variant`." },
        { name: 'max', type: 'number', optional: true, description: 'Maximum number to display. Values above this show "{max}+".' },
        { name: 'invisible', type: 'boolean', optional: true, description: 'If true, the badge is hidden.' },
        { name: 'placement', type: 'BadgePlacement', options: ['top-right', 'top-left', 'bottom-right', 'bottom-left'], optional: true, description: 'Where to position the badge relative to its child.' },
        { name: 'children', type: 'React.ReactNode', optional: true, description: 'The element the badge is attached to.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'textStyle', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Badge', propsType: 'BadgeProps' },
  ],
}
