// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'bottom-sheet',
  propTypes: {
    'BottomSheetProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false },
        { name: 'open', type: 'boolean', optional: true, description: 'Controlled open state. When provided, the sheet mounts already-open if `true` (seeding its internal visible/rendered state) instead of relying on an imperative `present()` after mount. This is what makes a responsive `Dialog` survive a placement swap (centered card ↔ bottom sheet on resize): the freshly-mounted sheet is visible on its first commit, with no present()-in-effect race that would otherwise leave it blank. Omit for the purely imperative `present()`/`dismiss()` API.' },
        { name: 'onDismiss', type: '() => void', optional: true },
        { name: 'enablePanDownToClose', type: 'boolean', optional: true },
        { name: 'backgroundComponent', type: '(props: { style?: StyleProp<ViewStyle>; }) => React.ReactElement | null', optional: true },
        { name: 'backdropComponent', type: '(props: { style?: StyleProp<ViewStyle>; onPress?: () => void; }) => React.ReactElement | null', optional: true },
        { name: 'style', type: 'StyleProp<AnimatedStyle<ViewStyle>>', optional: true, description: 'Style applied to the sheet container (the outer Animated.View positioned at the bottom of the screen). Use this to override `maxWidth`, `height`, background color, border radius, etc. Composed AFTER the internal sheet styles so it can override them.' },
        { name: 'enableHandlePanningGesture', type: 'boolean', optional: true },
        { name: 'onDismissAttempt', type: '() => boolean', optional: true },
        { name: 'detached', type: 'boolean', optional: true },
        { name: 'showHandle', type: 'boolean', optional: true, description: 'Whether to render the built-in (non-interactive) drag handle bar at the top of the sheet. Defaults to `true`. Set to `false` when the consumer renders its own handle (e.g. an interactive close affordance) inside `children`.' },
        { name: 'backdropOpacity', type: 'number', optional: true, description: 'Opacity of the dimming backdrop behind the sheet (0–1). Defaults to `0.5`. Set to a higher value (e.g. `0.7`) when the sheet is presented over another bottom sheet (Dialog cases) so the underlying handle/content does not bleed through.' },
        { name: 'scrollable', type: 'boolean', optional: true, description: 'When `true` (default), children are wrapped in an internal scrollable container — convenient for vertical content that can overflow.' },
        { name: 'manualActivation', type: 'boolean', optional: true, description: "When `true`, the body pan uses RNGH's `manualActivation` and only activates when (a) the inner ScrollView is at the top AND (b) the user has moved their finger downward by > 8dp. This is the" },
        { name: 'dynamicBackdrop', type: 'boolean', optional: true, description: 'When `true`, the backdrop dims proportionally with drag distance — the overlay fades from full opacity (sheet at rest) to 30% as the sheet is pulled down 40% of the screen height. iOS Photos style. The base `backdropOpacity` still controls the resting dim level.' },
        { name: 'handleComponent', type: '() => React.ReactNode', optional: true, description: 'Custom handle slot. When provided, replaces the default drag handle (the 36×5 pill). The rendered handle is wrapped in the dedicated handle gesture detector (when `manualActivation` is `true`) so it remains unconditionally draggable. `showHandle={false}` still suppresses any handle rendering — `handleComponent` is only consulted when `showHandle` is `true`.' },
        { name: 'scrollY', type: 'SharedValue<number>', optional: true, description: "External shared value the internal scroll handler mirrors the content offset into (in addition to its own gesture-gating offset). Lets a host — e.g. a Dialog nav-header — drive a collapse from the sheet's OWN scroller without owning the ScrollView. Optional; the standalone sheet ignores it." },
        { name: 'headerOverlay', type: 'React.ReactNode', optional: true, description: "Overlay slot rendered absolutely at the TOP of the sheet card, painted above the scrolling body (clipped to the sheet's rounded top). Used by the Dialog to float its sticky nav header over the sheet's scroll content." },
        { name: 'onLayout', type: '(event: LayoutChangeEvent) => void', optional: true, description: "Layout callback for the SHEET CARD — the same box `style` targets. Lets a host observe the card's rendered size (the Dialog measures it to morph the sheet between two content frames). Fires on every size change, including while a host animates the card's height." },
      ],
      inheritsFrom: ['RefAttributes<BottomSheetRef>'],
    },
  },
  components: [
    { name: 'BottomSheet', propsType: 'BottomSheetProps' },
  ],
}
