// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'button-group',
  propTypes: {
    'ButtonGroupProps': {
      props: [
        { name: 'material', type: 'ControlMaterial', options: ['solid', 'glass'], optional: true, description: "The material the group paints: `solid` (an opaque bordered pill, Bloom's default chrome) or `glass` (one translucent island the items sit flush on)." },
        { name: 'variant', type: 'ControlMaterial', options: ['solid', 'glass'], optional: true },
        { name: 'size', type: 'ButtonGroupSize', options: ['md', 'sm', 'medium', 'small'], optional: true, description: 'Size for every item that does not set its own. Inherited from the nearest `ControlSurface` when omitted, then `md`.' },
        { name: 'dividers', type: 'boolean', optional: true, description: 'Whether to draw the 1px hairlines BETWEEN items.' },
        { name: 'children', type: 'React.ReactNode', optional: false, description: '`ButtonGroupItem` children.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the group.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'ButtonGroupItemProps': {
      props: [
        { name: 'onPress', type: '(event: GestureResponderEvent) => void', optional: true, description: "Press handler. Receives the event, so a handler composed onto this item by an anchored family's `asChild` trigger can `preventDefault()` it — see `floating/TriggerSlot.tsx`." },
        { name: 'children', type: 'React.ReactNode', optional: true, description: 'Label. Ignored when `iconOnly`.' },
        { name: 'size', type: 'ButtonGroupSize', options: ['md', 'sm', 'medium', 'small'], optional: true, description: "Overrides the group's size." },
        { name: 'material', type: 'ControlMaterial', options: ['solid', 'glass'], optional: true, description: "Overrides the group's material. Rarely needed; the group owns it." },
        { name: 'variant', type: 'ControlMaterial', options: ['solid', 'glass'], optional: true },
        { name: 'checked', type: 'boolean', optional: true, description: 'Highlights the item like its hover state and announces it as pressed.' },
        { name: 'selected', type: 'boolean', optional: true },
        { name: 'onCheckedChange', type: '(checked: boolean) => void', optional: true },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'iconOnly', type: 'boolean', optional: true, description: 'Square item showing only `leadingIcon` — name it with `accessibilityLabel`.' },
        { name: 'leadingIcon', type: 'ButtonIconComponent', optional: true, description: 'Icon component before the label, sized and coloured by the item.' },
        { name: 'trailingIcon', type: 'ButtonIconComponent', optional: true, description: 'Icon component after the label.' },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'onLongPress', type: '(event: GestureResponderEvent) => void', optional: true, description: 'Long-press handler, composed by a `ContextMenu` trigger.' },
        { name: 'aria-expanded', type: 'boolean', optional: true, description: 'Set by an anchored family: whether the surface this opens is showing.' },
        { name: 'aria-haspopup', type: "WebAriaProps['aria-haspopup']", options: ['menu', 'listbox', 'tree', 'grid', 'dialog'], optional: true, description: 'Set by an anchored family: what kind of surface this opens.' },
        { name: 'accessibilityRole', type: "'button'", optional: true, description: 'Set by an anchored family. The item is a `button` either way.' },
        { name: 'hitSlop', type: 'number | { top?: number; bottom?: number; left?: number; right?: number; }', optional: true, description: 'Extra touch area around the item, in px.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'ButtonGroup', propsType: 'ButtonGroupProps' },
    { name: 'ButtonGroupItem', propsType: 'ButtonGroupItemProps' },
  ],
}
