// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'card',
  propTypes: {
    'CardProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'variant', type: 'CardVariant', options: ['plain', 'elevated', 'outlined', 'filled'], optional: true, description: 'Preset background + border + elevation. Default `elevated`.' },
        { name: 'radius', type: 'CardRadius', options: ['radius-2', 'radius-4', 'radius-8', 'radius-12', 'radius-16', 'radius-20', 'radius-24', 'radius-28', 'radius-max'], optional: true, description: 'Corner rung. Default `radius-12`.' },
        { name: 'elevation', type: 'CardElevation', options: ['none', 's', 'm', 'glass'], optional: true, description: "Overrides the variant's elevation." },
        { name: 'border', type: 'CardBorder', options: ['none', 'hairline', 'thin'], optional: true, description: "Overrides the variant's border width." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'className', type: 'string', optional: true },
        { name: 'onPress', type: '() => void', optional: true },
        { name: 'accessibilityRole', type: "'button' | 'link'", options: ['button', 'link'], optional: true, description: 'Role for the pressable form. A card that opens a URL is a `link`; a card that performs an in-app action is a `button` (the default).' },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'CardHeaderProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
      ],
    },
    'CardBodyProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
      ],
    },
    'CardFooterProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
      ],
    },
    'CardTitleProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'style', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'numberOfLines', type: 'number', optional: true },
      ],
    },
    'CardDescriptionProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'style', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'numberOfLines', type: 'number', optional: true },
      ],
    },
  },
  components: [
    { name: 'Card', propsType: 'CardProps' },
    { name: 'CardHeader', propsType: 'CardHeaderProps' },
    { name: 'CardBody', propsType: 'CardBodyProps' },
    { name: 'CardFooter', propsType: 'CardFooterProps' },
    { name: 'CardTitle', propsType: 'CardTitleProps' },
    { name: 'CardDescription', propsType: 'CardDescriptionProps' },
  ],
}
