// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'carousel',
  propTypes: {
    'CarouselProps': {
      props: [
        { name: 'children', type: 'ReactNode', optional: false, description: '`CarouselItem`s. Each is labelled "N of M" for assistive technology.' },
        { name: 'accessibilityLabel', type: 'string', optional: false, description: 'Names the carousel for assistive technology (a required `aria-label`). The region announces itself as a "carousel".' },
        { name: 'showArrows', type: 'boolean', optional: true, description: 'Previous / next buttons above the track. Defaults to `true`.' },
        { name: 'showDots', type: 'boolean', optional: true, description: 'Position indicator below the track. Defaults to `true`.' },
        { name: 'align', type: "'start' | 'center'", options: ['start', 'center'], optional: true, description: "Where a slide comes to rest when it snaps. Defaults to `'start'`." },
        { name: 'gap', type: 'number', optional: true, description: 'Gap between slides, in px. Defaults to `16`.' },
        { name: 'onIndexChange', type: '(index: number) => void', optional: true, description: 'Called when the slide in view changes.' },
        { name: 'previousLabel', type: 'string', optional: true, description: "Accessible name of the previous button. Defaults to `'Previous slide'`." },
        { name: 'nextLabel', type: 'string', optional: true, description: "Accessible name of the next button. Defaults to `'Next slide'`." },
        { name: 'dotLabel', type: '(slide: number) => string', optional: true, description: 'Accessible name of a dot. Defaults to `` n => `Go to slide ${n}` ``.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Style of the outer column (arrows, track, dots).' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'CarouselItemProps': {
      props: [
        { name: 'children', type: 'ReactNode', optional: false },
        { name: 'width', type: 'number', optional: true, description: "Slide width. Defaults to the track's full width, so exactly one slide is in view; pass a smaller number for a gallery that peeks the next slide." },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Overrides the default "N of M" accessible name.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Carousel', propsType: 'CarouselProps' },
    { name: 'CarouselItem', propsType: 'CarouselItemProps' },
  ],
}
