// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'carrier-quote',
  propTypes: {
    'CarrierQuoteCardProps': {
      props: [
        { name: 'quote', type: 'CarrierQuote', optional: false, description: 'The offer.' },
        { name: 'onAccept', type: '(id: string) => void', optional: true, description: "Draws the accept action. Called with the quote's id." },
        { name: 'onMessage', type: '(id: string) => void', optional: true, description: "Draws the message action. Called with the quote's id." },
        { name: 'onDecline', type: '(id: string) => void', optional: true, description: "Draws the decline action. Called with the quote's id." },
        { name: 'onPressCarrier', type: '(id: string) => void', optional: true, description: "Makes the identity block pressable — an app opens the carrier's profile from here." },
        { name: 'breakdown', type: 'boolean', optional: true, description: 'Draws the itemisation behind a disclosure under the tiles. Default `true` when the quote carries `priceLines`; `false` never draws it.' },
        { name: 'defaultBreakdownExpanded', type: 'boolean', optional: true, description: 'Starts the breakdown open. Default `false`.' },
        { name: 'density', type: 'CarrierQuoteDensity', options: ['comfortable', 'compact'], optional: true, description: 'Default `comfortable`.' },
        { name: 'selected', type: 'boolean', optional: true, description: 'Paints the card as the chosen offer: the accent border and a checked mark.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Dims the card and stops every action.' },
        { name: 'actions', type: 'ReactNode', optional: true, description: 'Replaces the three built-in actions entirely.' },
        { name: 'labels', type: 'CarrierQuoteLabels', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Overrides the composed name of the identity block.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'CarrierQuoteListProps': {
      props: [
        { name: 'quotes', type: 'readonly CarrierQuote[]', optional: false, description: "The offers. Order is the list's, not the caller's — see `sort`." },
        { name: 'sort', type: 'CarrierQuoteSort', options: ['price', 'eta', 'rating'], optional: true, description: 'Controlled sort.' },
        { name: 'defaultSort', type: 'CarrierQuoteSort', options: ['price', 'eta', 'rating'], optional: true, description: 'Uncontrolled initial sort. Default `price`.' },
        { name: 'onSortChange', type: '(sort: CarrierQuoteSort) => void', optional: true },
        { name: 'sortOptions', type: 'readonly CarrierQuoteSort[]', optional: true, description: 'Which orders are offered, in the order they are drawn. Default all three. An empty array draws no sort control — a list of two offers does not need one.' },
        { name: 'showCount', type: 'boolean', optional: true, description: 'Draws the count line over the list. Default `true`.' },
        { name: 'marks', type: 'boolean', optional: true, description: 'Marks the cheapest and the fastest offer. Default `true`. Every offer tied at the minimum is marked — two offers at the same price are both the cheapest, and picking one of them arbitrarily would be this component inventing a tie-break.' },
        { name: 'loading', type: 'boolean', optional: true, description: 'Replaces the list with placeholder cards.' },
        { name: 'loadingCount', type: 'number', optional: true, description: 'How many placeholders. Default `3`.' },
        { name: 'onAccept', type: '(id: string) => void', optional: true, description: 'Forwarded to every card.' },
        { name: 'onMessage', type: '(id: string) => void', optional: true },
        { name: 'onDecline', type: '(id: string) => void', optional: true },
        { name: 'onPressCarrier', type: '(id: string) => void', optional: true },
        { name: 'selectedId', type: 'string | null', optional: true, description: "The chosen offer's id, if one has been chosen." },
        { name: 'density', type: 'CarrierQuoteDensity', options: ['comfortable', 'compact'], optional: true },
        { name: 'breakdown', type: 'boolean', optional: true },
        { name: 'emptyTitle', type: 'string', optional: true, description: 'The line over the empty state. Default `"No offers yet"`.' },
        { name: 'emptyDescription', type: 'string', optional: true, description: 'Under it. Default `"Carriers are looking at your job. The first offers usually arrive within a few minutes."`.' },
        { name: 'emptyAction', type: 'ReactNode', optional: true, description: 'A control under the empty state — "Edit the job", "Invite a carrier".' },
        { name: 'labels', type: 'CarrierQuoteLabels', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the list. Default `"Offers"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Derives `-<quote id>` for each card.' },
      ],
    },
  },
  components: [
    { name: 'CarrierQuoteCard', propsType: 'CarrierQuoteCardProps' },
    { name: 'CarrierQuoteList', propsType: 'CarrierQuoteListProps' },
  ],
}
