// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'checkout-summary',
  propTypes: {
    'CheckoutConfirmProps': {
      props: [
        { name: 'label', type: 'string', optional: true, description: 'Default `"Place order"`.' },
        { name: 'amount', type: 'string', optional: true, description: 'The amount the press commits to, PRE-FORMATTED, drawn on the button after the label. It is on the BUTTON rather than beside it because the number a press commits to and the press are one decision.' },
        { name: 'secondaryAmount', type: 'string', optional: true, description: 'A second, PRE-FORMATTED rendering of `amount` — the buyer\'s currency beside the shop\'s, `"≈ 12,00 €"` — drawn de-emphasised, centred under the button. Named like `PriceLine.secondaryAmount`; drawn as given, nothing converts.' },
        { name: 'terms', type: 'ReactNode', optional: true, description: 'The terms line under the button — a string, or a node with links in it. `null` draws none.' },
        { name: 'onConfirm', type: '() => void', optional: true, description: 'Called at most once per busy cycle.' },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'busy', type: 'boolean', optional: true, description: 'The order is being placed: spinner, and every further press is dropped.' },
        { name: 'busyLabel', type: 'string', optional: true, description: 'Announced while busy, in place of the button\'s own name. Default `"Placing your order"`.' },
        { name: 'footer', type: 'ReactNode', optional: true, description: 'Under the terms line — "Cancel", a help link.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'CheckoutSummaryProps': {
      props: [
        { name: 'title', type: 'string | null', optional: true, description: 'The heading above the rows. `null` draws none.' },
        { name: 'address', type: 'CheckoutAddressSummary', optional: true, description: 'Where it goes.' },
        { name: 'delivery', type: 'CheckoutSummaryLine', optional: true, description: 'When it comes.' },
        { name: 'payment', type: 'ReactNode', optional: true, description: 'How it is paid — a SLOT, because the payment-method row is its own family. Anything that renders as a row goes here; `CheckoutSummaryRow` is exported so an app with no payment family yet can draw one in the same register.' },
        { name: 'note', type: 'CheckoutSummaryLine', optional: true, description: 'The note to the seller.' },
        { name: 'extras', type: 'readonly CheckoutSummaryLine[]', optional: true, description: 'Anything else this order needs a decision about, appended after the note.' },
        { name: 'price', type: 'PriceSummaryProps', optional: true, description: "What it costs — `price-breakdown`'s `PriceSummary`, passed through. There is no second breakdown in this family and no arithmetic anywhere." },
        { name: 'confirm', type: 'CheckoutConfirmProps', optional: true, description: 'The confirm control under the totals.' },
        { name: 'children', type: 'ReactNode', optional: true, description: 'Between the rows and the totals — a promo field, a tip picker.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the summary. Default the title, then `"Order summary"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'CheckoutSummaryRowProps': {
      props: [
        { name: 'content', type: 'ReactNode', optional: true, description: 'Replaces the value/detail column — an `AddressRow`, a two-line receipt, a row of chips. The label and the chevron stay.' },
        { name: 'leading', type: 'ReactNode', optional: true, description: 'An arbitrary leading node instead of the glyph tile. Read for PRESENCE: `leading={null}` draws no media at all.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'id', type: 'string', optional: true, description: 'Stable key. Defaults to the index.' },
        { name: 'label', type: 'string', optional: false, description: 'What the row is FOR — "Delivery window", "Note for the shop".' },
        { name: 'icon', type: 'BloomIconComponent', optional: true, description: 'The glyph in the leading tile.' },
        { name: 'value', type: 'string', optional: true, description: 'The chosen value, PRE-FORMATTED — "Today, 17:00 – 19:00", "€24.80". This family formats no dates and no money.' },
        { name: 'placeholder', type: 'string', optional: true, description: 'Drawn in place of the value while nothing is chosen. Default `"Not chosen yet"`.' },
        { name: 'detail', type: 'string', optional: true, description: 'A quieter third line — "Standard delivery", "Leave at the door".' },
        { name: 'badge', type: 'ReactNode', optional: true, description: 'A node beside the value — a `Badge` ("Free"), a `Chip`.' },
        { name: 'onPress', type: '() => void', optional: true, description: 'Opens whatever changes this row. Without it the row is a static summary.' },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'accessibilityHint', type: 'string', optional: true, description: 'What pressing the row does, announced as the row\'s hint. Default `"Opens the picker"`; it is a HINT and not part of the name, so a reader scanning the summary hears the values rather than "Change" five times.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Defaults to `"<label>: <value>"`.' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'CheckoutConfirm', propsType: 'CheckoutConfirmProps' },
    { name: 'CheckoutSummary', propsType: 'CheckoutSummaryProps' },
    { name: 'CheckoutSummaryRow', propsType: 'CheckoutSummaryRowProps' },
  ],
}
