// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'checkbox',
  propTypes: {
    'CheckboxProps': {
      props: [
        { name: 'checked', type: 'boolean', optional: false, description: 'Whether the checkbox is checked.' },
        { name: 'onCheckedChange', type: '(checked: boolean) => void', optional: false, description: 'Called when the checked state changes.' },
        { name: 'label', type: 'string', optional: true, description: 'Optional label text.' },
        { name: 'description', type: 'string', optional: true, description: 'Optional description shown below the label.' },
        { name: 'size', type: 'CheckboxSize', options: ['medium', 'sm', 'md', 'lg', 'xs', 'small', 'large'], optional: true, description: 'Size preset.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Whether the checkbox is disabled.' },
        { name: 'indeterminate', type: 'boolean', optional: true, description: 'Whether the checkbox is in an indeterminate state.' },
        { name: 'tone', type: 'BloomTone', options: ['neutral', 'accent', 'support', 'action', 'success', 'warning', 'danger', 'info'], optional: true, description: 'Semantic color when checked. Uses theme primary by default.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'labelStyle', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'nativeID', type: 'string', optional: true, description: "The control's id. Inside a `Field` the field supplies one, so the label's `htmlFor` points at this control on web." },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'CheckboxCardProps': {
      props: [
        { name: 'checked', type: 'boolean', optional: false, description: "Whether the card's checkbox is checked." },
        { name: 'onCheckedChange', type: '(checked: boolean) => void', optional: false, description: 'Called when the checked state changes. A press anywhere on the card toggles it.' },
        { name: 'title', type: 'string', optional: false, description: "The card's title (one line); also its accessible name." },
        { name: 'description', type: 'string', optional: true, description: 'Optional one-line description under the title.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Dims the whole card and stops it toggling.' },
        { name: 'indeterminate', type: 'boolean', optional: true, description: 'Whether the checkbox is in an indeterminate state.' },
        { name: 'tone', type: 'BloomTone', options: ['neutral', 'accent', 'support', 'action', 'success', 'warning', 'danger', 'info'], optional: true, description: 'Accent for the checked box. Uses the theme primary by default.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Checkbox', propsType: 'CheckboxProps' },
    { name: 'CheckboxCard', propsType: 'CheckboxCardProps' },
  ],
}
