// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'chip',
  propTypes: {
    'ChipProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true, description: 'Text content of the chip.' },
        { name: 'variant', type: 'AccentFill', options: ['solid', 'subtle', 'outlined'], optional: true, description: 'How loudly the chip is painted. `subtle` used to be spelled `soft` here and `subtle` on `Badge` — one concept, two names, resolved by the shared AccentFill.' },
        { name: 'color', type: 'AccentTone', options: ['default', 'primary', 'success', 'warning', 'error', 'info'], optional: true, description: 'Semantic color.' },
        { name: 'size', type: 'ChipSize', options: ['small', 'medium', 'large'], optional: true, description: 'Size preset.' },
        { name: 'startIcon', type: 'React.ReactNode', optional: true, description: 'Icon rendered before the label.' },
        { name: 'endIcon', type: 'React.ReactNode', optional: true, description: 'Icon or close button rendered after the label.' },
        { name: 'onPress', type: '() => void', optional: true, description: 'Called when the chip is pressed. Makes the chip interactive.' },
        { name: 'onClose', type: '() => void', optional: true, description: 'Called when the close/end icon is pressed.' },
        { name: 'selected', type: 'boolean', optional: true, description: 'Whether the chip is in a selected state.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Whether the chip is disabled.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'textStyle', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Chip', propsType: 'ChipProps' },
  ],
}
