// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'combobox',
  propTypes: {
    'ComboboxProps<T>': {
      props: [
        { name: 'options', type: 'ComboboxOption<T>[]', optional: false, description: 'All selectable options.' },
        { name: 'value', type: 'T | null', optional: false, description: 'Currently selected value (controlled). `null` = nothing selected.' },
        { name: 'onValueChange', type: '(value: T) => void', optional: false, description: 'Fired when the user picks an option.' },
        { name: 'placeholder', type: 'string', optional: true, description: 'Placeholder shown in the input when nothing is selected.' },
        { name: 'label', type: 'string', optional: true, description: "Accessible label for the input. Defaults to `placeholder` or `'Search'`." },
        { name: 'emptyText', type: 'string', optional: true, description: "Text shown when the filtered list is empty. Defaults to `'No results'`." },
        { name: 'filter', type: '(option: ComboboxOption<T>, query: string) => boolean', optional: true, description: 'Custom filter predicate. Defaults to a case-insensitive substring match against `label` and `description`.' },
        { name: 'query', type: 'string', optional: true, description: 'Controlled query text. When omitted the combobox owns the query.' },
        { name: 'onQueryChange', type: '(query: string) => void', optional: true, description: 'Notified on query changes (works controlled or uncontrolled).' },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'maxListHeight', type: 'number', optional: true, description: 'Max height of the option list in px. Defaults to `280`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Combobox', propsType: 'ComboboxProps<T>' },
  ],
}
