// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'composer-loader',
  propTypes: {
    'ComposerLoaderProps': {
      props: [
        { name: 'children', type: 'ReactNode', optional: false },
        { name: 'active', type: 'boolean', optional: true, description: 'Show the light. Fades in/out (450ms) — flip it while awaiting a response. Default `true`.' },
        { name: 'colors', type: 'ComposerLoaderColors', optional: true, description: 'Four gradient colours, spread across the pill left → right. Default an iridescent set.' },
        { name: 'speed', type: 'number', optional: true, description: 'Seconds per full lap. Default `4.5`.' },
        { name: 'intensity', type: 'number', optional: true, description: 'Overall light opacity. Default `0.7`.' },
        { name: 'bloom', type: 'number', optional: true, description: 'How far the bloom bleeds inward from the rim, px. `0` drops the bloom layer. Default `16`.' },
        { name: 'bloomStrength', type: 'number', optional: true, description: 'Bloom layer opacity. Default `0.3`.' },
        { name: 'arc', type: 'number', optional: true, description: 'How much of the perimeter the band occupies, degrees (of 360). Default `120`.' },
        { name: 'reverse', type: 'boolean', optional: true, description: 'Reverse the travel direction.' },
        { name: 'radius', type: 'number', optional: true, description: 'Corner radius, px. Defaults to a full pill.' },
        { name: 'line', type: 'number', optional: true, description: 'Width of the crisp line, px; the tight glow scales with it. Default `2.5`.' },
        { name: 'bloomOnly', type: 'boolean', optional: true, description: 'Draw the wide bloom alone, no line or tight glow: a soft wash for a beam to lead.' },
        { name: 'surface', type: 'boolean', optional: true, description: 'Paint the pill surface (and its `shadow-xs`) behind the light. Default `true`.' },
        { name: 'taper', type: 'number', optional: true, description: "Fade the band's two ends instead of cutting them, 0–1: the fraction of the band's length that ramps. Each layer is stacked as 14 shorter, centred copies at a fraction of its opacity; the blur melts the steps together." },
        { name: 'blend', type: "ViewStyle['mixBlendMode']", options: ['normal', 'multiply', 'screen', 'overlay', 'darken', 'lighten', 'color-dodge', 'color-burn', 'hard-light', 'soft-light', 'difference', 'exclusion', 'hue', 'saturation', 'color', 'luminosity'], optional: true, description: "How the light composites over what's beneath, e.g. `screen` to read as light on a surface." },
        { name: 'offset', type: 'number', optional: true, description: 'Moves the band forward along the lap, as a fraction of the perimeter (0–1). Lets two loaders on one pill line up: a short beam with `offset` equal to the difference of the two arcs (as fractions) leads a wider glow tip to tip.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Outer wrapper style (width, margins…).' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'ComposerLoader', propsType: 'ComposerLoaderProps' },
  ],
}
