// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'contact-card',
  propTypes: {
    'ContactProfileCardProps': {
      props: [
        { name: 'kind', type: 'ContactSubjectKind', options: ['person', 'company'], optional: true, description: 'Default `person`.' },
        { name: 'name', type: 'string', optional: false, description: "The person's name, or the company's." },
        { name: 'role', type: 'string', optional: true, description: "A person's job title, or a company's industry." },
        { name: 'company', type: 'string', optional: true, description: 'The account a person belongs to. Ignored when `kind` is `company`.' },
        { name: 'avatar', type: 'string', optional: true, description: 'Photo or logo: a URL or an `ImageResolver` id. Without it the avatar draws a monogram.' },
        { name: 'coverSource', type: 'string | ImageSourcePropType | null', optional: true, description: 'The image across the cover band. Without one the band is an accent wash in `coverTone` — a record always has a cover, because the mark overlaps it and a mark hanging off nothing is the one arrangement that reads as a mistake. `compact` draws no band at all.' },
        { name: 'coverTone', type: 'AccentTone', options: ['default', 'primary', 'secondary', 'tertiary', 'success', 'warning', 'error', 'info'], optional: true, description: 'The wash behind the cover when there is no image. Default `primary`.' },
        { name: 'status', type: 'ContactStatus', optional: true },
        { name: 'channels', type: 'readonly ContactChannel[]', optional: true, description: 'Reachable channels, drawn as glyph actions in the order given.' },
        { name: 'owner', type: 'ContactOwner', optional: true },
        { name: 'headline', type: 'ContactProfileHeadline', optional: true, description: 'The figure over the tiles. `comfortable` only.' },
        { name: 'stats', type: 'readonly ContactProfileStat[]', optional: true, description: 'The numbers a CRM record is read for — open deals, pipeline, last touch, reply time. One row of tiles from CONTACT_NARROW_WIDTH up, two columns below it. `comfortable` only.' },
        { name: 'tags', type: 'readonly string[]', optional: true, description: 'Read-only attribute pills, in the chip row UNDER the tiles. The INPUT for these is `tag-field`, a family of its own — this card never edits a tag.' },
        { name: 'lastTouch', type: 'string', optional: true, description: 'Pre-formatted ("Last contacted 6 days ago"). The app owns the arithmetic. The first chip of the row on a card; a quiet third line in a row.' },
        { name: 'lastTouchTone', type: 'AccentTone', options: ['default', 'primary', 'secondary', 'tertiary', 'success', 'warning', 'error', 'info'], optional: true, description: 'Colours `lastTouch` through the accent pair. Omitted, it is quiet text.' },
        { name: 'facts', type: 'readonly string[]', optional: true, description: 'Short unlabelled facts — "48 people", "Madrid", "Customer since 2024". They join the chip row after the last touch. A fact with a LABEL is a `stats` tile instead, and a number a record is read for belongs there.' },
        { name: 'people', type: 'readonly ContactProfilePerson[]', optional: true, description: 'The people at the company, or the colleagues of a person. `comfortable` only.' },
        { name: 'peopleLabel', type: 'string', optional: true, description: 'The caption beside the facepile ("12 people").' },
        { name: 'peopleTotal', type: 'number', optional: true, description: 'Real total, when `people` is a sample. Drives the `+N` chip.' },
        { name: 'density', type: 'ContactProfileDensity', options: ['comfortable', 'compact'], optional: true, description: 'Default `comfortable`.' },
        { name: 'onPress', type: '() => void', optional: true, description: 'Opens the record. It is bound to the IDENTITY BLOCK, not to the whole card — see `docs/contact-card.mdx`; the channel actions sit outside it so nothing nests a control inside a control.' },
        { name: 'actions', type: 'ReactNode', optional: true, description: 'Trailing slot, outside the press target: a menu trigger, an assign button.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the press target. Defaults to the name, the role and the company.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'ContactProfileCard', propsType: 'ContactProfileCardProps' },
  ],
}
