// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'context-menu',
  propTypes: {
    'ContextMenuProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'onOpenChange', type: '(open: boolean) => void', optional: true, description: 'Called whenever the menu opens or closes, from any cause.' },
      ],
    },
    'ContextMenuTriggerProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'asChild', type: 'boolean', optional: true, description: "Render the single element child AS the trigger, merging the open handler and a11y props into it. Without it the children render inside Bloom's own `Pressable`." },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'label', type: 'string', optional: true, description: 'Accessible name. Ignored when the `asChild` child carries its own.' },
        { name: 'className', type: 'string', optional: true, description: 'Applied to the measured anchor wrapper; the context trigger draws no chrome.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'OverlaySurfaceProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'label', type: 'string', optional: true, description: 'Accessible name of the surface.' },
        { name: 'dismissible', type: 'boolean', optional: true, description: 'Dismiss on outside press and Escape. Defaults to `true`.' },
        { name: 'minWidth', type: 'number', optional: true },
        { name: 'maxWidth', type: 'number', optional: true },
        { name: 'className', type: 'string', optional: true, description: "Appended to the surface's own chrome — see FloatingPanelProps.className." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
        { name: 'side', type: 'FloatingSide', options: ['top', 'bottom', 'left', 'right'], optional: true, description: "Preferred side of the anchor. Defaults to `'bottom'`." },
        { name: 'align', type: 'FloatingAlign', options: ['start', 'center', 'end'], optional: true, description: 'Horizontal alignment against the anchor. Defaults per component.' },
        { name: 'sideOffset', type: 'number', optional: true, description: 'Gap between the anchor and the surface, on the `side` axis.' },
        { name: 'alignOffset', type: 'number', optional: true, description: 'Shift along the `align` axis, applied before the viewport clamp.' },
      ],
    },
  },
  components: [
    { name: 'ContextMenu', propsType: 'ContextMenuProps' },
    { name: 'ContextMenuTrigger', propsType: 'ContextMenuTriggerProps' },
    { name: 'ContextMenuContent', propsType: 'OverlaySurfaceProps' },
  ],
}
