// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'content-panel',
  propTypes: {
    'ContentPanelProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false },
        { name: 'framed', type: 'boolean', optional: true, description: 'Framing mode. Tri-state, resolved purely with NativeWind — no consumer breakpoint hook needed: - `undefined` (DEFAULT) → responsive: full-bleed below the `framedFrom` breakpoint, rounded + bordered at/above it. - `false` → never framed (plain full-bleed at every size). - `true` → always rounded + bordered.' },
        { name: 'framedFrom', type: 'ContentPanelFramedBreakpoint', optional: true, description: 'Viewport width at which the RESPONSIVE panel switches from full-bleed to framed. Only meaningful when `framed` is `undefined` (responsive) — ignored when `framed` is `true` (always framed) or `false` (never framed). Defaults to `768` (Tailwind `md`), reproducing the prior fixed behavior exactly.' },
        { name: 'chrome', type: 'ContentPanelChrome', options: ['elevated', 'border', 'none'], optional: true, description: "The panel's EDGE, when it is framed." },
        { name: 'shadow', type: 'string', optional: true, description: 'Overrides the shadow `chrome="elevated"` draws (any `box-shadow` string). For an app that wants its own elevation without giving up the hairline.' },
        { name: 'fill', type: 'boolean', optional: true, description: 'The panel is the HEIGHT OF THE SPACE IT IS GIVEN, and its content scrolls inside it — instead of the panel growing with its content while the page scrolls underneath.' },
        { name: 'surfaceClassName', type: 'string', optional: true, description: 'Override the surface background utility (defaults to `bg-card`).' },
        { name: 'surfaceStyle', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'surfaceColor', type: 'string', optional: true, description: 'The colour this panel paints, when `surfaceClassName`/`surfaceStyle` has repainted it.' },
        { name: 'contentClassName', type: 'string', optional: true, description: 'Extra utilities for the inner content wrapper.' },
        { name: 'contentStyle', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'showStickyFrame', type: 'boolean', optional: true, description: 'Whether to render the WEB sticky border frame. No-op on native (the border is always part of the surface).' },
        { name: 'maskColor', type: 'string', optional: true, description: 'Color of the WEB sticky bleed-mask gutter ring. Accepted for cross-platform API parity — no-op on native (there is no bleed-mask), like `framed`.' },
        { name: 'overlaySizing', type: "'viewport' | 'panel'", options: ['viewport', 'panel'], optional: true, description: 'How the WEB overlays (the bleed-mask and the border frame) size themselves. No-op on native (there are no overlays to size).' },
        { name: 'overlayInset', type: 'number | { top: number; bottom: number; }', optional: true, description: "The gap between the VIEWPORT's edge and the sticky frame, in `'viewport'` mode. Default 8." },
      ],
    },
  },
  components: [
    { name: 'ContentPanel', propsType: 'ContentPanelProps' },
  ],
}
