// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'content-panel',
  propTypes: {
    'ContentPanelProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false },
        { name: 'framed', type: 'boolean', optional: true, description: 'Framing mode. Tri-state, resolved purely with NativeWind — no consumer breakpoint hook needed: - `undefined` (DEFAULT) → responsive: full-bleed below the `framedFrom` breakpoint, rounded + bordered at/above it. - `false` → never framed (plain full-bleed at every size). - `true` → always rounded + bordered.' },
        { name: 'framedFrom', type: 'ContentPanelFramedBreakpoint', optional: true, description: 'Viewport width at which the RESPONSIVE panel switches from full-bleed to framed. Only meaningful when `framed` is `undefined` (responsive) — ignored when `framed` is `true` (always framed) or `false` (never framed). Defaults to `768` (Tailwind `md`), reproducing the prior fixed behavior exactly.' },
        { name: 'surfaceClassName', type: 'string', optional: true, description: 'Override the surface background utility (defaults to `bg-card`).' },
        { name: 'surfaceStyle', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'contentClassName', type: 'string', optional: true, description: 'Extra utilities for the inner content wrapper.' },
        { name: 'contentStyle', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'showStickyFrame', type: 'boolean', optional: true, description: 'Whether to render the WEB sticky border frame. No-op on native (the border is always part of the surface).' },
        { name: 'maskColor', type: 'string', optional: true, description: 'Color of the WEB sticky bleed-mask gutter ring. Accepted for cross-platform API parity — no-op on native (there is no bleed-mask), like `framed`.' },
      ],
    },
  },
  components: [
    { name: 'ContentPanel', propsType: 'ContentPanelProps' },
  ],
}
