// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'cover-header',
  propTypes: {
    'CoverHeaderProps': {
      props: [
        { name: 'coverSource', type: 'string | ImageSourcePropType | null', optional: true, description: 'Photo across the cover band. Without one the band shows `background-tertiary`.' },
        { name: 'coverPosition', type: '{ x: number; y: number; }', optional: true, description: 'Where the photo\'s crop sits, as fractions (`object-position`). Default `{ x: 0.5, y: 0.5 }` — centred, as `resizeMode="cover"`.' },
        { name: 'cover', type: 'ReactNode', optional: true, description: 'Drawn in the band instead of the photo (an editor, a gradient, a video poster).' },
        { name: 'coverHeight', type: 'number', optional: true, description: 'Height of the cover band. Default `170`.' },
        { name: 'overlap', type: 'number', optional: true, description: 'How far the content rises into the cover band. Default `45` — half a 90px avatar. Clamped to `0..coverHeight`.' },
        { name: 'coverStyle', type: 'StyleProp<ViewStyle>', optional: true, description: "The band's own style: corner radii, a different fill." },
        { name: 'contentStyle', type: 'StyleProp<ViewStyle>', optional: true, description: "The content column's style. Its `paddingTop` is the component's and is ignored." },
        { name: 'children', type: 'ReactNode', optional: true, description: 'The content: the avatar row first, then whatever follows it.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Also names the parts: `-cover`, `-cover-image`, `-content`.' },
      ],
    },
  },
  components: [
    { name: 'CoverHeader', propsType: 'CoverHeaderProps' },
  ],
}
