// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'delivery-slot',
  propTypes: {
    'DeliverySlotDaysProps': {
      props: [
        { name: 'days', type: 'readonly DeliveryDay[]', optional: false },
        { name: 'value', type: 'string', optional: true, description: "The chosen day's `id`." },
        { name: 'onChange', type: '(id: string) => void', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the strip. Default `"Day"`.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Disables every day. A day may also disable itself.' },
        { name: 'fadeColor', type: 'string', optional: true, description: "The colour the strip's scroll fade blends into — the surface behind it. Defaults to the page background, which is wrong on a card, so say so." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'DeliverySlotOptionProps': {
      props: [
        { name: 'label', type: 'string', optional: false, description: 'The line a reader chooses by — "17:00 – 19:00", "As soon as possible".' },
        { name: 'detail', type: 'string', optional: true, description: 'Under it — "Standard · 2 left", "Sold out".' },
        { name: 'price', type: 'string', optional: true, description: 'At the end of the row, PRE-FORMATTED — "Free", "+€2.50".' },
        { name: 'badge', type: 'ReactNode', optional: true, description: 'A node after the label — a `Badge` ("Express").' },
        { name: 'icon', type: 'BloomIconComponent', optional: true, description: 'A glyph BEFORE the label — the lightning the ASAP row carries. It does not replace the radio dot: the dot is what says "one of these", and a row that dropped it would look like a different control inside the same group.' },
        { name: 'selected', type: 'boolean', optional: true },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'onPress', type: '() => void', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Default: the label, the detail and the price, as one utterance.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'DeliverySlotPickerProps': {
      props: [
        { name: 'label', type: 'string', optional: true, description: "The name of the choice, which is also the radio group's accessible name." },
        { name: 'description', type: 'string', optional: true, description: 'Under the group — "Windows fill up; yours is held for 10 minutes." Ignored inside another `Field`.' },
        { name: 'error', type: 'string | null', optional: true, description: 'A non-empty string puts the field in its invalid state. Ignored inside another `Field`.' },
        { name: 'required', type: 'boolean', optional: true, description: 'Ignored inside another `Field`.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Disables the strip and every option. An option may also disable itself.' },
        { name: 'days', type: 'readonly DeliveryDay[]', optional: false },
        { name: 'day', type: 'string', optional: true, description: "The chosen day's `id`." },
        { name: 'onDayChange', type: '(id: string) => void', optional: true },
        { name: 'dayLabel', type: 'string', optional: true, description: 'Names the day strip. Default `"Day"`.' },
        { name: 'windows', type: 'readonly DeliveryWindow[]', optional: false, description: 'The windows OF THE CHOSEN DAY. The app reloads them when the day changes.' },
        { name: 'value', type: 'string', optional: true, description: "The chosen window's — or the ASAP option's — `id`." },
        { name: 'onValueChange', type: '(id: string) => void', optional: true },
        { name: 'asap', type: 'DeliveryAsapOption', optional: true, description: 'The option that is not a window.' },
        { name: 'loading', type: 'boolean', optional: true, description: 'Draws placeholder rows instead of the windows, announced as busy.' },
        { name: 'loadingRows', type: 'number', optional: true, description: 'How many placeholder rows. Default 3.' },
        { name: 'empty', type: 'ReactNode', optional: true, description: 'Replaces the whole empty block.' },
        { name: 'emptyTitle', type: 'string', optional: true, description: 'Default `"No windows left"`.' },
        { name: 'emptyDescription', type: 'string', optional: true, description: 'Default `"Pick another day, or take the next courier."`' },
        { name: 'tierLabels', type: 'Partial<Record<DeliveryTier, string>>', optional: true, description: 'Defaults: `standard` → "Standard", `express` → "Express".' },
        { name: 'soldOutLabel', type: 'string', optional: true, description: 'Default `"Sold out"`.' },
        { name: 'fadeColor', type: 'string', optional: true, description: "The colour the day strip's fade blends into. See `DeliverySlotDaysProps`." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'DeliverySlotDays', propsType: 'DeliverySlotDaysProps' },
    { name: 'DeliverySlotOption', propsType: 'DeliverySlotOptionProps' },
    { name: 'DeliverySlotPicker', propsType: 'DeliverySlotPickerProps' },
  ],
}
