// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'dialog',
  propTypes: {
    'DialogProps': {
      props: [
        { name: 'control', type: 'DialogControlProps', optional: true, description: 'Imperative open/close handle from `useDialogControl()`. Optional — omit it when driving the dialog with the controlled `open` prop instead.' },
        { name: 'open', type: 'boolean', optional: true, description: 'Controlled open state (opt-in). When provided, the dialog is driven by this boolean and `onClose`, and `control` is ignored.' },
        { name: 'onClose', type: '() => void', optional: true, description: 'Fires after the dialog has finished closing. In controlled mode it is the close request the host must answer by flipping `open` to `false`.' },
        { name: 'testID', type: 'string', optional: true },
        { name: 'title', type: 'string', optional: true, description: 'Optional dialog header text. Rendered above `description` / `children`.' },
        { name: 'description', type: 'string', optional: true, description: 'Optional supporting copy, rendered below the title.' },
        { name: 'actions', type: 'DialogAction[]', optional: true, description: 'Optional action row. When provided, bloom renders the appropriate confirm/cancel/destructive buttons for you. Order is preserved.' },
        { name: 'placement', type: 'ResponsiveDialogPlacement', optional: true, description: "Surface anchor. Defaults to `'center'` (the centered modal — current behavior). `'left'`/`'right'` render an anchored side-sheet, `'bottom'` a bottom-sheet. A responsive map resolves by viewport width, e.g. `{ base: 'bottom', md: 'left' }` (drawer on wide, sheet on narrow)." },
        { name: 'width', type: 'number', optional: true, description: 'Side-sheet width (px) on wide screens. Defaults to `460`.' },
        { name: 'maxWidth', type: 'number', optional: true, description: 'Centered-card max width (px). Defaults to `480`.' },
        { name: 'maxHeightRatio', type: 'number', optional: true, description: 'Bottom-sheet max height as a fraction of the viewport height. Defaults to `0.9`.' },
        { name: 'inset', type: 'DialogInset', optional: true, description: "Side-sheet inset (px) from the root overlay's edges." },
        { name: 'showHandle', type: 'boolean', optional: true, description: 'Whether to render the drag handle in bottom-sheet mode. Defaults to `true`.' },
        { name: 'header', type: 'DialogHeaderConfig', optional: true, description: "Turns on the Dialog's OWN navigation header (see DialogHeaderConfig). When present the Dialog renders a sticky gradient nav bar + a large collapsing title over its own scroll content, and its content is inset below the bar — a DISTINCT mode from the declarative `title`/`description`/`actions` centered heading (a confirm/alert dialog passes NO `header` and is unchanged). Screens render no header of their own; the title/slots come from this config, refined at runtime by a mounted screen's `useDialogHeader` contribution." },
        { name: 'startOpen', type: 'boolean', optional: true, description: "Open-INTENT seed for a freshly-mounted placement branch, distinct from the controlled `open` prop. It ONLY seeds a branch's initial visible state on mount — it never switches the dialog into controlled close semantics, so the imperative `control.close()` still owns the exit animation and fires `onClose` post-exit (no synchronous-`onClose` entry leak). Set by the surface stack so a responsive `Dialog` that swaps its inner component across a breakpoint (centered card ↔ bottom sheet on resize) re-mounts the new branch ALREADY OPEN instead of blank. Ignored when the controlled `open` prop is provided (that path seeds itself)." },
        { name: 'scrollable', type: 'boolean', optional: true, description: 'Whether the dialog wraps its content in an internal scroll container. Defaults to `true`. Set `false` when the content owns its own scrolling primitive (a `FlatList` / `SectionList` / any VirtualizedList, or its own `ScrollView`): the surface then renders children WITHOUT a ScrollView wrap — a bounded, overflow-clipped card on the centered/side placements and a non-scrollable `BottomSheet` body on the bottom placement — so the child gets a bounded height and owns its scroll, and no "VirtualizedList inside a plain ScrollView" warning is emitted.' },
        { name: 'contentPadding', type: 'number', optional: true, description: 'Inner padding (px) of the dialog content container, applied uniformly across every placement (centered panel, side-sheet body, bottom-sheet body). Defaults to `20`.' },
        { name: 'dismissOnBackdrop', type: 'boolean', optional: true, description: 'Whether tapping the backdrop dismisses the dialog. Defaults to `true`.' },
        { name: 'morph', type: 'boolean', optional: true, description: 'Whether the panel MORPHS across an in-place content swap. Defaults to `true`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Style overrides applied to the inner content container on native (the floating bottom-sheet card) and to the modal panel on web.' },
        { name: 'panelStyle', type: 'StyleProp<ViewStyle>', optional: true, description: 'Style overrides for the side/bottom placement panel surface.' },
        { name: 'panelClassName', type: 'string', optional: true, description: 'NativeWind classes for the side/bottom placement panel surface.' },
        { name: 'containerStyle', type: 'StyleProp<ViewStyle>', optional: true, description: 'Style for the root overlay (theme-var scope, rail offset, etc.).' },
        { name: 'containerClassName', type: 'string', optional: true, description: 'NativeWind classes for the root overlay (e.g. `"md:left-[4.75rem]"`).' },
        { name: 'label', type: 'string', optional: true, description: 'Accessibility label, applied to the dialog role on web.' },
      ],
      inheritsFrom: ['React.PropsWithChildren<…>'],
    },
  },
  components: [
    { name: 'Dialog', propsType: 'DialogProps' },
  ],
}
