// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'divider',
  propTypes: {
    'DividerProps': {
      props: [
        { name: 'color', type: 'string', optional: true, description: 'Custom color (defaults to theme.colors.border)' },
        { name: 'thickness', type: 'number', optional: true, description: 'Line thickness (defaults to StyleSheet.hairlineWidth)' },
        { name: 'vertical', type: 'boolean', optional: true, description: 'If true, renders a vertical divider' },
        { name: 'spacing', type: 'number', optional: true, description: 'Spacing around the divider (marginVertical for horizontal, marginHorizontal for vertical)' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Custom style' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Divider', propsType: 'DividerProps' },
  ],
}
