// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'dot-grid-meter',
  propTypes: {
    'DotGridMeterProps': {
      props: [
        { name: 'filled', type: 'number', optional: false, description: 'Number of filled dots (clamped to `[0, total]`).' },
        { name: 'total', type: 'number', optional: false, description: 'Total number of dots in the grid.' },
        { name: 'columns', type: 'number', optional: true, description: 'Dots per row before wrapping.' },
        { name: 'dotSize', type: 'number', optional: true, description: 'Diameter of each dot in px.' },
        { name: 'gap', type: 'number', optional: true, description: 'Gap between dots in px (both axes).' },
        { name: 'filledColor', type: 'string', optional: true, description: 'Color of a filled dot.' },
        { name: 'emptyColor', type: 'string', optional: true, description: 'Color of an empty dot.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: "The meter's accessible NAME — what is being measured." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Container style override.' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'DotGridMeter', propsType: 'DotGridMeterProps' },
  ],
}
