// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'empty-state',
  propTypes: {
    'EmptyStateProps': {
      props: [
        { name: 'icon', type: 'BloomIconComponent', optional: true, description: 'The glyph. Omit it (and `illustration`) for a block that is text only — a table band, a search result count — which is a real shape and not a degraded one.' },
        { name: 'media', type: 'EmptyStateMedia', options: ['glyph', 'circle'], optional: true, description: 'Default `glyph`. Ignored when `illustration` is set.' },
        { name: 'illustration', type: 'ReactNode', optional: true, description: 'An arbitrary mark above the title — an image, a `Skeleton` stack, an `AnimatedCheck`. WINS over `icon`, and takes no tile of its own: whatever is passed is drawn exactly as it comes.' },
        { name: 'title', type: 'string', optional: true, description: '"Nothing here yet". A block with no title is a single explanatory line.' },
        { name: 'description', type: 'string', optional: true, description: 'The one line that says why, and what would change it.' },
        { name: 'action', type: 'EmptyStateAction', optional: true, description: 'The thing to do about it.' },
        { name: 'secondaryAction', type: 'EmptyStateAction', optional: true, description: 'The other thing to do about it. Drawn beside `action`, quieter.' },
        { name: 'children', type: 'ReactNode', optional: true, description: "Anything between the explanation and the actions — a reference chip, a status strip, a list of facts. Stretched to the block's full width and left to lay itself out, because the things that go here are not centred text." },
        { name: 'footer', type: 'ReactNode', optional: true, description: 'Under the actions: a note, a link, a row of suggestions. Centred.' },
        { name: 'variant', type: 'EmptyStateVariant', options: ['comfortable', 'compact'], optional: true, description: 'Default `comfortable`.' },
        { name: 'minHeight', type: 'number', optional: true, description: 'A floor for the block, for an empty state that has to hold a band open — a table body, a panel that must not collapse. The content centres in it.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the block. Defaults to the title, so a screen reader reaches one named `group` instead of three unrelated strings.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'EmptyState', propsType: 'EmptyStateProps' },
  ],
}
