// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'error-boundary',
  propTypes: {
    'ErrorBoundaryProps': {
      props: [
        { name: 'children', type: 'ReactNode', optional: false },
        { name: 'fallback', type: 'ErrorBoundaryFallback', optional: true, description: 'Custom fallback UI to render on error. Accepts either: - a ReactNode (static — same UI on every error), or - a render-prop `(ctx) => ReactNode` receiving `{ error, errorInfo, retry, retryCount }`.' },
        { name: 'title', type: 'string', optional: true, description: "Error title (`'Something went wrong'` in English, localised via `BloomProvider locale`)" },
        { name: 'message', type: 'string', optional: true, description: "Error message (`'An unexpected error occurred'` in English)" },
        { name: 'retryLabel', type: 'string', optional: true, description: "Retry button label (`'Try Again'` in English)" },
        { name: 'onError', type: '(error: Error, errorInfo: ErrorInfo) => void', optional: true, description: 'Callback when an error is caught' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'ErrorBoundary', propsType: 'ErrorBoundaryProps' },
  ],
}
