// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'eviction',
  propTypes: {
    'EvictionReportCardProps': {
      props: [
        { name: 'date', type: 'string', optional: false, description: 'The scheduled date, pre-formatted and prominent ("Tuesday, 23 September"). The app owns the locale.' },
        { name: 'time', type: 'string', optional: true, description: 'Pre-formatted ("09:00").' },
        { name: 'relativeLabel', type: 'string', optional: true, description: 'A relative line the app computes ("in 3 days", "Tomorrow", "2 weeks ago"). The card never reads the clock.' },
        { name: 'status', type: 'EvictionStatus', options: ['scheduled', 'postponed', 'suspended', 'executed', 'cancelled'], optional: false },
        { name: 'statusLabel', type: 'string', optional: true, description: 'Overrides the status word.' },
        { name: 'area', type: 'string', optional: false, description: 'A COARSE area — a neighbourhood and city ("Carabanchel, Madrid") or a street without a number. PRIVACY: never pass an exact address. How precise this is gets decided upstream, where the report is moderated; the card draws whatever it is given and has no field for a door number on purpose.' },
        { name: 'household', type: 'readonly string[]', optional: true, description: 'Short free strings drawn as chips ("Family with minors", "Elderly person").' },
        { name: 'description', type: 'string', optional: true, description: 'Clamped to `numberOfLines`.' },
        { name: 'numberOfLines', type: 'number', optional: true, description: 'Default `3`; `0` never clamps.' },
        { name: 'attendeesLabel', type: 'string', optional: true, description: 'Pre-formatted ("12 people will attend").' },
        { name: 'organisationsLabel', type: 'string', optional: true, description: 'Pre-formatted ("3 organisations supporting").' },
        { name: 'attending', type: 'boolean', optional: true, description: 'Whether the viewer said they will attend. Draws the toggle with `onAttendingChange`.' },
        { name: 'onAttendingChange', type: '(attending: boolean) => void', optional: true },
        { name: 'attendLabel', type: 'string', optional: true, description: 'Default `"I\'ll be there"`. Stays the toggle\'s name in both states; `aria-pressed` carries the state.' },
        { name: 'onShare', type: '() => void', optional: true },
        { name: 'shareLabel', type: 'string', optional: true, description: 'Default `"Share"`.' },
        { name: 'onContactSupport', type: '() => void', optional: true },
        { name: 'contactSupportLabel', type: 'string', optional: true, description: 'Default `"Contact support group"`.' },
        { name: 'verified', type: 'boolean', optional: true, description: 'Checked by the community (neighbours, a housing group) — NOT by an authority. The label says so; keep it that way when translating.' },
        { name: 'verifiedLabel', type: 'string', optional: true, description: 'Default `"Community verified"`.' },
        { name: 'headingLevel', type: 'number', optional: true, description: 'The heading level of the date on web. Default `3`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'EvictionTimelineProps': {
      props: [
        { name: 'events', type: 'readonly EvictionEvent[]', optional: false },
        { name: 'formatSource', type: '(source: string) => string', optional: true, description: 'Default `(source) => `Source: ${source}``.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the list. Default `"Case history"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'EvictionReportCard', propsType: 'EvictionReportCardProps' },
    { name: 'EvictionTimeline', propsType: 'EvictionTimelineProps' },
  ],
}
