// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'field',
  propTypes: {
    'FieldProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false, description: 'The input/control this field wraps.' },
        { name: 'label', type: 'React.ReactNode', optional: true, description: "Field label, rendered above the control via Bloom's `Label`." },
        { name: 'description', type: 'React.ReactNode', optional: true, description: 'Helper/description text rendered below the control.' },
        { name: 'error', type: 'string | null', optional: true, description: 'Error message. When a non-empty string is provided the field renders in its invalid state (error-colored message, replaces the description).' },
        { name: 'required', type: 'boolean', optional: true, description: "Mark the field's label with a required asterisk." },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Disables the label/description styling AND, for a control that reads the field context, the control itself.' },
        { name: 'multiple', type: 'boolean', optional: true, description: "The field holds SEVERAL controls — a radio set, a date's three boxes." },
        { name: 'nativeID', type: 'string', optional: true, description: "The control's id, wired to the label's `htmlFor` on web so a label click focuses it." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Field', propsType: 'FieldProps' },
  ],
}
