// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'fill',
  propTypes: {
    'Fill': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
      ],
    },
  },
  components: [
    { name: 'Fill', propsType: 'Fill' },
  ],
}
