// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'frosted-icon-button',
  propTypes: {
    'FrostedIconButtonProps': {
      props: [
        { name: 'onPress', type: '() => void', optional: true, description: 'Press handler.' },
        { name: 'icon', type: 'ButtonIconComponent', optional: true, description: 'Icon component; Bloom supplies its size and resolved foreground.' },
        { name: 'tone', type: 'BloomTone', options: ['neutral', 'accent', 'support', 'action', 'success', 'warning', 'danger', 'info'], optional: true },
        { name: 'checked', type: 'boolean', optional: true, description: 'Solid "on" state for toggles. When true the button drops its translucency and backdrop blur and fills with the brand `primary` token (icon tinted `primaryForeground`), so an enabled toggle reads unmistakably as active. Exposed to assistive tech as `aria-pressed` (web) / the selected a11y state.' },
        { name: 'onCheckedChange', type: '(checked: boolean) => void', optional: true },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'size', type: 'FrostedIconButtonSize | number', optional: true, description: "A preset (`'sm' | 'md'`) or a raw pixel diameter (`number`). Defaults to `'md'` (36px). See FrostedIconButtonSize." },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Required for icon-only buttons so screen readers announce the action.' },
        { name: 'accessibilityHint', type: 'string', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Container style override (merged last).' },
        { name: 'className', type: 'string', optional: true, description: 'NativeWind / DOM className passthrough.' },
        { name: 'testID', type: 'string', optional: true },
        { name: 'hitSlop', type: '{ top: number; bottom: number; left: number; right: number; }', optional: true, description: 'Native press hit target padding. Defaults to a generous slop so the compact circle is comfortable to tap. No-op on web.' },
        { name: 'onClick', type: '(event: React.MouseEvent<HTMLButtonElement>) => void', optional: true, description: 'Web click handler. Fires together with `onPress`.' },
        { name: 'aria-label', type: 'string', optional: true, description: '`aria-label` (web only). Falls back to `accessibilityLabel`.' },
        { name: 'title', type: 'string', optional: true, description: '`title` tooltip attribute (web only).' },
        { name: 'id', type: 'string', optional: true, description: 'Inline DOM `id` (web only).' },
        { name: 'type', type: "'button' | 'submit' | 'reset'", options: ['button', 'submit', 'reset'], optional: true, description: "HTML button `type` (web only). Defaults to `'button'`." },
      ],
    },
  },
  components: [
    { name: 'FrostedIconButton', propsType: 'FrostedIconButtonProps' },
  ],
}
