// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'hover-card',
  propTypes: {
    'HoverCardProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'openDelay', type: 'number', optional: true, description: 'Milliseconds the pointer (or keyboard focus) has to rest on the trigger before the card opens. Web only. Defaults to `400`.' },
        { name: 'closeDelay', type: 'number', optional: true, description: 'Milliseconds the card stays up after the pointer leaves the trigger or the card — long enough to cross the gap between them. Web only. Defaults to `150`.' },
        { name: 'open', type: 'boolean', optional: true, description: 'Controlled open state. Omit for an uncontrolled surface.' },
        { name: 'defaultOpen', type: 'boolean', optional: true, description: 'Initial open state when uncontrolled. Defaults to `false`.' },
        { name: 'onOpenChange', type: '(open: boolean) => void', optional: true, description: 'Called whenever the surface opens or closes, from any cause.' },
      ],
    },
    'HoverCardTriggerProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'asChild', type: 'boolean', optional: true, description: "NATIVE: merge the long-press into the single element child instead of wrapping it in Bloom's own `Pressable`. Use it whenever the child is itself pressable (a link, an avatar that opens a profile) — a wrapping `Pressable` never receives the long press, because the inner one wins the responder. WEB: ignored; the trigger listens for pointer and focus on a wrapper, so there is nothing to merge." },
        { name: 'disabled', type: 'boolean', optional: true, description: 'A disabled trigger never opens the card.' },
        { name: 'className', type: 'string', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'HoverCardContentProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'label', type: 'string', optional: true, description: "Accessible name of the card. Defaults to `'Hover card'`." },
        { name: 'padded', type: 'boolean', optional: true, description: "Draw Bloom's floating surface around the content (radius 16, 1px border, dropdown shadow, 15px inset). Defaults to `true`. A child that paints its own surface — `UserHoverCard` does, and detects this panel by itself — does not need `false`." },
        { name: 'className', type: 'string', optional: true, description: "Appended to the panel's own classes." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
        { name: 'side', type: 'FloatingSide', options: ['top', 'bottom', 'left', 'right'], optional: true, description: "Preferred side of the anchor. Defaults to `'bottom'`." },
        { name: 'align', type: 'FloatingAlign', options: ['start', 'center', 'end'], optional: true, description: 'Horizontal alignment against the anchor. Defaults per component.' },
        { name: 'sideOffset', type: 'number', optional: true, description: 'Gap between the anchor and the surface, on the `side` axis.' },
        { name: 'alignOffset', type: 'number', optional: true, description: 'Shift along the `align` axis, applied before the viewport clamp.' },
      ],
    },
  },
  components: [
    { name: 'HoverCard', propsType: 'HoverCardProps' },
    { name: 'HoverCardTrigger', propsType: 'HoverCardTriggerProps' },
    { name: 'HoverCardContent', propsType: 'HoverCardContentProps' },
  ],
}
