// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'icons',
  propTypes: {
    'AndroidLogo': {
      props: [
        { name: 'fill', type: 'import("react-native-svg").PathProps["fill"]', optional: true },
        { name: 'style', type: 'import("react-native").StyleProp<import("./shared").IconStyle>', optional: true },
        { name: 'size', type: 'keyof typeof import("./shared").sizes', options: ['sm', 'md', 'lg', '2xs', 'xs', 'xl', '2xl', '3xl'], optional: true },
        { name: 'gradient', type: 'keyof typeof import("../styles/tokens").gradients', options: ['primary', 'sky'], optional: true },
      ],
      inheritsFrom: ['Omit<SvgProps, "size" | "style">', 'RefAttributes<Svg>'],
    },
    'Full': {
      props: [
        { name: 'style', type: 'StyleProp<IconStyle>', optional: true },
        { name: 'gradient', type: 'keyof typeof gradients', options: ['primary', 'sky'], optional: true },
        { name: 'markFill', type: "Props['fill']", optional: true },
        { name: 'textFill', type: "Props['fill']", optional: true },
      ],
      inheritsFrom: ["Omit<Props, 'fill' | 'size' | 'height'> & { markFill?: Props['fill']; textFill?…"],
    },
  },
  components: [
    { name: 'AndroidLogo', propsType: 'AndroidLogo' },
    { name: 'AppleLogo', propsType: 'AndroidLogo' },
    { name: 'Bookmark', propsType: 'AndroidLogo' },
    { name: 'BookmarkFilled', propsType: 'AndroidLogo' },
    { name: 'BookmarkDeleteLarge', propsType: 'AndroidLogo' },
    { name: 'Full', propsType: 'Full' },
    { name: 'Mark', propsType: 'AndroidLogo' },
    { name: 'Newskie', propsType: 'AndroidLogo' },
    { name: 'Reply', propsType: 'AndroidLogo' },
    { name: 'ReplyFilled', propsType: 'AndroidLogo' },
    { name: 'StarterPack', propsType: 'AndroidLogo' },
    { name: 'VerifiedCheck', propsType: 'AndroidLogo' },
    { name: 'VerifierCheck', propsType: 'AndroidLogo' },
  ],
}
