// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'icon-circle',
  propTypes: {
    'IconCircle': {
      props: [
        { name: 'icon', type: 'React.ComponentType<IconProps>', optional: false },
        { name: 'size', type: 'IconProps["size"]', options: ['sm', 'md', 'lg', '2xs', 'xs', 'xl', '2xl', '3xl'], optional: true },
        { name: 'style', type: 'ViewStyle | ViewStyle[]', optional: true },
        { name: 'iconStyle', type: 'IconProps["style"]', optional: true },
      ],
    },
  },
  components: [
    { name: 'IconCircle', propsType: 'IconCircle' },
  ],
}
