// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'image-aspect-ratio-cache',
  propTypes: {
  },
  components: [
  ],
}
