// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'image-resolver',
  propTypes: {
    'ProviderProps<ImageResolver | null>': {
      props: [],
      inheritsFrom: ['ProviderProps<ImageResolver | null>'],
    },
  },
  components: [
    { name: 'ImageResolverProvider', propsType: 'ProviderProps<ImageResolver | null>' },
  ],
}
