// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'important-alerts-card',
  propTypes: {
    'ImportantAlertsCardProps': {
      props: [
        { name: 'alerts', type: 'readonly ImportantAlertsCardAlert[]', optional: false, description: 'The feed, newest first. It scrolls inside the card.' },
        { name: 'count', type: 'number | string', optional: false, description: 'The headline number — the total for the period, which can be higher than `alerts.length` when the feed lists only the most recent ones.' },
        { name: 'title', type: 'string', optional: true, description: 'Card title. Defaults to `"Important alerts"`.' },
        { name: 'countCaption', type: 'string', optional: true, description: 'Caption after the count. Defaults to `"this week"`.' },
        { name: 'rangeLabel', type: 'string', optional: true, description: 'Label of the range pill in the corner (`"29 Jun - 5 Jul"`). Omit to hide the pill.' },
        { name: 'height', type: 'number', optional: true, description: 'Card height. Defaults to `330`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'ImportantAlertsCard', propsType: 'ImportantAlertsCardProps' },
  ],
}
