// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'input-group',
  propTypes: {
    'InputGroupProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false, description: 'Group children. Place `InputGroupAddon` elements before/after the input (a Bloom `TextFieldInput`, a `Search`, or any control). The middle child stretches to fill.' },
        { name: 'isInvalid', type: 'boolean', optional: true, description: 'Invalid state — renders the error-colored border.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Disabled styling.' },
        { name: 'size', type: "'sm' | 'md' | 'lg'", options: ['sm', 'md', 'lg'], optional: true, description: "Size affects height + horizontal padding. Defaults to `'md'`." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'InputGroupAddonProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false, description: 'Addon content (icon, text, `Button`, `Kbd`, etc.).' },
        { name: 'divider', type: 'boolean', optional: true, description: "Visually separate the addon from the input with a hairline divider on the inner edge. Defaults to `false` (addons that are buttons usually want this `true`; plain text/icons usually don't)." },
        { name: 'noPadding', type: 'boolean', optional: true, description: 'Remove the default horizontal padding (useful when the addon is an interactive control that brings its own hit area / padding).' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'InputGroup', propsType: 'InputGroupProps' },
    { name: 'InputGroupAddon', propsType: 'InputGroupAddonProps' },
  ],
}
