// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'item',
  propTypes: {
    'ItemProps': {
      props: [
        { name: 'title', type: 'React.ReactNode', optional: true, description: 'Primary title text.' },
        { name: 'subtitle', type: 'React.ReactNode', optional: true, description: 'Secondary text rendered below the title.' },
        { name: 'children', type: 'React.ReactNode', optional: true, description: 'Arbitrary body content. When provided it replaces the `title`/`subtitle` text column — use it for fully custom rows.' },
        { name: 'leading', type: 'React.ReactNode', optional: true, description: 'Leading slot (icon, avatar, radio, etc.).' },
        { name: 'trailing', type: 'React.ReactNode', optional: true, description: 'Trailing slot (chevron, switch, badge, value text, etc.).' },
        { name: 'onPress', type: '() => void', optional: true, description: 'Makes the row pressable.' },
        { name: 'onLongPress', type: '() => void', optional: true, description: 'Long-press handler. Only honored when the row is pressable.' },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'destructive', type: 'boolean', optional: true, description: "Render the title in the theme's negative/error color." },
        { name: 'selected', type: 'boolean', optional: true, description: 'Selected state — applies a subtle highlighted background. Useful when `Item` is used as an option inside an overlay (combobox, command, menu).' },
        { name: 'active', type: 'boolean', optional: true, description: 'Highlighted (keyboard-focused) state for overlay lists.' },
        { name: 'density', type: "'comfortable' | 'compact'", options: ['comfortable', 'compact'], optional: true, description: "Vertical density. Defaults to `'comfortable'`." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'titleStyle', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'subtitleStyle', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'accessibilityHint', type: 'string', optional: true },
        { name: 'accessibilityRole', type: 'AccessibilityRole', options: ['none', 'button', 'togglebutton', 'link', 'search', 'image', 'keyboardkey', 'text', 'adjustable', 'imagebutton', 'header', 'summary', 'alert', 'checkbox', 'combobox', 'menu', 'menubar', 'menuitem', 'progressbar', 'radio', 'radiogroup', 'scrollbar', 'spinbutton', 'switch', 'tab', 'tabbar', 'tablist', 'timer', 'list', 'toolbar'], optional: true },
        { name: 'role', type: "'option' | 'radio' | 'checkbox' | 'menuitem' | 'listitem'", options: ['option', 'radio', 'checkbox', 'menuitem', 'listitem'], optional: true, description: "Web ARIA role override. Use `'option'` for combobox/listbox items (RN's `accessibilityRole` has no `'option'`), and `'radio'` / `'checkbox'` for a single- or multi-choice list. Each role scopes which state ARIA allows, and `Item` spells the matching one — see the `selectedAria` branch in `Item.tsx`." },
        { name: 'expanded', type: 'boolean', optional: true, description: 'Whether the row DISCLOSES something (a sub-menu, an accordion section). Emitted as `aria-expanded`, which React Native folds back into `accessibilityState` — so, unlike `accessibilityState.expanded` alone, it reaches web as well.' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Item', propsType: 'ItemProps' },
  ],
}
