// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'label',
  propTypes: {
    'LabelProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false, description: 'Label text.' },
        { name: 'nativeID', type: 'string', optional: true, description: 'Native ID of the control this label describes. On web, also wires up `htmlFor` so clicking the label focuses the associated input.' },
        { name: 'htmlFor', type: 'string', optional: true, description: 'Web-only convenience: the `id` of the form control this label is for. Defaults to `nativeID` when omitted. Ignored on native.' },
        { name: 'required', type: 'boolean', optional: true, description: "Render a required marker (an asterisk in the theme's negative color) after the label text. Defaults to `false`." },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Visually subdued label (e.g. for optional fields). Defaults to `false`.' },
        { name: 'size', type: "'xs' | 'sm' | 'md'", options: ['xs', 'sm', 'md'], optional: true, description: "Typography size token. Defaults to `'sm'`." },
        { name: 'style', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Label', propsType: 'LabelProps' },
  ],
}
