// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'link-preview',
  propTypes: {
    'LinkPreviewCardProps': {
      props: [
        { name: 'url', type: 'string', optional: false, description: 'The previewed URL. Opened via `Linking.openURL` when `onPress` is omitted.' },
        { name: 'title', type: 'string', optional: true, description: 'OpenGraph / page title. Falls back to the URL hostname when absent.' },
        { name: 'description', type: 'string', optional: true, description: 'OpenGraph / meta description.' },
        { name: 'image', type: 'string', optional: true, description: 'Absolute cover-image URL (e.g. a `cloud.oxy.so` OG image). Rendered directly with the RN `Image` primitive — NOT through `ImageResolver` / `Avatar`, which are for bare Oxy file IDs.' },
        { name: 'siteName', type: 'string', optional: true, description: 'Site / brand name shown above the title. Falls back to the URL hostname.' },
        { name: 'coverFill', type: 'boolean', optional: true, description: 'Fill-height mode for the cover image. Defaults to `false`.' },
        { name: 'onPress', type: '() => void', optional: true, description: 'Press handler. When omitted, the card opens `url` via `Linking.openURL`.' },
        { name: 'className', type: 'string', optional: true, description: 'Extra NativeWind utilities merged onto the card surface.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Extra style merged onto the card surface.' },
      ],
    },
  },
  components: [
    { name: 'LinkPreviewCard', propsType: 'LinkPreviewCardProps' },
  ],
}
