// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'list',
  propTypes: {
    'VirtualList': {
      props: [
        { name: 'data', type: 'readonly T[] | null', optional: true, description: 'Row data.' },
        { name: 'renderItem', type: 'VirtualListRenderItem<T>', optional: true, description: 'Renders one row.' },
        { name: 'keyExtractor', type: '(item: T, index: number) => string', optional: true, description: 'Stable key for a row; strongly recommended for correct virtualization.' },
        { name: 'ListHeaderComponent', type: 'VirtualListSlot', optional: true, description: 'Rendered above the rows; scrolls away with the content.' },
        { name: 'ListEmptyComponent', type: 'VirtualListSlot', optional: true, description: 'Rendered (in place of rows) when `data` is empty.' },
        { name: 'ListFooterComponent', type: 'VirtualListSlot', optional: true, description: 'Rendered below the rows.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Style for the outer list container.' },
        { name: 'contentContainerStyle', type: 'StyleProp<ViewStyle>', optional: true, description: 'Style for the inner content wrapper (e.g. padding).' },
        { name: 'estimatedItemSize', type: 'number', optional: true, description: 'First-paint row-height estimate (px) used before a row is measured. On web each row is measured after mount and this is only the initial guess.' },
        { name: 'overscan', type: 'number', optional: true, description: 'Web: extra rows mounted beyond the viewport (virtualization overscan).' },
        { name: 'onEndReached', type: '() => void', optional: true, description: 'Called when the end of the list is approached (native pagination).' },
        { name: 'onEndReachedThreshold', type: 'number', optional: true, description: 'Native: viewport-relative distance from the end that fires `onEndReached`.' },
        { name: 'refreshing', type: 'boolean', optional: true, description: 'Pull-to-refresh active flag (native).' },
        { name: 'onRefresh', type: '() => void', optional: true, description: 'Pull-to-refresh handler (native).' },
        { name: 'testID', type: 'string', optional: true, description: 'Test id applied to the outer container.' },
        { name: 'removeClippedSubviews', type: 'boolean', optional: true },
        { name: 'maxToRenderPerBatch', type: 'number', optional: true },
        { name: 'windowSize', type: 'number', optional: true },
        { name: 'initialNumToRender', type: 'number', optional: true },
        { name: 'recycleItems', type: 'boolean', optional: true },
        { name: 'maintainVisibleContentPosition', type: 'boolean', optional: true },
        { name: 'ref', type: 'React.Ref<VirtualListHandle>', optional: true },
      ],
    },
  },
  components: [
    { name: 'VirtualList', propsType: 'VirtualList' },
  ],
}
