// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'listing-editor',
  propTypes: {
    'AddressPrecisionPickerProps': {
      props: [
        { name: 'value', type: 'AddressPrecision', options: ['exact', 'street', 'approximate'], optional: false },
        { name: 'onValueChange', type: '(value: AddressPrecision) => void', optional: false },
        { name: 'renderMap', type: '(precision: AddressPrecision) => ReactNode', optional: true, description: "Draws a card's map preview. Default: Bloom's placeholder — a street grid with a pin (exact), a highlighted street (street) or a circle (approximate). Return a real static map here." },
        { name: 'options', type: 'ReadonlyArray<AddressPrecisionOption>', optional: true, description: "The three cards' copy, in order. Default Bloom's copy, in the locale." },
        { name: 'footnote', type: 'string | null', optional: true, description: 'The line under the cards. Default explains that the choice decides the published location. `null` hides it.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the radiogroup. `"Address precision"` in English.' },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'PrecisionMapPlaceholder': {
      props: [
        { name: 'precision', type: 'AddressPrecision', options: ['exact', 'street', 'approximate'], optional: false },
        { name: 'height', type: 'number', optional: false },
      ],
    },
    'ListingPreviewPaneProps': {
      props: [
        { name: 'listing', type: 'ListingPreviewData', optional: false },
        { name: 'mode', type: 'ListingPreviewMode', options: ['card', 'page'], optional: true, description: 'Controlled mode.' },
        { name: 'defaultMode', type: 'ListingPreviewMode', options: ['card', 'page'], optional: true, description: 'Uncontrolled starting mode. Default `card`.' },
        { name: 'onModeChange', type: '(mode: ListingPreviewMode) => void', optional: true },
        { name: 'renderPage', type: '(listing: ListingPreviewData) => ReactNode', optional: true, description: 'Replaces the built-in page preview.' },
        { name: 'title', type: 'string', optional: true, description: '`"Preview"` in English.' },
        { name: 'description', type: 'string', optional: true, description: 'The line under the title. `"This is how guests will see your listing."` in English.' },
        { name: 'cardLabel', type: 'string', optional: true, description: 'The toggle\'s words. `"Card"` / `"Page"` in English.' },
        { name: 'pageLabel', type: 'string', optional: true },
        { name: 'toggleLabel', type: 'string', optional: true, description: 'Names the toggle. `"Preview as"` in English.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'ListingQualityMeterProps': {
      props: [
        { name: 'items', type: 'ReadonlyArray<ListingQualityItem>', optional: false },
        { name: 'score', type: 'number', optional: true, description: "0..100. Default: the done items' share of the total weight." },
        { name: 'title', type: 'string', optional: true, description: '`"Listing quality"` in English.' },
        { name: 'summary', type: 'string', optional: true, description: 'The line under the title. By score, in English: under 50 `"Needs work"`, under 80 `"Good"`, else `"Excellent"`.' },
        { name: 'tips', type: 'ReadonlyArray<string>', optional: true, description: 'Short advice drawn in a tips box under the checklist.' },
        { name: 'tipsTitle', type: 'string', optional: true, description: '`"Tips"` in English.' },
        { name: 'formatScore', type: '(score: number) => string', optional: true, description: "The ring's centre text. Default `` score => `${score}` ``." },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the ring. `"Listing quality score"` in English.' },
        { name: 'doneLabel', type: 'string', optional: true, description: 'The done/not-done words added to each row\'s name. `"Done"` / `"To do"` in English.' },
        { name: 'todoLabel', type: 'string', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'OfferingEditorProps': {
      props: [
        { name: 'value', type: 'OfferingValue', optional: false },
        { name: 'onValueChange', type: '(value: OfferingValue) => void', optional: false },
        { name: 'kinds', type: 'ReadonlyArray<OfferingKind>', optional: true, description: 'The kinds to offer, in order. Default all four.' },
        { name: 'currencySymbol', type: 'string', optional: true, description: 'Drawn before every money field ("€"). Default `"€"`.' },
        { name: 'area', type: 'number', optional: true, description: "The home's floor area. With a sale price it gives the read-only price per area — the one number this component computes." },
        { name: 'areaUnit', type: 'string', optional: true, description: 'The unit `area` is in. Default `"m²"`.' },
        { name: 'formatPricePerArea', type: '(value: number) => string', optional: true, description: 'Formats the computed price per area. Default: rounded, thousands spaced, `currencySymbol` first.' },
        { name: 'depositOptions', type: 'ReadonlyArray<number>', optional: true, description: 'The deposit chips, in months. Default `[0, 1, 2, 3]`.' },
        { name: 'errors', type: 'OfferingErrors', optional: true, description: 'Messages under fields; `kinds` sits under the cards.' },
        { name: 'labels', type: 'Partial<OfferingEditorLabels>', optional: true },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'PropertyTypeSelectorProps<T>': {
      props: [
        { name: 'value', type: 'T | null', optional: false },
        { name: 'onValueChange', type: '(value: T) => void', optional: false },
        { name: 'options', type: 'ReadonlyArray<PropertyTypeOption<T>>', optional: true, description: "The tiles. Default Bloom's nine property types, labelled in the locale." },
        { name: 'columns', type: 'number', optional: true, description: 'A fixed column count. Default: 2 below 400 wide, 3 below 640, 4 from there.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the radiogroup. `"Property type"` in English.' },
        { name: 'error', type: 'string', optional: true, description: 'A message under the tiles, painted as an error.' },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'AddressPrecisionPicker', propsType: 'AddressPrecisionPickerProps' },
    { name: 'PrecisionMapPlaceholder', propsType: 'PrecisionMapPlaceholder' },
    { name: 'ListingPreviewPane', propsType: 'ListingPreviewPaneProps' },
    { name: 'ListingQualityMeter', propsType: 'ListingQualityMeterProps' },
    { name: 'OfferingEditor', propsType: 'OfferingEditorProps' },
    { name: 'PropertyTypeSelector', propsType: 'PropertyTypeSelectorProps<T>' },
  ],
}
