// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'location-puck',
  propTypes: {
    'LocationPuckProps': {
      props: [
        { name: 'state', type: 'LocationPuckState', options: ['locating', 'located', 'stale'], optional: true, description: 'Default `located`.' },
        { name: 'mode', type: 'LocationPuckMode', options: ['following', 'compass', 'navigating'], optional: true, description: 'Default `following`.' },
        { name: 'heading', type: 'number', optional: true, description: 'Which way you are facing, in degrees clockwise from north. Turns the cone in `following`, and the chevron in `navigating`; ignored in `compass`, where the map itself is what turned.' },
        { name: 'headingAccuracy', type: 'number', optional: true, description: "The platform's own ± uncertainty for heading, in DEGREES, and the cone's half-width: the wedge is the uncertainty, drawn. Clamped into `[coneMinHalfAngle, coneMaxHalfAngle]`, and defaulted to the minimum when the platform reports nothing." },
        { name: 'headingUnknown', type: 'boolean', optional: true, description: 'No heading at all — draws NO cone. A guessed cone is worse than none: it is a confident claim about the one thing the device could not measure.' },
        { name: 'accuracyRadius', type: 'number', optional: true, description: "The accuracy halo's radius in PIXELS. The app computes it from its own map projection (metres at this latitude and zoom → pixels) and re-renders on zoom, exactly as it does for `MapAreaCircle` — which is the circle this draws." },
        { name: 'coneLength', type: 'number', optional: true, description: 'How far the cone reaches, in pixels. Default LOCATION_PUCK_GEOMETRY `.cone`.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: "The puck's announced name. Defaults to the sentence describeLocationPuck builds from the state, the mode and the heading — a coloured dot says nothing aloud." },
        { name: 'stateLabels', type: 'Partial<Record<LocationPuckState, string>>', optional: true, description: 'Replaces the English state words.' },
        { name: 'reducedMotion', type: 'boolean', optional: true, description: "Force the pulse off regardless of the OS preference. Omitted, the puck reads the platform's reduced-motion setting and stands still when it is on." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Parts get `<testID>-halo`, `-cone`, `-dot`, `-chevron`.' },
      ],
    },
  },
  components: [
    { name: 'LocationPuck', propsType: 'LocationPuckProps' },
  ],
}
