// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'lyrics',
  propTypes: {
    'LyricsViewProps': {
      props: [
        { name: 'lines', type: 'readonly LyricLine[]', optional: true, description: 'The lines, in any order — synced lines are sorted by `time`.' },
        { name: 'text', type: 'string', optional: true, description: 'Plain, unsynced lyrics as one string (split on line breaks). Used when `lines` is absent or empty.' },
        { name: 'currentTime', type: 'number', optional: true, description: 'The playback position, in seconds. Drives the active line.' },
        { name: 'onSeekLine', type: '(line: LyricLine, index: number) => void', optional: true, description: 'Called when a synced line is pressed, with the line and its index in the sorted lines. Seek the player to `line.time`. Without it lines are not pressable.' },
        { name: 'artworkColor', type: 'string | null', optional: true, description: "The artwork's colour (hex or `rgb()`), from the backend. The view paints a deep shade of it and picks text colours that keep contrast. Absent or unparseable: the theme's neutral surface." },
        { name: 'providerText', type: 'string', optional: true, description: 'The footer line, e.g. "Lyrics provided by …". Omitted: no footer.' },
        { name: 'footer', type: 'ReactNode', optional: true, description: 'Replaces the footer with your own node.' },
        { name: 'emptyText', type: 'string', optional: true, description: 'Drawn when there are no lyrics at all. Default "Lyrics aren’t available for this track".' },
        { name: 'backToCurrentLabel', type: 'string', optional: true, description: 'The pill shown after the user scrolls away. Default "Back to current line".' },
        { name: 'resumeDelay', type: 'number', optional: true, description: "How long after the user's last scroll auto-scroll resumes, in ms. Default `3000`." },
        { name: 'anchor', type: 'number', optional: true, description: "Where the active line's centre is kept, as a fraction of the height. Default `1/3`." },
        { name: 'size', type: 'LyricsSize', options: ['large', 'medium', 'small'], optional: true, description: 'Text size. Default by width: `large` from 720, `medium` from 480, `small` below.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'The region\'s name. Default `"Lyrics"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'LyricsPreviewCardProps': {
      props: [
        { name: 'lines', type: 'readonly LyricLine[]', optional: true },
        { name: 'text', type: 'string', optional: true, description: 'Plain, unsynced lyrics — the card shows the first lines.' },
        { name: 'currentTime', type: 'number', optional: true },
        { name: 'artworkColor', type: 'string | null', optional: true },
        { name: 'title', type: 'string', optional: true, description: 'The card\'s heading. Default `"Lyrics"`.' },
        { name: 'visibleLines', type: '4 | 5', optional: true, description: 'How many lines the card shows. Default `5`.' },
        { name: 'onShowLyrics', type: '() => void', optional: true, description: 'Called by the "Show lyrics" button. Without it the button is not drawn.' },
        { name: 'showLyricsLabel', type: 'string', optional: true, description: 'Default `"Show lyrics"`.' },
        { name: 'onSeekLine', type: '(line: LyricLine, index: number) => void', optional: true, description: 'Makes the lines pressable, as in LyricsViewProps.onSeekLine.' },
        { name: 'providerText', type: 'string', optional: true, description: 'A small footer, e.g. "Lyrics provided by …".' },
        { name: 'emptyText', type: 'string', optional: true, description: 'Drawn when there are no lyrics. Default "Lyrics aren’t available for this track".' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'LyricsView', propsType: 'LyricsViewProps' },
    { name: 'LyricsPreviewCard', propsType: 'LyricsPreviewCardProps' },
  ],
}
