// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'map-controls',
  propTypes: {
    'MapControlsProps': {
      props: [
        { name: 'onLocate', type: '() => void', optional: true, description: 'Draws the locate button.' },
        { name: 'following', type: 'boolean', optional: true, description: 'Whether the map is following the reader. It is a TOGGLE — `aria-pressed` on web and the selected state on native — so leave it `undefined` for a locate button that only recentres once.' },
        { name: 'heading', type: 'number', optional: true, description: 'Draws the compass. Degrees clockwise from north.' },
        { name: 'onResetNorth', type: '() => void', optional: true, description: 'Pressing the compass. Without it the compass is not drawn.' },
        { name: 'hideCompassAtNorth', type: 'boolean', optional: true, description: 'Passed to `MapCompass`. Default `true`.' },
        { name: 'onZoomIn', type: '() => void', optional: true, description: 'Draws the zoom pair. Both are needed: one zoom button is not a pair.' },
        { name: 'onZoomOut', type: '() => void', optional: true },
        { name: 'canZoomIn', type: 'boolean', optional: true, description: "Disables the matching zoom button at the end of the map's range." },
        { name: 'canZoomOut', type: 'boolean', optional: true },
        { name: 'onTiltChange', type: '(tilted: boolean) => void', optional: true, description: 'Draws the tilt toggle.' },
        { name: 'tilted', type: 'boolean', optional: true, description: 'Whether the map is tilted.' },
        { name: 'children', type: 'ReactNode', optional: true, description: 'Islands appended to the stack — a `MapLayerPicker`, or one of your own. They are placed, not wrapped: the stack owns the column and the gap, and nothing else.' },
        { name: 'align', type: 'MapControlsAlign', options: ['start', 'end'], optional: true, description: 'Which edge the stack hugs. Default `end`.' },
        { name: 'labels', type: 'MapControlsLabels', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Parts get `<testID>-locate`, `-compass`, `-zoom`, `-zoom-in`, `-zoom-out`, `-tilt`.' },
      ],
    },
    'MapCompassProps': {
      props: [
        { name: 'heading', type: 'number', optional: false, description: 'Degrees CLOCKWISE from north the map has been rotated. The needle turns the other way, so it keeps pointing at north.' },
        { name: 'onPress', type: '() => void', optional: true, description: 'Pressing it puts the map back at north.' },
        { name: 'hideAtNorth', type: 'boolean', optional: true, description: 'Hide the compass while the map is already within MAP_CONTROLS_GEOMETRY `.northTolerance` of north. Default `true` — a control that does nothing is a control a reader has to rule out.' },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'The announced name. Default `` `Facing ${Math.round(heading)} degrees. Reset to north` `` — pass a translated sentence, since a needle announces nothing at all.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'MapLayerPickerProps': {
      props: [
        { name: 'layers', type: 'readonly MapLayerOption[]', optional: false, description: 'The map types.' },
        { name: 'layerId', type: 'string', optional: true, description: "The chosen type's id." },
        { name: 'onLayerChange', type: '(id: string) => void', optional: true },
        { name: 'overlays', type: 'readonly MapOverlayOption[]', optional: true, description: 'The overlays. Omitted, the menu is types only.' },
        { name: 'activeOverlayIds', type: 'readonly string[]', optional: true, description: 'Which overlays are on.' },
        { name: 'onOverlayChange', type: '(id: string, active: boolean) => void', optional: true },
        { name: 'icon', type: 'BloomIconComponent', optional: true, description: "The trigger's glyph. Default a stack." },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'open', type: 'boolean', optional: true },
        { name: 'defaultOpen', type: 'boolean', optional: true },
        { name: 'onOpenChange', type: '(open: boolean) => void', optional: true },
        { name: 'labels', type: 'MapLayerPickerLabels', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Parts get `<testID>-trigger`, `-content`, `-layer-<id>`, `-overlay-<id>`.' },
      ],
    },
  },
  components: [
    { name: 'MapControls', propsType: 'MapControlsProps' },
    { name: 'MapCompass', propsType: 'MapCompassProps' },
    { name: 'MapLayerPicker', propsType: 'MapLayerPickerProps' },
  ],
}
