// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'map-attribution',
  propTypes: {
    'MapAttributionProps': {
      props: [
        { name: 'credit', type: 'string', optional: false, description: "The credit the data's licence requires, as the licence words it. NOT optional and NOT defaulted: a component that invented a default credit would put a wrong attribution on a map, which is the one failure in this family that is a legal problem rather than a visual one." },
        { name: 'onPressCredit', type: '() => void', optional: true, description: "Opens the provider's own attribution page. With it the credit becomes a link; without it, plain text." },
        { name: 'creditLabel', type: 'string', optional: true, description: "The link's announced name. Defaults to `credit`." },
        { name: 'scales', type: 'readonly MapScale[]', optional: true, description: 'The scale bar, drawn before the credit. Without it none is drawn.' },
        { name: 'scaleLabel', type: 'string', optional: true, description: 'The word before the readings in the scale\'s announcement. Default `"Scale"`.' },
        { name: 'updated', type: 'string', optional: true, description: 'When the tiles were last refreshed, pre-formatted by the app — "Updated 12 March", "Updated 3 days ago". Never computed here: this component does not read a clock.' },
        { name: 'variant', type: 'MapAttributionVariant', options: ['island', 'inline'], optional: true, description: 'Default `island`.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the strip. Default `"Map data"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Parts get `<testID>-scale`, `-credit`, `-updated`.' },
      ],
    },
    'MapScaleBarProps': {
      props: [
        { name: 'scales', type: 'readonly MapScale[]', optional: false, description: 'One bar, or two — a metric bar and an imperial one, in that order. Two is the case this takes a list for: they are the same measurement in two vocabularies and must line up under each other rather than appear as two separate instruments.' },
        { name: 'variant', type: 'MapAttributionVariant', options: ['island', 'inline'], optional: true, description: 'Default `island`.' },
        { name: 'scaleLabel', type: 'string', optional: true, description: 'The word before the readings in the announcement. Default `"Scale"`.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Defaults to `"Scale, 500 m, 1000 ft"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Parts get `<testID>-bar-<n>`, `<testID>-rule-<n>`.' },
      ],
    },
  },
  components: [
    { name: 'MapAttribution', propsType: 'MapAttributionProps' },
    { name: 'MapScaleBar', propsType: 'MapScaleBarProps' },
  ],
}
