// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'map-marker',
  propTypes: {
    'MapAreaCircleProps': {
      props: [
        { name: 'radius', type: 'number', optional: false, description: "The circle's radius in PIXELS. The app computes it from its map projection (metres at this latitude and zoom → pixels) and re-renders on zoom." },
        { name: 'label', type: 'string', optional: true, description: 'A small pill at the centre ("Approximate area", "~500 m").' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'The circle\'s name, which makes it an image to assistive technology ("Approximate location, within 500 metres"). Without it the circle is decorative and only its `label` is read.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Parts get `<testID>-fill`, `-label`.' },
      ],
    },
    'MapClusterMarkerProps': {
      props: [
        { name: 'count', type: 'number | string', optional: false, description: 'How many listings the bubble stands for; a string is drawn as given ("99+").' },
        { name: 'state', type: 'MapMarkerState', options: ['default', 'active', 'visited'], optional: true, description: '`visited` draws as `default`. Default `default`.' },
        { name: 'onPress', type: '() => void', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Defaults to `"<count> stays"` — pass a translated sentence.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'MapListingPreviewProps': {
      props: [
        { name: 'image', type: 'string', optional: true, description: "The photo: a URL, or an id the app's `ImageResolver` turns into one." },
        { name: 'imageVariant', type: 'string', optional: true, description: 'The variant handed to the `ImageResolver` with an id.' },
        { name: 'title', type: 'string', optional: false },
        { name: 'rating', type: 'number | string | null', optional: true, description: 'Handed to `Rating` (`null` draws "New"); omit to hide the rating.' },
        { name: 'reviewCount', type: 'number | string', optional: true },
        { name: 'subtitle', type: 'string', optional: true, description: 'The secondary line ("Entire cabin · 2 beds").' },
        { name: 'price', type: 'string', optional: true, description: 'Pre-formatted ("€120"). Optional when `priceLines` is given.' },
        { name: 'priceDetail', type: 'string', optional: true, description: 'Drawn after the price in secondary text ("night", "total").' },
        { name: 'originalPrice', type: 'string', optional: true, description: 'A struck-through earlier price before `price` ("€150").' },
        { name: 'priceLines', type: 'ReadonlyArray<ListingPriceLine>', optional: true, description: 'Stacked price lines, as on `ListingCard` ("€950 / month"; "€240,000 · €3,200/m²"). Replaces `price`, `priceDetail` and `originalPrice`.' },
        { name: 'facts', type: 'ReadonlyArray<ListingFact>', optional: true, description: 'The facts row, as on `ListingCard` (bed 3 · bath 2 · 110 m²).' },
        { name: 'offerings', type: 'ReadonlyArray<Offering>', optional: true, description: 'Offering badges, a small tinted row above the title.' },
        { name: 'offeringLabels', type: 'Partial<Record<Offering, string>>', optional: true, description: 'Replaces the English offering labels.' },
        { name: 'favorite', type: 'boolean', optional: true, description: 'Whether the listing is saved. The heart shows only with `onFavoriteChange`.' },
        { name: 'onFavoriteChange', type: '(favorite: boolean) => void', optional: true },
        { name: 'onClose', type: '() => void', optional: true, description: 'The close button shows only with this.' },
        { name: 'onPress', type: '() => void', optional: true, description: 'Opens the listing — the whole card is the target.' },
        { name: 'layout', type: 'MapListingPreviewLayout', options: ['vertical', 'compact'], optional: true, description: 'Default `vertical`.' },
        { name: 'width', type: 'number', optional: true, description: 'Default `327`.' },
        { name: 'closeLabel', type: 'string', optional: true, description: 'Default `"Close"`.' },
        { name: 'favoriteLabel', type: 'string', optional: true, description: 'The heart\'s name; its pressed state says whether it is saved. Default `"Save"`.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: "The card target's name. Defaults to `title`." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Parts get `<testID>-open`, `-close`, `-favorite`, `-image`.' },
      ],
    },
    'MapPriceMarkerProps': {
      props: [
        { name: 'price', type: 'string', optional: false, description: 'The price as drawn, pre-formatted and SHORT — the app abbreviates it ("€120", "€950/mo", "€240K", "€1.2M"); the pill never truncates.' },
        { name: 'state', type: 'MapMarkerState', options: ['default', 'active', 'visited'], optional: true, description: 'Default `default`.' },
        { name: 'size', type: 'MapPriceMarkerSize', options: ['default', 'compact'], optional: true, description: 'Default `default`.' },
        { name: 'saved', type: 'boolean', optional: true, description: 'Draws a small heart before the price.' },
        { name: 'onPress', type: '() => void', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'The marker\'s accessible name — a sentence, since the pill only shows a number ("€120 per night, Lisbon"). Defaults to `price`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'MapSearchAreaButtonProps': {
      props: [
        { name: 'variant', type: "'toggle'", options: ['button', 'toggle'], optional: true, description: 'A checkbox pill, "Search as I move the map". A button pill, "Search this area". Default.' },
        { name: 'label', type: 'string', optional: true, description: "Defaults to the variant's own sentence." },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'MapAreaCircle', propsType: 'MapAreaCircleProps' },
    { name: 'MapClusterMarker', propsType: 'MapClusterMarkerProps' },
    { name: 'MapListingPreview', propsType: 'MapListingPreviewProps' },
    { name: 'MapPriceMarker', propsType: 'MapPriceMarkerProps' },
    { name: 'MapSearchAreaButton', propsType: 'MapSearchAreaButtonProps' },
  ],
}
