// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'media-controls',
  propTypes: {
    'PlayButtonProps': {
      props: [
        { name: 'interactive', type: 'boolean', optional: true, description: '`false` draws the disc without making it a control: no `role="button"`, no focus stop, hidden from assistive tech unless `accessibilityLabel` names it. For a play glyph that sits INSIDE a pressable poster frame or row — a button inside a button is invalid HTML and a second stop for one action.' },
        { name: 'playing', type: 'boolean', optional: false, description: 'Whether the media is playing: draws the pause glyph and is named "Pause".' },
        { name: 'onPress', type: '() => void', optional: true, description: 'Called on press. The button does not toggle anything itself.' },
        { name: 'size', type: 'PlayButtonSize', options: ['small', 'medium', 'large'], optional: true, description: 'Default `medium`.' },
        { name: 'variant', type: 'PlayButtonVariant', options: ['accent', 'inverse', 'plain'], optional: true, description: 'Default `accent`.' },
        { name: 'loading', type: 'boolean', optional: true, description: 'Replaces the glyph with a spinning ring and sets `aria-busy`. Still pressable.' },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'subject', type: 'string', optional: true, description: 'What plays, appended to the name: `"Night Drive"` → "Play Night Drive".' },
        { name: 'playLabel', type: 'string', optional: true, description: 'Name while paused. Default `"Play"`.' },
        { name: 'pauseLabel', type: 'string', optional: true, description: 'Name while playing. Default `"Pause"`.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Replaces the composed name entirely.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'LikeButtonProps': {
      props: [
        { name: 'liked', type: 'boolean', optional: false },
        { name: 'onLikedChange', type: '(liked: boolean) => void', optional: false, description: 'Called with the next state.' },
        { name: 'size', type: 'LikeButtonSize', options: ['small', 'medium', 'large'], optional: true, description: 'Default `medium`.' },
        { name: 'activeColor', type: 'string', optional: true, description: "The liked heart's colour. Default: the theme accent." },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'The toggle\'s name. Default `"Save to Your Library"`. It stays the same in both states — `aria-pressed` carries the state; a name that also flipped would be announced as "Remove from Your Library, pressed".' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'ExplicitBadgeProps': {
      props: [
        { name: 'size', type: 'ExplicitBadgeSize', options: ['small', 'medium'], optional: true, description: 'Default `medium`.' },
        { name: 'letter', type: 'string', optional: true, description: 'The drawn letter. Default `"E"`.' },
        { name: 'label', type: 'string', optional: true, description: 'The accessible name. Default `"Explicit"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'NowPlayingIndicatorProps': {
      props: [
        { name: 'playing', type: 'boolean', optional: true, description: 'Animates the bars. `false` draws them still. Default `true`.' },
        { name: 'size', type: 'number', optional: true, description: 'Width and height of the square it draws in. Default `16`.' },
        { name: 'bars', type: '3 | 4', optional: true, description: 'Number of bars. Default `4`.' },
        { name: 'color', type: 'string', optional: true, description: 'Bar colour. Default: the theme accent.' },
        { name: 'label', type: 'string', optional: true, description: 'The accessible name. Default `"Now playing"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'PlaybackProgressProps': {
      props: [
        { name: 'value', type: 'number', optional: false, description: 'Position, in seconds.' },
        { name: 'duration', type: 'number', optional: false, description: 'Length, in seconds.' },
        { name: 'buffered', type: 'number', optional: true, description: 'How far the media has loaded, in seconds.' },
        { name: 'onSeek', type: '(seconds: number) => void', optional: true, description: 'Called once, with the position in seconds, when a drag is released or a key is pressed.' },
        { name: 'onSeekPreview', type: '(seconds: number) => void', optional: true, description: 'Called while dragging, with the position under the pointer.' },
        { name: 'showTimes', type: 'boolean', optional: true, description: 'Draws the elapsed and total (or remaining) time. Default `false`.' },
        { name: 'showRemaining', type: 'boolean', optional: true, description: 'The right-hand label counts down ("−2:22") instead of showing the length.' },
        { name: 'timesPosition', type: 'PlaybackProgressTimes', options: ['inline', 'below'], optional: true, description: 'Default `inline`.' },
        { name: 'keyboardStep', type: 'number', optional: true, description: 'Seconds one arrow key moves. Default `5`.' },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'The slider\'s name. Default `"Seek"`.' },
        { name: 'formatValueText', type: '(seconds: number, duration: number) => string', optional: true, description: 'The announced value. Default: "1:23 of 3:45".' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'VolumeControlProps': {
      props: [
        { name: 'volume', type: 'number', optional: false, description: 'Level, `0`..`1`.' },
        { name: 'onVolumeChange', type: '(volume: number) => void', optional: false, description: 'Called while dragging and on each key press, with a level in `0`..`1`.' },
        { name: 'muted', type: 'boolean', optional: true, description: 'Whether sound is muted. The slider draws 0 while muted.' },
        { name: 'onMutedChange', type: '(muted: boolean) => void', optional: true, description: 'Called by the speaker button, and with `false` when the slider is moved while muted.' },
        { name: 'sliderWidth', type: 'number', optional: true, description: 'Width of the slider. Default `96`.' },
        { name: 'sliderVisibility', type: 'VolumeSliderVisibility', options: ['always', 'hover'], optional: true, description: 'Default `always`.' },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'muteLabel', type: 'string', optional: true, description: 'Button name while sounding. Default `"Mute"`.' },
        { name: 'unmuteLabel', type: 'string', optional: true, description: 'Button name while muted. Default `"Unmute"`.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'The slider\'s name. Default `"Volume"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'PlayButton', propsType: 'PlayButtonProps' },
    { name: 'LikeButton', propsType: 'LikeButtonProps' },
    { name: 'ExplicitBadge', propsType: 'ExplicitBadgeProps' },
    { name: 'NowPlayingIndicator', propsType: 'NowPlayingIndicatorProps' },
    { name: 'PlaybackProgress', propsType: 'PlaybackProgressProps' },
    { name: 'VolumeControl', propsType: 'VolumeControlProps' },
  ],
}
