// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'media-flight',
  propTypes: {
    'MediaFlightHostProps<P>': {
      props: [
        { name: 'id', type: 'string', optional: false, description: 'The id this host shares with the flight and with the other end.' },
        { name: 'content', type: 'MediaSurfaceImage | MediaSurfaceVideoOf<P>', optional: false, description: 'What to paint: a still image, or a consumer-owned expo-video player.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: "Style of the host BOX. Give it the radius and `overflow: 'hidden'` you want." },
        { name: 'contentFit', type: "'contain' | 'cover'", options: ['contain', 'cover'], optional: true, description: "How the media fills the box. Defaults to `'cover'`." },
        { name: 'renderVideo', type: 'MediaVideoSlot<P>', optional: true, description: 'Paint the video yourself, keeping your own `ref` and expo-video props. See MediaVideoSlot; memoise it.' },
        { name: 'nativeControls', type: 'boolean', optional: true, description: "Whether the video arm shows expo-video's own controls. Defaults to `false`." },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'surfaceType', type: 'VideoSurfaceType', options: ['textureView', 'surfaceView'], optional: true, description: "Android's rendering surface for the video arm. See `MediaSurfaceProps`. Ignored on web, where there is no such choice." },
        { name: 'pointerEvents', type: "'auto' | 'none' | 'box-none' | 'box-only'", options: ['auto', 'none', 'box-none', 'box-only'], optional: true, description: 'Passed through as a PROP, never as a style key — react-native-web resolves `box-none`/`box-only` from the prop path only.' },
        { name: 'flightId', type: 'string', optional: true, description: 'Set on a DESTINATION host, to the id its flight was started with, when the destination paints its media ITSELF rather than through the shared node — which on native is always. The web host does not need it: a flight there ends when the destination host claims the node, because by then the node it is claiming has been showing the media all along.' },
      ],
    },
    'MediaSurfaceProps': {
      props: [
        { name: 'content', type: 'MediaSurfaceContent', optional: false, description: 'What to paint: a still image, or a consumer-owned expo-video player.' },
        { name: 'style', type: 'MediaSurfaceStyle', optional: true, description: 'Size, radius and transform of the box. May carry an animated style.' },
        { name: 'contentFit', type: "'contain' | 'cover'", options: ['contain', 'cover'], optional: true, description: "How the media fills the box. Defaults to `'contain'`." },
        { name: 'surfaceType', type: 'VideoSurfaceType', options: ['textureView', 'surfaceView'], optional: true, description: "Android's rendering surface for the video arm. Defaults to `'textureView'` and is CAPTURED ON FIRST RENDER: expo-video documents that this prop must not change at runtime, and a `surfaceView` is composited outside the app's view hierarchy — it ignores its parent's clip, radius and transform, which is every property a flying box relies on." },
        { name: 'renderVideo', type: 'MediaVideoSlot', optional: true, description: 'Paint the video yourself, keeping your own `ref` and expo-video props.' },
        { name: 'nativeControls', type: 'boolean', optional: true, description: "Whether the video arm shows expo-video's own controls. Defaults to `false`." },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'pointerEvents', type: "'auto' | 'none' | 'box-none' | 'box-only'", options: ['auto', 'none', 'box-none', 'box-only'], optional: true, description: 'Passed through as a PROP, never as a style key: react-native-web resolves the RN-only `box-none`/`box-only` values from the prop path only.' },
        { name: 'flightId', type: 'string', optional: true, description: 'Set this on the DESTINATION surface of a media flight, to the same id the flight was started with. When this surface presents its first frame it tells the layer to let the flying copy go.' },
        { name: 'detached', type: 'boolean', optional: true, description: 'Render the video arm with NO player, unbinding this element from it while the element is still in the DOM.' },
      ],
    },
    'MediaPoster': {
      props: [
        { name: 'content', type: 'MediaSurfaceContent', optional: false },
        { name: 'style', type: 'MediaPosterStyle', optional: true },
        { name: 'contentFit', type: "'contain' | 'cover'", options: ['contain', 'cover'], optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true },
      ],
    },
    'EmptyMediaSurface': {
      props: [
        { name: 'style', type: 'MediaPosterStyle', optional: true },
      ],
    },
  },
  components: [
    { name: 'MediaFlightLayer' },
    { name: 'MediaFlightHost', propsType: 'MediaFlightHostProps<P>' },
    { name: 'MediaSurface', propsType: 'MediaSurfaceProps' },
    { name: 'MediaPoster', propsType: 'MediaPoster' },
    { name: 'EmptyMediaSurface', propsType: 'EmptyMediaSurface' },
  ],
}
