// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'menu-item',
  propTypes: {
    'MenuItemOptionsProps': {
      props: [
        { name: 'groups', type: 'ReadonlyArray<MenuItemOptionGroup>', optional: false, description: 'The questions, in the order they are asked.' },
        { name: 'value', type: 'Readonly<Record<string, ReadonlyArray<string>>>', optional: false, description: 'The chosen option ids, per group id. Fully controlled — it keeps no state.' },
        { name: 'onValueChange', type: '(groupId: string, optionIds: ReadonlyArray<string>) => void', optional: false, description: "Called with the group and its next selection, already capped at the group's `max`." },
        { name: 'quantity', type: 'number', optional: true, description: 'How many of the dish. Without `onQuantityChange` no quantity row is drawn.' },
        { name: 'onQuantityChange', type: '(quantity: number) => void', optional: true },
        { name: 'quantityLabel', type: 'string', optional: true, description: 'The quantity row\'s title. Default `"Quantity"`.' },
        { name: 'total', type: 'string', optional: true, description: 'The running price, PRE-FORMATTED — "€16.40". The app recomputes it as the choices change; this component never adds anything up.' },
        { name: 'onSubmit', type: '() => void', optional: true, description: 'The footer button. Without it no footer is drawn.' },
        { name: 'submitLabel', type: 'string', optional: true, description: 'The footer button\'s label. Default `"Add to basket"`.' },
        { name: 'submitDisabled', type: 'boolean', optional: true, description: 'Blocks the footer button — a required group with nothing chosen.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Disables every control, the footer included.' },
        { name: 'header', type: 'ReactNode', optional: true, description: "A node above the groups — the dish's own photo, name and description." },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the set of questions. Default `"Options"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'MenuItemRowProps': {
      props: [
        { name: 'name', type: 'string', optional: false, description: "The dish's name. One line, truncated." },
        { name: 'description', type: 'string', optional: true, description: "What is in it. Clamped to two lines — the full text belongs on the dish's own screen." },
        { name: 'price', type: 'string', optional: false, description: 'PRE-FORMATTED — "€12.50". Nothing here parses, converts or adds up a price.' },
        { name: 'originalPrice', type: 'string', optional: true, description: 'PRE-FORMATTED price before a discount, struck through BEFORE `price`.' },
        { name: 'photo', type: 'string', optional: true, description: "An absolute URL, or an id the app's `ImageResolver` turns into one." },
        { name: 'photoVariant', type: 'string', optional: true, description: 'The `ImageResolver` rendition for a photo id. Ignored for URLs.' },
        { name: 'diets', type: 'ReadonlyArray<MenuItemDiet>', optional: true, description: 'Drawn as pills after the name, in the order given. Duplicates are drawn once.' },
        { name: 'dietLabels', type: 'Partial<Record<MenuItemDiet, string>>', optional: true, description: 'Replaces the English diet words ("Vegan", "Gluten-free", …).' },
        { name: 'spice', type: 'number', optional: true, description: 'How hot it is, `0`–`3`, drawn as that many flames. A LEVEL rather than a pill: heat is a quantity, and a pill that says "Spicy" cannot tell a reader whether one is enough.' },
        { name: 'spiceLabel', type: 'string', optional: true, description: 'The word the flames are announced with. Default `"Spicy"` (as "Spicy 2 of 3").' },
        { name: 'quantity', type: 'number', optional: true, description: 'How many are already in the basket. Drawn ONCE: in the `Stepper` when `onQuantityChange` is given (which is where you would change it), and as a count over the thumbnail otherwise. Two spellings of one number is a reader asking which of them is the real one.' },
        { name: 'onQuantityChange', type: '(quantity: number) => void', optional: true, description: 'With a `quantity` above zero, the trailing control is a `Stepper` driving this.' },
        { name: 'onAdd', type: '() => void', optional: true, description: 'The add control. Drawn while nothing is in the basket yet.' },
        { name: 'addLabel', type: 'string', optional: true, description: 'Names the add control, which draws no text. Default `"Add <name>"`.' },
        { name: 'unavailable', type: 'boolean', optional: true, description: 'Sold out: the photo washes toward the page, the row dims and every control goes.' },
        { name: 'unavailableLabel', type: 'string', optional: true, description: 'Default `"Sold out"`.' },
        { name: 'onPress', type: '() => void', optional: true, description: 'Opens the dish — its options, its full description.' },
        { name: 'density', type: 'MenuItemDensity', options: ['comfortable', 'compact'], optional: true, description: 'Default `comfortable`.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Replaces the composed name ("Ember flatbread, Vegan, Spicy 2 of 3, €12.50, Sold out").' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'MenuItemOptions', propsType: 'MenuItemOptionsProps' },
    { name: 'MenuItemRow', propsType: 'MenuItemRowProps' },
  ],
}
