// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'motion',
  propTypes: {
    'ScreenTransitionProps': {
      props: [
        { name: 'direction', type: 'ScreenTransitionDirection', options: ['forward', 'backward'], optional: false, description: "`'forward'` slides the new screen in from the right, `'backward'` from the left — matching a push / pop navigation gesture." },
        { name: 'enabledWeb', type: 'boolean', optional: true, description: 'Enable the transition on web. Off by default: Reanimated layout animations are fragile across web bundlers, so web opts in explicitly and gets a lightweight cross-fade rather than a slide.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'children', type: 'React.ReactNode', optional: true },
      ],
    },
  },
  components: [
    { name: 'ScreenTransition', propsType: 'ScreenTransitionProps' },
  ],
}
