// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'multi-agent-chat',
  propTypes: {
    'MultiAgentChatProps': {
      props: [
        { name: 'providers', type: "ReadonlyArray<import('../composer-panel/types').ModelPickerProvider>", optional: true, description: "Model catalogue passed to Bloom's shared composer picker." },
        { name: 'onRespond', type: '(agent: Agent, messages: Message[], signal: AbortSignal) => Promise<string>', optional: true },
        { name: 'initialWorkspace', type: 'Workspace', optional: true },
        { name: 'defaultEditorId', type: 'string | null', optional: true },
        { name: 'storageKey', type: 'string | null', optional: true, description: 'Web persistence; null disables storage. Native retains session state.' },
        { name: 'onWorkspaceChange', type: '(workspace: Workspace) => void', optional: true },
        { name: 'onCopy', type: '(text: string) => void | Promise<void>', optional: true, description: 'Clipboard integration for native hosts; web uses navigator.clipboard by default.' },
        { name: 'voices', type: 'readonly AgentVoice[]', optional: true },
        { name: 'onPreviewVoice', type: '(text: string, preferences: AgentPreferences) => void', optional: true },
        { name: 'className', type: 'string', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'MultiAgentChat', propsType: 'MultiAgentChatProps' },
  ],
}
