// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'notification',
  propTypes: {
    'NotificationProps': {
      props: [
        { name: 'title', type: 'React.ReactNode', optional: false },
        { name: 'description', type: 'React.ReactNode', optional: true },
        { name: 'timestamp', type: 'React.ReactNode', optional: true, description: 'Muted text after the title, e.g. `2m ago`.' },
        { name: 'status', type: 'NotificationStatus', options: ['neutral', 'information', 'success', 'warning', 'error'], optional: true, description: 'Colours the leading disc. Defaults to `neutral`.' },
        { name: 'icon', type: 'NotificationIconComponent', optional: true, description: 'Custom leading glyph. Defaults to the icon associated with `status`.' },
        { name: 'avatar', type: 'NotificationAvatar', optional: true, description: 'Avatar leading visual. Takes precedence over `icon`.' },
        { name: 'actions', type: 'NotificationAction[]', optional: true, description: 'Small action buttons below the message.' },
        { name: 'dismissible', type: 'boolean', optional: true, description: 'Show the close button. Defaults to `true`.' },
        { name: 'closeLabel', type: 'string', optional: true, description: 'Accessible name of the close button. Defaults to `Dismiss notification`.' },
        { name: 'onDismiss', type: '() => void', optional: true, description: 'Called after the dismiss exit animation completes.' },
        { name: 'autoDismissDuration', type: 'number', optional: true, description: 'Dismiss automatically after this many milliseconds, drawing a 3px accent countdown bar along the bottom edge for the same duration.' },
        { name: 'introDelay', type: 'number', optional: true, description: 'Opt into the entrance animation, after this many SECONDS.' },
        { name: 'role', type: "'alert' | 'status'", options: ['alert', 'status'], optional: true, description: 'The live-region role. Defaults to `alert` for `error` and `status` for the rest.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'NotificationStatusVisual': {
      props: [
        { name: 'status', type: 'NotificationStatus', options: ['neutral', 'information', 'success', 'warning', 'error'], optional: false },
        { name: 'icon', type: 'NotificationIconComponent', optional: true },
        { name: 'paint', type: 'NotificationPaint', optional: false },
        { name: 'children', type: 'React.ReactNode', optional: true, description: 'Replaces the glyph (e.g. a spinner) while keeping the disc.' },
      ],
    },
  },
  components: [
    { name: 'Notification', propsType: 'NotificationProps' },
    { name: 'NotificationStatusVisual', propsType: 'NotificationStatusVisual' },
  ],
}
