// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'offering-badge',
  propTypes: {
    'OfferingBadgeProps': {
      props: [
        { name: 'offering', type: 'Offering', options: ['long_term_rent', 'short_term_rent', 'sale', 'exchange'], optional: false, description: 'What the listing is offered as. Picks the default label, icon and tint.' },
        { name: 'label', type: 'string', optional: true, description: 'Replaces the default label ("For rent", "For sale", "Vacation rental", "Swap").' },
        { name: 'icon', type: 'boolean | OfferingBadgeIcon', optional: true, description: "`true` (default) draws the offering's own icon, `false` none, a component replaces it." },
        { name: 'size', type: 'OfferingBadgeSize', options: ['small', 'medium'], optional: true, description: 'Default `medium`.' },
        { name: 'variant', type: 'OfferingBadgeVariant', options: ['tinted', 'onMedia'], optional: true, description: 'Default `tinted`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'OfferingBadge', propsType: 'OfferingBadgeProps' },
  ],
}
