// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'order-status',
  propTypes: {
    'OrderStatusBarProps': {
      props: [
        { name: 'status', type: 'string', optional: false, description: 'The live line — "Out for delivery", "Cooking", "Driver on the way".' },
        { name: 'eta', type: 'string', optional: true, description: 'The arrival reading, pre-formatted by the app: "Arrives 14:35", "12 min". Drawn at the end of the status line, in tabular figures so it does not jitter as it counts down.' },
        { name: 'detail', type: 'string', optional: true, description: 'A quieter second line — "Four stops away", "Table 6".' },
        { name: 'progress', type: 'OrderStatusProgress', optional: true, description: 'How far along. Without it no bar is drawn.' },
        { name: 'tone', type: 'AccentTone', options: ['default', 'primary', 'secondary', 'tertiary', 'success', 'warning', 'error', 'info'], optional: true, description: 'The tone of the glyph tile and the bar. Default `primary`.' },
        { name: 'icon', type: 'BloomIconComponent', optional: true, description: 'A glyph in the leading tile. Without it (and without `leading`) no tile is drawn.' },
        { name: 'leading', type: 'ReactNode', optional: true, description: 'An arbitrary leading node — an `Avatar`, a photo. Wins over `icon`.' },
        { name: 'action', type: 'ReactNode', optional: true, description: 'A trailing control — a `Button`, a `GlyphButton`.' },
        { name: 'variant', type: 'OrderStatusBarVariant', options: ['surface', 'plain'], optional: true, description: 'Default `surface`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'OrderStatusTimelineProps': {
      props: [
        { name: 'steps', type: 'readonly OrderStatusStep[]', optional: false, description: 'The steps, in the order they happen.' },
        { name: 'orientation', type: 'OrderStatusOrientation', options: ['vertical', 'horizontal'], optional: true, description: 'Default `vertical`.' },
        { name: 'density', type: 'OrderStatusDensity', options: ['comfortable', 'compact'], optional: true, description: 'Default `comfortable`.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the list as a whole. Default `"Status"`.' },
        { name: 'stateLabels', type: 'Partial<Record<OrderStatusStepState, string>>', optional: true, description: 'What a screen reader announces for each state, before the step\'s own label. Defaults are `"Done"`, `"In progress"`, `"Not yet"`, `"Failed"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'OrderStatusBar', propsType: 'OrderStatusBarProps' },
    { name: 'OrderStatusTimeline', propsType: 'OrderStatusTimelineProps' },
  ],
}
