// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'order-confirmation',
  propTypes: {
    'OrderConfirmationProps': {
      props: [
        { name: 'title', type: 'string', optional: true, description: 'Default `"Your order is placed"`.' },
        { name: 'description', type: 'string', optional: true, description: 'The line under it — "We have sent the receipt to your inbox."' },
        { name: 'mark', type: 'ReactNode', optional: true, description: 'The mark above the title. Default a check on a success-tinted disc — a STATIC one, because `AnimatedCheck` draws itself on only when a caller kicks it through its ref, and a mark nobody can see until a method runs is not a mark. Pass `<AnimatedCheck>` (played by your own ref) for the draw-on, a brand mark, or `null` for none.' },
        { name: 'markSize', type: 'number', optional: true, description: "The default mark's box. Default 56." },
        { name: 'reference', type: 'string', optional: true, description: 'The order\'s own number — "A-4821". PRE-FORMATTED, including any prefix.' },
        { name: 'referenceLabel', type: 'string', optional: true, description: 'The caption above it. Default `"Order number"`.' },
        { name: 'status', type: 'OrderStatusBarProps', optional: true, description: 'The tracking strip — `order-status`\'s `OrderStatusBar`, passed straight through. This family draws no second one: "where it is right now" has one component in the library and this is a place that shows it.' },
        { name: 'address', type: 'OrderConfirmationAddress', optional: true, description: 'Where it goes.' },
        { name: 'facts', type: 'readonly OrderConfirmationFact[]', optional: true, description: 'When it arrives, what was charged, and anything else worth reading back.' },
        { name: 'items', type: 'ReactNode', optional: true, description: "What was ordered, in full — the basket's own rows, rendered by the app. A slot rather than data: a line of an order is a dish, a parcel or a seat depending on the app, and each already has a row family of its own." },
        { name: 'itemsLabel', type: 'string', optional: true, description: 'The caption above `items`. Default `"What you ordered"`.' },
        { name: 'action', type: 'EmptyStateAction', optional: true, description: 'The first thing you do next — normally "Track order".' },
        { name: 'secondaryAction', type: 'EmptyStateAction', optional: true, description: 'The other one — normally "Get help".' },
        { name: 'footer', type: 'ReactNode', optional: true, description: 'Under the actions — a "Back to the shop" link, a note.' },
        { name: 'variant', type: 'EmptyStateVariant', options: ['comfortable', 'compact'], optional: true, description: 'Default `comfortable`. `compact` is the panel rung.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the whole surface. Defaults to the title and the reference.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'OrderConfirmation', propsType: 'OrderConfirmationProps' },
  ],
}
