// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'overlay',
  propTypes: {
    'OverlayRootProps': {
      props: [
        { name: 'children', type: 'ReactNode', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
        { name: 'className', type: 'string', optional: true, description: "NativeWind / DOM class for the surface's outermost node." },
        { name: 'zIndex', type: 'number', optional: true, description: 'Opt OUT of the open-order stack and pin to a fixed depth. Only the toast layer does this — a notification has to stay visible over whatever is open, including a surface opened after it. Everything else must leave this unset so it stacks by open order; a hand-picked number here is precisely the bug `./stack.ts` exists to remove.' },
      ],
    },
    'BackdropProps': {
      props: [
        { name: 'onPress', type: '() => void', optional: true, description: 'Dismiss handler. Omit (or pass `disabled`) for a backdrop that only dims.' },
        { name: 'progress', type: 'SharedValue<number>', optional: true, description: 'Fade driver, 0 (hidden) → 1 (fully shown). The backdrop applies it to its OWN layers — see the note on `style` for why the caller must not animate opacity from the outside.' },
        { name: 'disabled', type: 'boolean', optional: true, description: '`true` keeps the dim but makes it inert — a blocking dialog, a busy state.' },
        { name: 'blurIntensity', type: 'number', optional: true, description: 'Blur radius behind the dim. `0` renders the dim alone.' },
        { name: 'blurTint', type: "'light' | 'dark' | 'default'", options: ['light', 'dark', 'default'], optional: true, description: 'Blur tint. Backdrops dim the app, so `dark` is the default on every theme.' },
        { name: 'dimColor', type: 'string', optional: true, description: 'Dim colour over the blur.' },
        { name: 'dimOpacity', type: 'number', optional: true, description: 'Dim opacity, 0–1.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: "Geometry for the press target: insets, layout. NOT a z-index — where this surface sits relative to others is `OverlayRoot`'s call (see `./stack.ts`), and within the surface the panel is simply rendered after this. NOT opacity either — `backdrop-filter` samples nothing under an ancestor with `opacity < 1` (the group composites in isolation), so a fade applied here silently kills the blur. An `opacity` found in this style is redirected onto the layers; animate the fade through `progress` instead." },
        { name: 'layerStyle', type: 'StyleProp<ViewStyle>', optional: true, description: "Extra style for the blur + dim LAYERS, for fades a shared value can't express — the web dialog's CSS keyframes, for instance." },
        { name: 'children', type: 'ReactNode', optional: true, description: "Rendered ON TOP of the dim, as a sibling of the press target (Dialog's panel does this)." },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'OverlayRoot', propsType: 'OverlayRootProps' },
    { name: 'Backdrop', propsType: 'BackdropProps' },
  ],
}
