// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'page-footer',
  propTypes: {
    'PageFooterProps': {
      props: [
        { name: 'children', type: 'ReactNode', optional: true, description: 'Optional content before the actions, for example a selection summary.' },
        { name: 'actions', type: 'ReactNode', optional: true, description: 'Controls grouped by the caller; inherits the surrounding Bloom size.' },
        { name: 'bottomInset', type: 'number', optional: true, description: "Distance from the containing frame's bottom. Defaults to the occupied bottom edge (for example AppShell's measured bottom bar). Pass 0 when the frame already ends above navigation, or the footer is in a desktop pane." },
        { name: 'safeArea', type: 'boolean', optional: true, description: 'Include the bottom safe area when no bottom edge is occupied. Defaults to true on native, false on web. Disable when the containing shell owns it.' },
        { name: 'scrim', type: "'auto' | 'always' | 'none'", options: ['auto', 'always', 'none'], optional: true, description: 'Mirrored PageHeader gradient. Default always preserves existing behavior. auto follows ScrollMetricsProvider: hidden at the bottom or for short / unmeasured content, fading in over scrollThreshold of remaining content.' },
        { name: 'scrollThreshold', type: 'number', optional: true, description: 'Distance from the bottom over which the automatic scrim fades. Default 20.' },
        { name: 'scrimColor', type: 'string', optional: true, description: "Opaque gradient color; defaults to the containing surface's fill." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'PageFooterProvider': {
      props: [],
      inheritsFrom: ['PropsWithChildren'],
    },
  },
  components: [
    { name: 'PageFooter', propsType: 'PageFooterProps' },
    { name: 'PageFooterProvider', propsType: 'PageFooterProvider' },
  ],
}
