// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'page-header',
  propTypes: {
    'PageHeaderProps': {
      props: [
        { name: 'title', type: 'ReactNode', optional: true, description: 'A string renders as the heading; a node renders as-is (and owns its own semantics).' },
        { name: 'subtitle', type: 'ReactNode', optional: true, description: 'A string renders as a secondary line under the title; a node renders as-is.' },
        { name: 'titleAlign', type: 'PageHeaderTitleAlign', options: ['start', 'center'], optional: true, description: 'Default `start`.' },
        { name: 'headingLevel', type: '1 | 2 | 3 | 4 | 5 | 6', optional: true, description: "The title's heading level. Default 1." },
        { name: 'titleReveal', type: 'PageHeaderTitleReveal', options: ['always', 'onScroll', 'onDock'], optional: true, description: 'Default `always`.' },
        { name: 'titleRevealOffset', type: 'number', optional: true, description: 'Scroll distance before title and subtitle begin revealing. Default0; fade spans scrollThreshold.' },
        { name: 'presentation', type: 'PageHeaderPresentation', options: ['floating', 'bar'], optional: true, description: 'Default `floating`.' },
        { name: 'placement', type: 'PageHeaderPlacement', options: ['inline', 'overlay', 'overlap'], optional: true, description: 'Default `inline`.' },
        { name: 'onBack', type: '() => void', optional: true, description: "Renders the back button and is called when it is pressed. The header is router-agnostic: pass `router.back`, or your app's safe-back helper." },
        { name: 'backLabel', type: 'string', optional: true, description: 'The back button\'s accessible name. Default "Back".' },
        { name: 'leading', type: 'ReactNode', optional: true, description: 'Rendered after the back button, before the title (an avatar, a logo).' },
        { name: 'actions', type: 'ReactNode', optional: true, description: "Rendered at the end of the bar. In the floating presentation this slot is wrapped in a `ControlSurface` with `material: 'glass'`, so a `ButtonGroup` inside it becomes one island with no prop written on it. Declare the grouping yourself — the header never infers it by reading children." },
        { name: 'border', type: 'PageHeaderBorder', options: ['auto', 'always', 'none'], optional: true, description: '`presentation="bar"` only. Default `auto`.' },
        { name: 'transparent', type: 'boolean', optional: true, description: '`presentation="bar"` only: the bar\'s background and shadow fade in with scroll instead of showing at rest.' },
        { name: 'scrim', type: 'PageHeaderScrim', options: ['auto', 'always', 'none'], optional: true, description: '`presentation="floating"` only. Default `auto`.' },
        { name: 'scrimColor', type: 'string', optional: true, description: 'The colour the edge effect fades FROM. Defaults to `theme.colors.background` — the page colour, which is what the content scrolling under the header is disappearing into.' },
        { name: 'scrollY', type: 'SharedValue<number>', optional: true, description: 'The scroll offset driving the scrim, the separator and the shadow.' },
        { name: 'scrollThreshold', type: 'number', optional: true, description: 'The offset (px) over which the scrim, separator and shadow fade in. Default 20.' },
        { name: 'sticky', type: 'boolean', optional: true, description: 'Web only: pin the bar to the top of its scroll container. Default true.' },
        { name: 'safeArea', type: 'boolean', optional: true, description: 'Pad the top by the safe-area inset. Default true on native, false on web.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'PageHeader', propsType: 'PageHeaderProps' },
  ],
}
