// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'pagination',
  propTypes: {
    'PaginationProps': {
      props: [
        { name: 'page', type: 'number', optional: false, description: 'The current page, 1-based. Controlled.' },
        { name: 'totalPages', type: 'number', optional: false, description: 'Total number of pages. Renders nothing when 1 or fewer.' },
        { name: 'onChange', type: '(page: number) => void', optional: false, description: 'Called with the requested page.' },
        { name: 'siblingCount', type: 'number', optional: true, description: 'Page numbers shown on each side of the current page. Default 1 (0 when compact).' },
        { name: 'previousLabel', type: 'string', optional: true, description: 'Label of the Previous button, and its accessible name when compact. Default `"Previous"`.' },
        { name: 'nextLabel', type: 'string', optional: true, description: 'Label of the Next button, and its accessible name when compact. Default `"Next"`.' },
        { name: 'getPageLabel', type: '(page: number) => string', optional: true, description: 'Accessible name of a page button. Default `` `Go to page ${page}` ``.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the navigation landmark. Default `"Pagination"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Pagination', propsType: 'PaginationProps' },
  ],
}
