// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'patient-info-card',
  propTypes: {
    'PatientInfoCardProps': {
      props: [
        { name: 'name', type: 'string', optional: false, description: 'Patient name under the photo.' },
        { name: 'avatarSource', type: 'string | ImageSourcePropType | null', optional: true, description: 'Photo. Without one the avatar shows `initials` on the neutral disc.' },
        { name: 'initials', type: 'string', optional: true, description: 'Initials for the photo-less disc. Defaults to the first letter of `name`.' },
        { name: 'details', type: 'readonly PatientInfoCardDetail[]', optional: false, description: 'Label / value rows under the name.' },
        { name: 'onAddPhoto', type: '() => void', optional: true, description: 'Press handler of the `+` button pinned to the avatar.' },
        { name: 'addPhotoLabel', type: 'string', optional: true, description: 'Accessible name of the `+` button. Defaults to `"Add profile photo"`.' },
        { name: 'hideAddPhoto', type: 'boolean', optional: true, description: 'Hide the `+` button.' },
        { name: 'height', type: 'number', optional: true, description: 'Card height. Defaults to `330`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'PatientInfoCard', propsType: 'PatientInfoCardProps' },
  ],
}
