// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'payment-method',
  propTypes: {
    'PaymentMethodListProps': {
      props: [
        { name: 'methods', type: 'readonly PaymentMethodEntry[]', optional: false, description: 'The saved methods, in the order they should be read.' },
        { name: 'selectedId', type: 'string', optional: true, description: 'The chosen entry\'s `id`. Only meaningful for `variant="picker"`.' },
        { name: 'onSelect', type: '(id: string) => void', optional: true },
        { name: 'variant', type: 'PaymentMethodListVariant', options: ['list', 'picker'], optional: true, description: 'Default `list`.' },
        { name: 'density', type: 'PaymentMethodDensity', options: ['comfortable', 'compact'], optional: true, description: 'Default `comfortable`.' },
        { name: 'disabled', type: 'boolean', optional: true, description: "Disables every row. Combined with an enclosing `Field`'s `disabled` with `||`, never replaced — a row inside a disabled field cannot re-enable itself." },
        { name: 'onAdd', type: '() => void', optional: true, description: 'Draws the "add a method" row under the list. Without it no row is drawn.' },
        { name: 'addLabel', type: 'string', optional: true, description: 'Default `"Add a payment method"`.' },
        { name: 'addIcon', type: 'BloomIconComponent', optional: true, description: 'The glyph on the add row. Default a plus.' },
        { name: 'loading', type: 'boolean', optional: true, description: 'Draws placeholder rows instead of the methods.' },
        { name: 'loadingRows', type: 'number', optional: true, description: 'How many placeholder rows. Default 3.' },
        { name: 'empty', type: 'ReactNode', optional: true, description: 'Replaces the whole empty block. The add row is still drawn under it.' },
        { name: 'emptyTitle', type: 'string', optional: true, description: 'Default `"No saved payment methods"`.' },
        { name: 'emptyDescription', type: 'string', optional: true },
        { name: 'emptyIcon', type: 'BloomIconComponent', optional: true, description: 'The glyph above the empty text. Default a card.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the list — and, for a picker, the `radiogroup`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'PaymentMethodMarkProps': {
      props: [
        { name: 'scheme', type: 'string', optional: true, description: "The scheme's name, spelled by the APP — Bloom ships no list of schemes. Drawn as text beside the plate. Omit it for the plate alone, which is what `PaymentMethodRow` does: the row already draws the name in its title." },
        { name: 'kind', type: 'PaymentMethodKind', options: ['card', 'account', 'wallet', 'cash'], optional: true, description: 'Chooses the default glyph. Default `card`.' },
        { name: 'icon', type: 'BloomIconComponent', optional: true, description: 'The glyph, overriding whatever `kind` would have chosen.' },
        { name: 'image', type: 'ReactNode', optional: true, description: 'An image the app has the rights to, drawn inside the plate instead of the glyph. Read for PRESENCE, so `image={null}` is an empty plate rather than the glyph.' },
        { name: 'state', type: 'PaymentMethodState', options: ['ok', 'expired', 'declined'], optional: true, description: "Paints the plate in the state's tone. Default `ok`." },
        { name: 'density', type: 'PaymentMethodDensity', options: ['comfortable', 'compact'], optional: true, description: 'Default `comfortable`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'PaymentMethodRowProps': {
      props: [
        { name: 'scheme', type: 'string', optional: true, description: 'The scheme\'s name, spelled by the app — "Aurora", "Meridian".' },
        { name: 'masked', type: 'string', optional: true, description: 'The MASKED identifier — `"•••• 4417"`, `"ES•• •••• 8842"`, `"nil@example"`.' },
        { name: 'expiry', type: 'string', optional: true, description: 'Pre-formatted by the app: `"09/29"`, `"Expires 09/29"`. Bloom never reads a clock, so whether that date is in the past is the app\'s finding, reported through `state`.' },
        { name: 'kind', type: 'PaymentMethodKind', options: ['card', 'account', 'wallet', 'cash'], optional: true, description: 'Chooses the default glyph on the mark. Default `card`.' },
        { name: 'icon', type: 'BloomIconComponent', optional: true, description: 'The glyph, overriding whatever `kind` would have chosen.' },
        { name: 'image', type: 'ReactNode', optional: true, description: 'An image the app has the rights to, drawn inside the plate.' },
        { name: 'leading', type: 'ReactNode', optional: true, description: 'An arbitrary leading node instead of the mark. Read for PRESENCE: `leading={null}` draws no media at all.' },
        { name: 'isDefault', type: 'boolean', optional: true, description: 'Marks this as the one that will be charged. Draws a `Badge`.' },
        { name: 'defaultLabel', type: 'string', optional: true, description: 'The default badge\'s word. Default `"Default"`.' },
        { name: 'state', type: 'PaymentMethodState', options: ['ok', 'expired', 'declined'], optional: true, description: 'Default `ok`.' },
        { name: 'stateMessage', type: 'string', optional: true, description: 'The words under the row when `state` is not `ok` — "Declined by your bank", "This card expired in June". Without it the row draws the state\'s own label.' },
        { name: 'selectable', type: 'boolean', optional: true, description: 'Draws the radio dot in the trailing slot and announces the row as a `radio`. `PaymentMethodList variant="picker"` sets it; set it yourself only for a row inside a `radiogroup` of your own.' },
        { name: 'selected', type: 'boolean', optional: true, description: 'Whether this is the chosen one. Announced as `aria-checked` on a `radio`.' },
        { name: 'action', type: 'ReactNode', optional: true, description: "A trailing control — a `GlyphButton` with the row's menu, a `Button`." },
        { name: 'onPress', type: '() => void', optional: true },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'density', type: 'PaymentMethodDensity', options: ['comfortable', 'compact'], optional: true, description: 'Default `comfortable`.' },
        { name: 'role', type: "'radio' | 'option' | 'listitem'", options: ['radio', 'option', 'listitem'], optional: true, description: 'What the row IS in the tree around it. `PaymentMethodList` passes this; a row on its own leaves it alone and gets a plain pressable row.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: "The announced name. Defaults to the scheme, the masked identifier, the default mark and the state, joined — the row's own text in reading order." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'PaymentMethodList', propsType: 'PaymentMethodListProps' },
    { name: 'PaymentMethodMark', propsType: 'PaymentMethodMarkProps' },
    { name: 'PaymentMethodRow', propsType: 'PaymentMethodRowProps' },
  ],
}
