// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'phone-input',
  propTypes: {
    'CountryFlagProps': {
      props: [
        { name: 'iso2', type: 'string', optional: false, description: 'ISO 3166-1 alpha-2. An unknown code renders nothing.' },
        { name: 'size', type: 'number', optional: true, description: 'Width in px; the flag is 3:2, so height is two thirds of it. Default `18` (`w-[18px] h-3`).' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Name the flag for assistive tech. Omitted (the default) the flag is DECORATIVE and hidden — right wherever the country name or dial code is written beside it.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
      ],
    },
    'CountryCodeSelectProps': {
      props: [
        { name: 'value', type: 'string', optional: true, description: 'Selected ISO code (controlled).' },
        { name: 'defaultValue', type: 'string', optional: true, description: 'Initial ISO code when uncontrolled. Default `US`.' },
        { name: 'onValueChange', type: '(iso2: string, country: Country) => void', optional: true },
        { name: 'countries', type: 'readonly Country[]', optional: true, description: 'The choosable countries. Default: every vendored country, by name.' },
        { name: 'label', type: 'string', optional: true, description: 'Accessible name of the trigger and the list. Default `Country code`.' },
        { name: 'disabled', type: 'boolean', optional: true },
      ],
    },
    'PhoneInputProps': {
      props: [
        { name: 'label', type: 'string', optional: true, description: "Visible label above the field; also the input's accessible name." },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: "The input's accessible name when there is no visible `label`. Default `Phone number`." },
        { name: 'placeholder', type: 'string', optional: true },
        { name: 'hint', type: 'string', optional: true, description: 'Caption under the field.' },
        { name: 'required', type: 'boolean', optional: true, description: 'Append the required asterisk to the label.' },
        { name: 'tooltip', type: 'boolean', optional: true, description: 'Show the info glyph after the label.' },
        { name: 'size', type: 'TextFieldSize', options: ['medium', 'sm', 'md', 'lg', 'xs', 'small'], optional: true, description: '`md` 36 (default) or `sm` 32.' },
        { name: 'invalid', type: 'boolean', optional: true },
        { name: 'isInvalid', type: 'boolean', optional: true },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'value', type: 'string', optional: true, description: 'The number as typed, without the dial code (controlled).' },
        { name: 'defaultValue', type: 'string', optional: true, description: 'Initial number when uncontrolled.' },
        { name: 'onValueChange', type: '(value: string) => void', optional: true },
        { name: 'country', type: 'string', optional: true, description: 'Selected ISO code (controlled).' },
        { name: 'defaultCountry', type: 'string', optional: true, description: 'Initial ISO code when uncontrolled. Default `US`.' },
        { name: 'onCountryChange', type: '(iso2: string, country: Country) => void', optional: true },
        { name: 'countries', type: 'readonly Country[]', optional: true, description: 'The choosable countries. Default: every vendored country, by name.' },
        { name: 'countrySelectLabel', type: 'string', optional: true, description: 'Accessible name of the country-code select. Default `Country code`.' },
        { name: 'trailingIcon', type: 'React.ComponentType<SVGIconProps>', optional: true, description: 'A 20px icon after the input (`trailingIcon`).' },
        { name: 'onFocus', type: '() => void', optional: true },
        { name: 'onBlur', type: '() => void', optional: true },
        { name: 'testID', type: 'string', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'The outer column (label, field, hint).' },
      ],
    },
  },
  components: [
    { name: 'CountryFlag', propsType: 'CountryFlagProps' },
    { name: 'CountryCodeSelect', propsType: 'CountryCodeSelectProps' },
    { name: 'PhoneInput', propsType: 'PhoneInputProps' },
  ],
}
