// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'pipeline',
  propTypes: {
    'DealCardProps': {
      props: [
        { name: 'title', type: 'string', optional: false },
        { name: 'account', type: 'string', optional: true, description: 'The company the deal is with.' },
        { name: 'amount', type: 'string', optional: true, description: 'PRE-FORMATTED ("€48,000", "$1.2M"). Bloom never does money maths and never picks a currency, a locale or a rounding — the app has all three and the card would have to guess. It is drawn on one line and never wraps.' },
        { name: 'closeDate', type: 'string', optional: true, description: 'Pre-formatted ("Closes 30 Sep").' },
        { name: 'owner', type: 'DealOwner', optional: true },
        { name: 'stage', type: 'string', optional: true, description: 'The stage word, for a card drawn OUTSIDE a column (a search result, a list).' },
        { name: 'health', type: 'DealHealth', options: ['on-track', 'at-risk', 'stalled'], optional: true },
        { name: 'healthLabel', type: 'string', optional: true, description: "Overrides the health's own word." },
        { name: 'stalledFor', type: 'string', optional: true, description: 'How long it has been stalled, pre-formatted ("14 days"). With `health="stalled"` the signal reads "Stalled for 14 days"; on any other health it is ignored, because a deal that is moving has not stalled.' },
        { name: 'onPress', type: '() => void', optional: true, description: 'Opens the deal. Bound to the title block — see `docs/pipeline.mdx`.' },
        { name: 'onMove', type: '() => void', optional: true, description: 'Move the deal to another stage. The BOARD DOES NOT DRAG: this is the affordance that replaces it, and the app decides what it opens (a menu, a sheet, a dialog).' },
        { name: 'moveLabel', type: 'string', optional: true, description: 'The move action\'s accessible name. Default `"Move {title}"`.' },
        { name: 'actions', type: 'ReactNode', optional: true, description: 'Trailing slot beside the move action: a `DropdownMenu` trigger, an assign button.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the press target. Defaults to the title, the account and the amount.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'PipelineBoardProps': {
      props: [
        { name: 'stages', type: 'readonly PipelineStage[]', optional: false },
        { name: 'renderStage', type: '(stage: PipelineStage) => ReactNode', optional: false, description: 'The CARDS of one stage. Called per rendered column — once in `single`, once per stage in `board`. The board never inspects what it returns.' },
        { name: 'layout', type: 'PipelineBoardLayout', options: ['auto', 'board', 'single'], optional: true, description: 'Default `auto`.' },
        { name: 'stageId', type: 'string', optional: true, description: 'The visible stage in the `single` layout. Controlled.' },
        { name: 'defaultStageId', type: 'string', optional: true, description: 'The stage the `single` layout opens on. Uncontrolled; defaults to the first.' },
        { name: 'onStageChange', type: '(stageId: string) => void', optional: true },
        { name: 'columnWidth', type: 'number', optional: true, description: 'Column width in the `board` layout. Default 288.' },
        { name: 'singleMaxWidth', type: 'number', optional: true, description: 'At or below this width `auto` picks `single`. Default 700.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the board. Required by the tab row in the `single` layout.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'PipelineColumnProps': {
      props: [
        { name: 'children', type: 'ReactNode', optional: true, description: 'The deal cards.' },
        { name: 'width', type: 'number', optional: true, description: 'A fixed width, for a column inside a horizontal board. Omitted, it fills its parent.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
        { name: 'tone', type: 'AccentTone', options: ['default', 'primary', 'secondary', 'tertiary', 'success', 'warning', 'error', 'info'], optional: true, description: "The stage's dot. Default `primary`." },
        { name: 'loading', type: 'boolean', optional: true, description: 'Draws placeholder cards instead of the children.' },
        { name: 'name', type: 'string', optional: false },
        { name: 'total', type: 'string', optional: true, description: 'The summed amount, PRE-FORMATTED by the app for the same reason DealCardProps.amount is.' },
        { name: 'count', type: 'number', optional: true, description: 'Deals in the stage. Drawn as a counter beside the name.' },
        { name: 'emptyLabel', type: 'string', optional: true, description: 'What an empty column says. Default `"No deals in this stage"`.' },
        { name: 'onLoadMore', type: '() => void', optional: true, description: 'Renders the "load more" action under the cards.' },
        { name: 'loadMoreLabel', type: 'string', optional: true, description: 'Default `"Load more"`.' },
      ],
    },
  },
  components: [
    { name: 'DealCard', propsType: 'DealCardProps' },
    { name: 'PipelineBoard', propsType: 'PipelineBoardProps' },
    { name: 'PipelineColumn', propsType: 'PipelineColumnProps' },
  ],
}
