// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'place-card',
  propTypes: {
    'PlaceCardProps': {
      props: [
        { name: 'name', type: 'string', optional: false, description: 'The place\'s name ("Forner de la Plaça").' },
        { name: 'category', type: 'string', optional: true, description: 'What it is, pre-formatted and short ("Bakery · €€").' },
        { name: 'photo', type: 'string', optional: true, description: "The photo — an absolute URL, or an id the app's `ImageResolver` turns into one. `row` crops it square; `detail` uses it as the cover." },
        { name: 'photoVariant', type: 'string', optional: true, description: 'The `ImageResolver` rendition for a photo id. Ignored for URLs.' },
        { name: 'rating', type: 'number | string | null', optional: true, description: 'The rating on a 5 scale, drawn by Bloom\'s `Rating` beside the name. `undefined` draws nothing; `null` or `\'\'` draws the "New" label.' },
        { name: 'reviewCount', type: 'number | string', optional: true, description: 'The review count, after the rating ("(318)").' },
        { name: 'newLabel', type: 'string', optional: true, description: 'The "New" label of an unrated place. Default `"New"`.' },
        { name: 'openState', type: 'PlaceOpenState', options: ['open', 'closing-soon', 'closed', 'opening-soon'], optional: true, description: 'Whether the place is open now. Without it no state pill is drawn.' },
        { name: 'openLabel', type: 'string', optional: true, description: 'Replaces the English state word ("Open", "Closing soon", …).' },
        { name: 'hours', type: 'string', optional: true, description: 'The hours line, pre-formatted ("Open until 20:00", "Opens 08:00 tomorrow").' },
        { name: 'address', type: 'string', optional: true, description: 'The street line, drawn with a pin.' },
        { name: 'facts', type: 'ReadonlyArray<ListingFact>', optional: true, description: 'Compact facts with icons, one clipped row ("1.4 km", "12 min"). Same shape and same part as `ListingCard`\'s.' },
        { name: 'figure', type: 'string', optional: true, description: 'The FIGURE — the one reading the header leads with, usually the time to get there ("12 min"). Drawn tabular at title-1. `detail` only.' },
        { name: 'figureLabel', type: 'string', optional: true, description: 'The quiet label over the figure ("Drive from you"). `detail` only.' },
        { name: 'figureDetail', type: 'string', optional: true, description: 'A chip after the figure ("1.4 km"). `detail` only.' },
        { name: 'stats', type: 'readonly PlaceStat[]', optional: true, description: 'Tiles under the figure. `detail` only.' },
        { name: 'badge', type: 'ReactNode', optional: true, description: 'The slot above the name. A string draws a neutral `Badge`; any other node is placed as given.' },
        { name: 'actions', type: 'readonly PlaceAction[]', optional: true, description: 'The actions. `detail` draws them under the figure block; `row` under the row.' },
        { name: 'favorite', type: 'boolean', optional: true, description: 'Whether the place is saved. Omit `onFavoriteChange` too to hide the heart.' },
        { name: 'onFavoriteChange', type: '(favorite: boolean) => void', optional: true, description: 'Called with the next saved state. The heart is drawn only when this is given.' },
        { name: 'saveLabel', type: 'string', optional: true, description: 'Names of the heart, passed to `FavoriteButton`.' },
        { name: 'removeLabel', type: 'string', optional: true },
        { name: 'onPress', type: '() => void', optional: true, description: 'Opens the place. `row` only — a detail header is already the thing it opens.' },
        { name: 'href', type: 'string', optional: true, description: "The place's URL. On web the row is a real `<a href>`; on native a press opens it with `Linking` when there is no `onPress`. `row` only." },
        { name: 'loading', type: 'boolean', optional: true, description: 'Draws a skeleton in the same geometry instead of the place.' },
        { name: 'density', type: 'PlaceCardDensity', options: ['row', 'detail'], optional: true, description: 'Default `row`.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Replaces the composed accessible name ("Forner de la Plaça, Bakery · €€, Open, Open until 20:00, …"), which is English.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Parts get `<testID>-photo`, `-name`, `-state`, `-hours`, `-figure`, `-actions`.' },
      ],
    },
    'PlaceActionsProps': {
      props: [
        { name: 'actions', type: 'readonly PlaceAction[]', optional: false },
        { name: 'size', type: "'small' | 'medium'", options: ['small', 'medium'], optional: true, description: 'Default `small` — the rung `ai-profile-card` draws its header actions at.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the row, which is a `group`. Default `"Actions"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Each button gets `<testID>-<action id>`.' },
      ],
    },
  },
  components: [
    { name: 'PlaceCard', propsType: 'PlaceCardProps' },
    { name: 'PlaceActions', propsType: 'PlaceActionsProps' },
  ],
}
