// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'place-list',
  propTypes: {
    'PlaceListProps': {
      props: [
        { name: 'places', type: 'readonly PlaceListPlace[]', optional: false },
        { name: 'onReorder', type: '(places: PlaceListPlace[]) => void', optional: true, description: 'Called with the WHOLE list in its new order. Setting it draws the move controls; without it the list is not reorderable.' },
        { name: 'onRemove', type: '(id: string) => void', optional: true, description: "Called with the entry's id. Setting it draws the remove control." },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Stops reordering and removing, without hiding the controls.' },
        { name: 'labels', type: 'Partial<PlaceListLabels>', optional: true },
        { name: 'empty', type: 'ReactNode', optional: true, description: 'Drawn instead of the list when there are no places.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the list. Default `"Saved places"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Parts get `<testID>-item-<n>`, `-item-<n>-up`, `-down`, `-remove`, `-status`.' },
      ],
    },
    'PlaceListCardProps': {
      props: [
        { name: 'name', type: 'string', optional: false, description: 'The list\'s name ("Want to go", "Coffee, ranked").' },
        { name: 'count', type: 'number', optional: true, description: 'How many places are in it. Drawn through `countLabel`.' },
        { name: 'countLabel', type: '(count: number) => string', optional: true, description: "Default `(n) => n === 1 ? '1 place' : `${n} places``." },
        { name: 'photos', type: 'readonly string[]', optional: true, description: "The cover strip: the first four places' photos, each an absolute URL or an id the app's `ImageResolver` turns into one. The first one is wide." },
        { name: 'photoVariant', type: 'string', optional: true, description: 'The `ImageResolver` rendition for a photo id. Ignored for URLs.' },
        { name: 'empty', type: 'ReactNode', optional: true, description: 'What to draw on the strip when the list has no photos yet.' },
        { name: 'icon', type: 'BloomIconComponent', optional: true, description: "The list's own glyph, beside the name. DECORATIVE — a glyph put in the `name` string is read out as its character and cannot be coloured." },
        { name: 'color', type: 'string', optional: true, description: "The person's colour for this list. It paints the glyph and tints the empty strip. It is the caller's colour and not a token, because a list's colour is a choice Bloom has no ramp for." },
        { name: 'visibility', type: 'PlaceListVisibility', options: ['private', 'shared', 'public'], optional: true, description: 'Default `private`.' },
        { name: 'visibilityLabel', type: 'string', optional: true, description: 'Replaces the English visibility word.' },
        { name: 'collaborators', type: 'readonly AvatarGroupItem[]', optional: true, description: 'The people it is shared with, as `AvatarGroup` items.' },
        { name: 'sharedWithLabel', type: '(count: number) => string', optional: true, description: 'Default `(n) => `Shared with ${n}``. Announced, and drawn when there is room.' },
        { name: 'onPress', type: '() => void', optional: true, description: 'Opens the list.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Replaces the composed name ("Want to go, 12 places, shared with 3").' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Parts get `<testID>-cover`, `-name`, `-meta`, `-people`.' },
      ],
    },
  },
  components: [
    { name: 'PlaceList', propsType: 'PlaceListProps' },
    { name: 'PlaceListCard', propsType: 'PlaceListCardProps' },
  ],
}
