// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'price-breakdown',
  propTypes: {
    'PriceSummaryProps': {
      props: [
        { name: 'lines', type: 'readonly PriceLine[]', optional: false, description: 'The charges, in the order they should be read.' },
        { name: 'total', type: 'PriceTotal', optional: true, description: 'The answer. Without it the component draws the lines and no rule.' },
        { name: 'collapsible', type: 'boolean', optional: true, description: 'Hide the lines behind a disclosure, leaving the total visible. The total is deliberately never what collapses: the number a reader came for stays on screen and the ITEMISATION is what folds away.' },
        { name: 'expanded', type: 'boolean', optional: true, description: 'Controlled disclosure.' },
        { name: 'defaultExpanded', type: 'boolean', optional: true, description: 'Uncontrolled initial disclosure. Default `false`.' },
        { name: 'onExpandedChange', type: '(expanded: boolean) => void', optional: true },
        { name: 'expandLabel', type: 'string', optional: true, description: '`"Show price details"` in English.' },
        { name: 'collapseLabel', type: 'string', optional: true, description: '`"Hide price details"` in English.' },
        { name: 'stateLabels', type: 'PriceStateLabels', optional: true, description: 'Defaults (English): `estimated` → "Estimated", `pending` → "Pending".' },
        { name: 'pendingPlaceholder', type: 'string', optional: true, description: 'Drawn where the amount would be on a line that has none. Default `"—"`.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the list of charges (`"Price breakdown"` in English).' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'PriceSummaryLineProps': {
      props: [
        { name: 'stateLabels', type: 'PriceStateLabels', optional: true, description: 'Defaults (English): `estimated` → "Estimated", `pending` → "Pending".' },
        { name: 'pendingPlaceholder', type: 'string', optional: true, description: 'Drawn where the amount would be on a line that has none. Default `"—"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
        { name: 'tone', type: 'PriceLineTone', options: ['default', 'discount', 'muted'], optional: true, description: 'Default `default`.' },
        { name: 'info', type: 'ReactNode', optional: true, description: 'An explanation, shown in a `Popover` anchored to an info glyph after the label. Any node: a string, a `Text`, a short column.' },
        { name: 'label', type: 'string', optional: false, description: '"Subtotal", "Delivery", "Service fee".' },
        { name: 'state', type: 'PriceLineState', options: ['final', 'estimated', 'pending'], optional: true, description: 'Default `final`.' },
        { name: 'sublabel', type: 'string', optional: true, description: 'A quieter second line under the label — "3 items", "4.2 km".' },
        { name: 'amount', type: 'string', optional: true, description: 'PRE-FORMATTED, sign and currency included: `"€12.40"`, `"−€3.00"`, `"$0.00"`. Nothing in this family parses, adds or formats a number — the app owns currency, locale and the minus sign. Omit it for a `pending` line.' },
        { name: 'secondaryAmount', type: 'string', optional: true, description: 'A second, PRE-FORMATTED rendering of the same amount, drawn de-emphasised under it — the buyer\'s currency beside the shop\'s: `"≈ 12,00 €"`. Like `ListingPriceLine.secondary`, it is drawn as given; nothing converts.' },
        { name: 'infoAccessibilityLabel', type: 'string', optional: true, description: 'Names the info affordance — it draws a glyph and no text. Defaults to `"About <label>"`.' },
      ],
    },
  },
  components: [
    { name: 'PriceSummary', propsType: 'PriceSummaryProps' },
    { name: 'PriceSummaryLine', propsType: 'PriceSummaryLineProps' },
  ],
}
