// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'progressive-blur',
  propTypes: {
    'ProgressiveBlurProps': {
      props: [
        { name: 'intensity', type: 'number', optional: true, description: "Blur strength at the anchored edge. Follows `expo-blur`'s 0–100 scale and is applied PER LAYER on native (see the native fork); the web fork maps it onto the single CSS blur radius that approximates the same stack." },
        { name: 'direction', type: "'top' | 'bottom'", options: ['top', 'bottom'], optional: true, description: 'Which edge the blur is anchored to (strongest there, fading away).' },
      ],
      inheritsFrom: ['ViewProps'],
    },
  },
  components: [
    { name: 'ProgressiveBlur', propsType: 'ProgressiveBlurProps' },
  ],
}
