// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'project-board',
  propTypes: {
    'ProjectBoardProps': {
      props: [
        { name: 'onMenuClick', type: '() => void', optional: true },
        { name: 'title', type: 'string', optional: true },
        { name: 'teamName', type: 'string', optional: true },
        { name: 'ownerName', type: 'string', optional: true },
        { name: 'headerActions', type: 'ReactNode', optional: true, description: 'Product notification center or other header actions.' },
        { name: 'onInboxClick', type: '() => void', optional: true },
        { name: 'initialColumns', type: 'readonly ProjectColumn[]', optional: true, description: "Starting data is copied on mount; mutations never change the caller's objects." },
        { name: 'members', type: 'Readonly<Record<string, ProjectMember>>', optional: true },
        { name: 'projects', type: 'readonly string[]', optional: true },
        { name: 'currentUserId', type: 'string', optional: true },
        { name: 'onColumnsChange', type: '(columns: ProjectColumn[]) => void', optional: true, description: 'Called for create, property edits, comments, sorting and completed moves.' },
        { name: 'onTicketOpen', type: '(ticket: ProjectTicket) => void', optional: true },
        { name: 'onCopyTicketLink', type: '(ticket: ProjectTicket) => void | Promise<void>', optional: true, description: 'Use a product-specific route and clipboard implementation on native.' },
        { name: 'onCopyTicketId', type: '(code: string) => void | Promise<void>', optional: true },
        { name: 'initialTicketId', type: 'string', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'className', type: 'string', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'ProjectBoard', propsType: 'ProjectBoardProps' },
  ],
}
