// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'prompt-input',
  propTypes: {
    'PromptInputProps': {
      props: [
        { name: 'isLoading', type: 'boolean', optional: true, description: 'Whether the AI is currently generating a response' },
        { name: 'value', type: 'string', optional: true, description: 'Controlled text value' },
        { name: 'onValueChange', type: '(value: string) => void', optional: true, description: 'Callback when text value changes' },
        { name: 'maxHeight', type: 'number', optional: true, description: 'Max height for the textarea before scrolling (defaults to 240)' },
        { name: 'onSubmit', type: '() => void', optional: true, description: 'Called when user submits the prompt' },
        { name: 'children', type: 'ReactNode', optional: true, description: 'Compound mode children (overrides simple mode)' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Container style' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Whether the input is disabled' },
        { name: 'onImagePaste', type: '(files: File[]) => void', optional: true, description: 'Web-only: callback when images are pasted' },
        { name: 'placeholder', type: 'string', optional: true, description: 'Simple mode: placeholder text' },
        { name: 'actionsLeft', type: 'ReactNode', optional: true, description: 'Custom left-side actions in the actions bar' },
        { name: 'onStop', type: '() => void', optional: true, description: 'Called when user presses stop during loading' },
        { name: 'emptyAction', type: 'ReactNode', optional: true, description: 'Rendered when input is empty and not loading (e.g., mic button)' },
        { name: 'attachments', type: 'PromptInputAttachment[]', optional: true, description: 'Controlled attachments' },
        { name: 'onAddAttachment', type: '(attachment: PromptInputAttachment) => void', optional: true, description: 'Callback to add an attachment' },
        { name: 'onRemoveAttachment', type: '(id: string) => void', optional: true, description: 'Callback to remove an attachment' },
        { name: 'onUpdateAttachment', type: '(id: string, updates: Partial<PromptInputAttachment>) => void', optional: true, description: 'Callback to update an attachment' },
        { name: 'disableKeyboardAvoidance', type: 'boolean', optional: true, description: 'Skip the inner KeyboardAvoidingView (use when outer keyboard handling exists)' },
        { name: 'expandIcon', type: 'ReactNode', optional: true, description: 'Icon shown on the expand button (defaults to text "⤢")' },
        { name: 'collapseIcon', type: 'ReactNode', optional: true, description: 'Icon shown on the collapse button in fullscreen (defaults to text "⤡")' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'PromptInputTextareaProps': {
      props: [
        { name: 'placeholder', type: 'string', optional: true, description: 'Placeholder text' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Container style' },
        { name: 'inputStyle', type: 'StyleProp<TextStyle>', optional: true, description: 'Text input style' },
        { name: 'textInputProps', type: "Omit<TextInputProps, 'value' | 'onChangeText' | 'multiline' | 'editable'>", optional: true, description: 'Additional TextInput props' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'PromptInputActionsProps': {
      props: [
        { name: 'children', type: 'ReactNode', optional: false },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Container style' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'PromptInputAttachmentsProps': {
      props: [
        { name: 'removeIcon', type: 'ReactNode', optional: true, description: 'Custom remove button icon (defaults to "×" text)' },
        { name: 'renderDocumentIcon', type: '(mimeType: string, name: string) => ReactNode', optional: true, description: 'Custom render function for document type icons' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Container style' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'PromptInputSubmitButtonProps': {
      props: [
        { name: 'isLoading', type: 'boolean', optional: true, description: 'Whether the AI is currently generating' },
        { name: 'onStop', type: '() => void', optional: true, description: 'Called when user presses stop' },
        { name: 'emptyAction', type: 'ReactNode', optional: true, description: 'Rendered when input is empty and not loading' },
        { name: 'submitIcon', type: 'ReactNode', optional: true, description: 'Custom submit icon (defaults to "↑" text)' },
        { name: 'stopIcon', type: 'ReactNode', optional: true, description: 'Custom stop icon (defaults to "■" text)' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Container style' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'PromptInput', propsType: 'PromptInputProps' },
    { name: 'PromptInputTextarea', propsType: 'PromptInputTextareaProps' },
    { name: 'PromptInputActions', propsType: 'PromptInputActionsProps' },
    { name: 'PromptInputAttachments', propsType: 'PromptInputAttachmentsProps' },
    { name: 'PromptInputSubmitButton', propsType: 'PromptInputSubmitButtonProps' },
  ],
}
