// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'radio-indicator',
  propTypes: {
    'RadioIndicatorProps': {
      props: [
        { name: 'selected', type: 'boolean', optional: false, description: 'Whether the radio is selected' },
        { name: 'pressed', type: 'boolean', optional: true, description: 'Whether the control it belongs to is currently HELD.' },
        { name: 'size', type: 'number', optional: true, description: 'Outer circle size in pixels (defaults to 16, the `md` size; 14 is `sm`)' },
        { name: 'selectedColor', type: 'string', optional: true, description: 'Accent the selected gradient is built around (defaults to theme.colors.primary)' },
        { name: 'selectedForeground', type: 'string', optional: true, description: 'Foreground paired with selectedColor; shared tonal controls pass this with the fill.' },
        { name: 'borderColor', type: 'string', optional: true, description: 'Border color when unselected (defaults to the semantic border)' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Custom style' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'RadioIndicator', propsType: 'RadioIndicatorProps' },
  ],
}
