// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'radio',
  propTypes: {
    'RadioProps<Value>': {
      props: [
        { name: 'value', type: 'Value', optional: false, description: 'The value this option stands for.' },
        { name: 'selected', type: 'boolean', optional: false, description: 'Whether this option is the selected one.' },
        { name: 'onSelect', type: '(value: Value) => void', optional: false, description: 'Called with `value` when the option is chosen. Selecting the already-selected option is a no-op — a radio, unlike a checkbox, cannot be un-chosen.' },
        { name: 'label', type: 'string', optional: true, description: 'Optional label text.' },
        { name: 'description', type: 'string', optional: true, description: 'Optional description shown below the label.' },
        { name: 'size', type: 'RadioSize', options: ['small', 'medium', 'large'], optional: true, description: 'Size preset.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Whether the option is disabled.' },
        { name: 'color', type: 'string', optional: true, description: 'Colour of the selected indicator. Uses the theme primary by default.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'labelStyle', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'RadioGroupProps<Value>': {
      props: [
        { name: 'label', type: 'string', optional: false, description: "The group's accessible name. Required: a `radiogroup` with no name announces a list of options and nothing about what is being chosen." },
        { name: 'value', type: 'Value | undefined', optional: false, description: 'The selected value, or `undefined` for a group with nothing chosen yet.' },
        { name: 'onValueChange', type: '(value: Value) => void', optional: false, description: 'Called with the newly chosen value.' },
        { name: 'options', type: 'ReadonlyArray<RadioOption<Value>>', optional: false, description: 'The options, in order.' },
        { name: 'size', type: 'RadioSize', options: ['small', 'medium', 'large'], optional: true, description: 'Size preset, applied to every option.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Disables every option. An option may also disable itself.' },
        { name: 'color', type: 'string', optional: true, description: 'Colour of the selected indicator. Uses the theme primary by default.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'labelStyle', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Radio', propsType: 'RadioProps<Value>' },
    { name: 'RadioGroup', propsType: 'RadioGroupProps<Value>' },
  ],
}
