// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'radio',
  propTypes: {
    'RadioProps<Value>': {
      props: [
        { name: 'value', type: 'Value', optional: false, description: 'The value this option stands for.' },
        { name: 'checked', type: 'boolean', optional: true, description: 'Whether this option is the checked one.' },
        { name: 'selected', type: 'boolean', optional: true },
        { name: 'onValueChange', type: '(value: Value) => void', optional: true, description: 'Called with `value` when the option is chosen. Selecting the already-checked option is a no-op — a radio, unlike a checkbox, cannot be un-chosen.' },
        { name: 'onSelect', type: '(value: Value) => void', optional: true },
        { name: 'label', type: 'string', optional: true, description: 'Optional label text.' },
        { name: 'description', type: 'string', optional: true, description: 'Optional description shown below the label.' },
        { name: 'size', type: 'RadioSize', options: ['xs', 'sm', 'md', 'lg'], optional: true, description: 'Size preset.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Whether the option is disabled.' },
        { name: 'tone', type: 'BloomTone', options: ['neutral', 'accent', 'support', 'action', 'success', 'warning', 'danger', 'info'], optional: true, description: 'Colour of the checked indicator. Uses the theme primary by default.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'labelStyle', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'nativeID', type: 'string', optional: true, description: "The control's id. Inside a `Field` the field supplies one, so the label's `htmlFor` points at this control on web." },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'RadioGroupProps<Value>': {
      props: [
        { name: 'label', type: 'string', optional: true, description: "The group's accessible name." },
        { name: 'value', type: 'Value | undefined', optional: false, description: 'The selected value, or `undefined` for a group with nothing chosen yet.' },
        { name: 'onValueChange', type: '(value: Value) => void', optional: true, description: 'Called with the newly chosen value.' },
        { name: 'onSelect', type: '(value: Value) => void', optional: true },
        { name: 'options', type: 'ReadonlyArray<RadioOption<Value>>', optional: false, description: 'The options, in order.' },
        { name: 'size', type: 'RadioSize', options: ['xs', 'sm', 'md', 'lg'], optional: true, description: 'Size preset, applied to every option.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Disables every option. An option may also disable itself.' },
        { name: 'tone', type: 'BloomTone', options: ['neutral', 'accent', 'support', 'action', 'success', 'warning', 'danger', 'info'], optional: true, description: 'Colour of the checked indicator. Uses the theme primary by default.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'labelStyle', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'variant', type: "'default' | 'card'", options: ['default', 'card'], optional: true, description: "`default` renders each option as a `Radio` row; `card` as a `RadioCard` (title + description left, the dot right, the whole card selectable). A card's title is the option's `label`." },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'RadioCardProps<Value>': {
      props: [
        { name: 'value', type: 'Value', optional: false, description: 'The value this card stands for.' },
        { name: 'checked', type: 'boolean', optional: true, description: 'Whether this card is the checked one.' },
        { name: 'selected', type: 'boolean', optional: true },
        { name: 'onValueChange', type: '(value: Value) => void', optional: true, description: 'Called with `value` when the card is chosen. Re-choosing it is a no-op.' },
        { name: 'onSelect', type: '(value: Value) => void', optional: true },
        { name: 'title', type: 'string', optional: false, description: "The card's title (one line); also its accessible name." },
        { name: 'description', type: 'string', optional: true, description: 'Optional one-line description under the title.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Dims the whole card and stops it selecting.' },
        { name: 'tone', type: 'BloomTone', options: ['neutral', 'accent', 'support', 'action', 'success', 'warning', 'danger', 'info'], optional: true, description: 'Accent for the checked dot. Uses the theme primary by default.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Radio', propsType: 'RadioProps<Value>' },
    { name: 'RadioGroup', propsType: 'RadioGroupProps<Value>' },
    { name: 'RadioCard', propsType: 'RadioCardProps<Value>' },
  ],
}
