// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'rail',
  propTypes: {
    'RailProps': {
      props: [
        { name: 'items', type: 'RailItem[]', optional: false, description: 'The destinations to render, top to bottom.' },
        { name: 'activeId', type: 'string', optional: true, description: '`id` of the active item. An id naming no item (including `undefined`) leaves nothing selected — every item renders in its inactive state.' },
        { name: 'onSelect', type: '(id: string) => void', optional: false, description: "Called with an item's `id` when it is pressed." },
        { name: 'width', type: 'number', optional: true, description: 'Width of the rail, in px. Defaults to `80`, a comfortable column for an icon-plus-label item.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: "Container style override, merged after the rail's own positioning." },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Rail', propsType: 'RailProps' },
  ],
}
