// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'rating',
  propTypes: {
    'RatingProps': {
      props: [
        { name: 'value', type: 'number | string | null', optional: true, description: "The rating on a 5 scale. A number is drawn with up to two decimals (4.9, 4.92, 5.0); a string is drawn as given. `null`, `undefined` or `''` means no rating yet, and `newLabel` is drawn instead." },
        { name: 'count', type: 'number | string', optional: true, description: 'The number of reviews. A string is drawn as given ("1.2k").' },
        { name: 'countStyle', type: 'RatingCountStyle', options: ['parenthesis', 'reviews'], optional: true, description: 'Default `parenthesis`.' },
        { name: 'reviewsLabel', type: 'string', optional: true, description: 'The word after the count in the `reviews` style and in the accessible name. Default `"reviews"`.' },
        { name: 'newLabel', type: 'string', optional: true, description: 'Drawn (and announced) when there is no rating yet. Default `"New"`.' },
        { name: 'size', type: 'RatingSize', options: ['small', 'medium'], optional: true, description: 'Default `medium`.' },
        { name: 'variant', type: 'RatingVariant', options: ['compact', 'stars'], optional: true, description: 'Default `compact` — one star. `stars` draws a row of five, filled fractionally.' },
        { name: 'color', type: 'string', optional: true, description: 'Paints the star(s) and the value — and the count, unless `countColor` is given — e.g. white over a brand-coloured hero, where text-primary and text-secondary are illegible. Default: text-primary (count text-secondary).' },
        { name: 'starColor', type: 'string', optional: true, description: 'The filled star(s) alone, e.g. a gold star beside neutral text. Default `color`.' },
        { name: 'countColor', type: 'string', optional: true, description: 'The count alone. Default `color` when given, else text-secondary.' },
        { name: 'emptyStarColor', type: 'string', optional: true, description: "`stars` variant: the unfilled part of each star. Default the theme's border colour." },
        { name: 'fillValue', type: 'number', optional: true, description: '`stars` variant: the number the stars are filled to, clamped to `0..5`, independent of the drawn `value`. Pass it with a localised `value` string (`value="4,5"` with `fillValue={4.5}`) so the text follows the locale and the fill does not depend on parsing it. Without it a string `value` is parsed (bidi marks dropped, a comma decimal accepted). Ignored by `compact` and while there is no rating (`value` empty).' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Overrides the composed accessible name ("Rated 4.92 out of 5, 128 reviews"), which is English — pass a translated sentence here.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'RatingBarProps': {
      props: [
        { name: 'label', type: 'string', optional: false, description: 'What the row measures ("Cleanliness", "5 stars"). Also the bar\'s accessible name.' },
        { name: 'value', type: 'number', optional: false, description: 'Position on the scale, `0..max`; clamped.' },
        { name: 'max', type: 'number', optional: true, description: 'The scale. Default `5`; pass `1` for a fraction.' },
        { name: 'display', type: 'string', optional: true, description: 'Text on the right ("4.9", "72%"). Omitted when not given.' },
        { name: 'labelWidth', type: 'number', optional: true, description: 'A fixed label width. Without it the label takes the free space and the bar is 96 wide (a category list); with it the bar takes the free space (a distribution).' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'RatingInputProps': {
      props: [
        { name: 'value', type: 'number | null', optional: false, description: 'The chosen rating, `1..max`, or `null` while nothing is chosen. Fully controlled — the component keeps no value of its own.' },
        { name: 'onChange', type: '(value: number) => void', optional: false, description: 'Called with the chosen rating. Never called with the value already chosen.' },
        { name: 'max', type: 'number', optional: true, description: 'How many stars. Default `5`.' },
        { name: 'size', type: 'RatingInputSize', options: ['small', 'medium', 'large'], optional: true, description: 'Default `medium`.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Disables the whole group: no press, no keyboard, dimmed.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'The NAME of what is being rated ("Overall rating", "Cleanliness").' },
        { name: 'formatStarLabel', type: '(value: number, max: number) => string', optional: true, description: 'Each star\'s own name, which is English by default (`"1 star"`, `"4 stars"`). Pass a translated formatter.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Derives `-star-<n>` for each star.' },
      ],
    },
  },
  components: [
    { name: 'Rating', propsType: 'RatingProps' },
    { name: 'RatingBar', propsType: 'RatingBarProps' },
    { name: 'RatingInput', propsType: 'RatingInputProps' },
  ],
}
