// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'route-stops',
  propTypes: {
    'RouteStopsProps': {
      props: [
        { name: 'stops', type: 'readonly RouteStop[]', optional: false, description: 'Origin first, destination last, everything else in between.' },
        { name: 'onPressStop', type: '(id: string) => void', optional: true, description: 'Makes each row pressable — an app opens its own picker from here.' },
        { name: 'onSwap', type: '() => void', optional: true, description: 'Draws the swap control. It is offered ONLY for exactly two stops: with three or more there is no single swap to make, and a control that silently meant something different at three stops is worse than no control.' },
        { name: 'onAddStop', type: '() => void', optional: true, description: 'Draws the "add a stop" button under the list.' },
        { name: 'onRemoveStop', type: '(id: string) => void', optional: true, description: 'Draws a remove affordance on every stop.' },
        { name: 'canAddStop', type: 'boolean', optional: true, description: "Disables `onAddStop`'s button — an app that caps the number of stops." },
        { name: 'density', type: 'AddressDensity', options: ['comfortable', 'compact'], optional: true, description: 'Default `comfortable`.' },
        { name: 'labels', type: 'RouteStopsLabels', optional: true },
        { name: 'addIcon', type: 'BloomIconComponent', optional: true, description: 'The glyph on the add button. Default a plus.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the list. Default `"Route stops"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'RouteStops', propsType: 'RouteStopsProps' },
  ],
}
