// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'screen',
  propTypes: {
    'ScreenProps': {
      props: [
        { name: 'header', type: 'ReactNode', optional: true },
        { name: 'active', type: 'boolean', optional: true, description: 'Disable all descendant scroll writers when a navigator retains this screen.' },
        { name: 'navigationScope', type: "'inherit' | 'shared' | 'isolated'", options: ['inherit', 'shared', 'isolated'], optional: true, description: 'inherit shell navigation motion; shared establishes a shell; isolated resets it for a modal.' },
        { name: 'documentScroll', type: 'boolean', optional: true, description: 'Web document flow: bind window scrolling automatically, reserve chrome clearance, and keep chrome sticky within this column. Explicit list bindings take priority.' },
        { name: 'bottomBar', type: 'ReactNode', optional: true },
        { name: 'primaryAction', type: 'ReactNode', optional: true, description: 'Standalone action; with navigation use BottomBar.action instead.' },
        { name: 'headerHeight', type: 'number', optional: true, description: 'Initial footprint before layout; include any safe area in custom values.' },
        { name: 'bottomBarHeight', type: 'number', optional: true },
        { name: 'contentClearance', type: 'number', optional: true, description: 'Extra visual clearance beyond the measured bottom chrome.' },
      ],
      inheritsFrom: ['ViewProps'],
    },
    'ScreenScrollViewProps': {
      props: [
        { name: 'active', type: 'boolean', optional: true, description: 'Only the focused screen/list may drive chrome.' },
        { name: 'restoration', type: 'ScrollRestorationBinding', optional: true, description: 'Existing restoration binding for this same scroll ref.' },
        { name: 'handler', type: 'ScrollHandlerProcessed | null', optional: true },
      ],
      inheritsFrom: ["Omit<ScrollViewProps, 'onScroll'>", 'RefAttributes<ScrollView>'],
    },
  },
  components: [
    { name: 'Screen', propsType: 'ScreenProps' },
    { name: 'ScreenScrollView', propsType: 'ScreenScrollViewProps' },
  ],
}
