// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'segmented-control',
  propTypes: {
    'SegmentedControl': {
      props: [
        { name: 'label', type: 'string', optional: false },
        { name: 'type', type: "'tabs' | 'radio'", options: ['tabs', 'radio'], optional: false },
        { name: 'size', type: 'SegmentedControlSize', options: ['small', 'medium', 'large'], optional: true, description: '`medium` (default); `small` and `large` step around it.' },
        { name: 'variant', type: 'SegmentedControlVariant', options: ['solid', 'plain'], optional: true, description: '`solid` (default) draws the track and sliding thumb; `plain` draws neither.' },
        { name: 'value', type: 'T', optional: false },
        { name: 'onChange', type: '(value: T) => void', optional: false },
        { name: 'children', type: 'React.ReactNode', optional: false },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'accessibilityHint', type: 'string', optional: true },
      ],
    },
    'SegmentedControlItem': {
      props: [
        { name: 'value', type: 'string', optional: false },
        { name: 'children', type: 'React.ReactNode', optional: false },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'onPress', type: '() => void', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true },
        { name: 'accessibilityHint', type: 'string', optional: true },
        { name: 'testID', type: 'string', optional: true },
        { name: 'disabled', type: "PressableProps['disabled']", optional: true },
      ],
    },
    'SegmentedControlItemText': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false },
        { name: 'style', type: 'StyleProp<TextStyle>', optional: true },
        { name: 'className', type: 'string', optional: true },
      ],
      inheritsFrom: ['{ children: React.ReactNode; style?: StyleProp<TextStyle>; } & Omit<React.Compo…'],
    },
  },
  components: [
    { name: 'SegmentedControl', propsType: 'SegmentedControl' },
    { name: 'SegmentedControlItem', propsType: 'SegmentedControlItem' },
    { name: 'SegmentedControlItemText', propsType: 'SegmentedControlItemText' },
  ],
}
