// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'select',
  propTypes: {
    'SelectProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'value', type: 'string', optional: true },
        { name: 'onValueChange', type: '(value: string) => void', optional: true },
        { name: 'disabled', type: 'boolean', optional: true },
      ],
    },
    'SelectTriggerProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'asChild', type: 'boolean', optional: true, description: "Render the single element child AS the trigger, merging the open handler and a11y props into it. Without it the children render inside Bloom's own pressable. The same escape hatch every anchored Bloom family offers." },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'label', type: 'string', optional: false },
        { name: 'className', type: 'string', optional: true, description: "Utility classes APPENDED to the part's own — never substituted for them, so a single layout class cannot strip the chrome." },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'SelectValueProps': {
      props: [
        { name: 'children', type: '(value: unknown) => React.ReactNode', optional: true, description: 'Extracts the display text from the currently-selected item. Defaults to `item => item.label`.' },
        { name: 'placeholder', type: 'string', optional: true },
        { name: 'className', type: 'string', optional: true },
        { name: 'style', type: 'TextStyle', optional: true },
      ],
    },
    'SelectIconProps': {
      props: [
        { name: 'style', type: 'TextStyle', optional: true },
      ],
    },
    'SelectContentProps<T>': {
      props: [
        { name: 'label', type: 'string', optional: true, description: 'Label displayed at the top of the selection sheet (native) or used as an ARIA label (web).' },
        { name: 'items', type: 'T[]', optional: false, description: 'The array of items to choose from.' },
        { name: 'renderItem', type: '(item: T, index: number, selectedValue?: string | null) => React.ReactElement', optional: false, description: 'Renders a single item. Use `SelectItem` inside this callback.' },
        { name: 'valueExtractor', type: '(item: T) => string', optional: true, description: 'Extracts a unique string key from an item. Defaults to `item => item.value`.' },
        { name: 'maxHeight', type: 'number', optional: true, description: 'Tallest the anchored dropdown grows before its options scroll (web only — the native sheet sizes itself). Defaults to 320.' },
        { name: 'className', type: 'string', optional: true, description: "Appended to the dropdown panel's own chrome." },
      ],
    },
    'SelectItemProps': {
      props: [
        { name: 'ref', type: 'React.Ref<View>', optional: true },
        { name: 'value', type: 'string', optional: false },
        { name: 'label', type: 'string', optional: false },
        { name: 'children', type: 'React.ReactNode', optional: false },
        { name: 'className', type: 'string', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
      ],
    },
    'SelectItemTextProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false },
        { name: 'className', type: 'string', optional: true },
        { name: 'style', type: 'TextStyle', optional: true },
      ],
    },
    'SelectItemIndicatorProps': {
      props: [
        { name: 'icon', type: 'React.ComponentType<SVGIconProps>', optional: true },
      ],
    },
    'SelectGroupProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'className', type: 'string', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
      ],
    },
    'SelectLabelProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'className', type: 'string', optional: true },
        { name: 'style', type: 'StyleProp<TextStyle>', optional: true },
      ],
    },
    'Omit<SelectScrollButtonProps, "direction">': {
      props: [
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'className', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Select', propsType: 'SelectProps' },
    { name: 'SelectTrigger', propsType: 'SelectTriggerProps' },
    { name: 'SelectValue', propsType: 'SelectValueProps' },
    { name: 'SelectIcon', propsType: 'SelectIconProps' },
    { name: 'SelectContent', propsType: 'SelectContentProps<T>' },
    { name: 'SelectItem', propsType: 'SelectItemProps' },
    { name: 'SelectItemText', propsType: 'SelectItemTextProps' },
    { name: 'SelectItemIndicator', propsType: 'SelectItemIndicatorProps' },
    { name: 'SelectSeparator' },
    { name: 'SelectGroup', propsType: 'SelectGroupProps' },
    { name: 'SelectLabel', propsType: 'SelectLabelProps' },
    { name: 'SelectScrollUpButton', propsType: 'Omit<SelectScrollButtonProps, "direction">' },
    { name: 'SelectScrollDownButton', propsType: 'Omit<SelectScrollButtonProps, "direction">' },
  ],
}
