// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'shipment-request',
  propTypes: {
    'ShipmentLoadPickerProps': {
      props: [
        { name: 'value', type: 'ShipmentLoad', optional: false, description: 'The load. Fully controlled — the picker keeps no value of its own.' },
        { name: 'onValueChange', type: '(value: ShipmentLoad) => void', optional: false, description: 'Called with the WHOLE next load, never a patch.' },
        { name: 'kinds', type: 'readonly ShipmentLoadKindOption[]', optional: true, description: 'The kinds, in the order they are drawn. Default SHIPMENT_LOAD_KINDS .' },
        { name: 'sizes', type: 'readonly ShipmentLoadSizeOption[]', optional: true, description: 'The sizes. Default SHIPMENT_LOAD_SIZES .' },
        { name: 'notes', type: 'boolean', optional: true, description: 'Draws the notes field. Default `false`.' },
        { name: 'maxQuantity', type: 'number', optional: true, description: 'The most the stepper goes to. Default `20`.' },
        { name: 'errors', type: 'ShipmentLoadErrors', optional: true },
        { name: 'labels', type: 'ShipmentLoadPickerLabels', optional: true },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'ShipmentOptionsListProps': {
      props: [
        { name: 'extras', type: 'readonly ShipmentExtra[]', optional: true, description: 'The independent extras, as switch rows.' },
        { name: 'selectedExtras', type: 'readonly string[]', optional: true, description: 'The keys of the extras that are on.' },
        { name: 'onExtrasChange', type: '(keys: string[]) => void', optional: true },
        { name: 'accessOptions', type: 'readonly ShipmentAccessOption[]', optional: true, description: 'The access answers — a single choice, because one of them is true.' },
        { name: 'access', type: 'ShipmentAccess | null', options: ['ground', 'stairs', 'lift'], optional: true },
        { name: 'onAccessChange', type: '(access: ShipmentAccess) => void', optional: true },
        { name: 'windows', type: 'readonly ShipmentTimeWindow[]', optional: true, description: 'The collection windows — a single choice.' },
        { name: 'window', type: 'string | null', optional: true },
        { name: 'onWindowChange', type: '(id: string) => void', optional: true },
        { name: 'labels', type: 'ShipmentOptionsLabels', optional: true },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'ShipmentRequestFormProps': {
      props: [
        { name: 'route', type: 'RouteStopsProps', optional: false, description: 'The pickup and the drop-off, handed to `RouteStops` UNCHANGED.' },
        { name: 'load', type: 'ShipmentLoad', optional: false, description: 'The load section.' },
        { name: 'onLoadChange', type: '(load: ShipmentLoad) => void', optional: false },
        { name: 'loadProps', type: "Omit<ShipmentLoadPickerProps, 'value' | 'onValueChange' | 'style' | 'testID'>", optional: true, description: 'Everything else `ShipmentLoadPicker` takes, minus the value pair.' },
        { name: 'photos', type: "Omit<SortablePhotoGridProps, 'style' | 'testID'>", optional: true, description: 'The photos, handed to `SortablePhotoGrid` unchanged. Without it the photos section is not drawn — a job that needs no picture should not be asked for one.' },
        { name: 'options', type: "Omit<ShipmentOptionsListProps, 'style' | 'testID'>", optional: true, description: 'The options section. Without it the section is not drawn.' },
        { name: 'price', type: "Omit<PriceSummaryProps, 'style' | 'testID'>", optional: true, description: 'The running price, handed to `PriceSummary` unchanged. It sits last, so the options above it and the number they move are on the same screen.' },
        { name: 'footer', type: 'ReactNode', optional: true, description: 'The submit row, drawn under the last section with no divider over it.' },
        { name: 'labels', type: 'ShipmentRequestFormLabels', optional: true },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Dims and stops every control in the form.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the form. Default `"Shipment request"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'ShipmentLoadPicker', propsType: 'ShipmentLoadPickerProps' },
    { name: 'ShipmentOptionsList', propsType: 'ShipmentOptionsListProps' },
    { name: 'ShipmentRequestForm', propsType: 'ShipmentRequestFormProps' },
  ],
}
