// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'sidebar',
  propTypes: {
    'SidebarProps': {
      props: [
        { name: 'variant', type: 'SidebarVariant', options: ['panel', 'rail'], optional: true, description: 'Defaults to `panel`.' },
        { name: 'items', type: 'SidebarNavItem[]', optional: true, description: 'Primary navigation rows.' },
        { name: 'secondaryItems', type: 'SidebarNavItem[]', optional: true, description: 'Rows pinned to the bottom above the team card (Support, Settings).' },
        { name: 'selected', type: 'string', optional: true, description: 'Key of the selected row.' },
        { name: 'onNavigate', type: '(item: SidebarNavItem) => void', optional: true, description: "Called when a row with `href` is pressed. When provided on web, the browser's own navigation is prevented, so a router can take over." },
        { name: 'collapsed', type: 'boolean', optional: true, description: 'Controlled collapsed state.' },
        { name: 'defaultCollapsed', type: 'boolean', optional: true },
        { name: 'onCollapsedChange', type: '(collapsed: boolean) => void', optional: true },
        { name: 'mobile', type: 'boolean', optional: true, description: 'Rendered inside a mobile drawer: always expanded, close button instead of collapse.' },
        { name: 'onClose', type: '() => void', optional: true },
        { name: 'fluid', type: 'boolean', optional: true, description: 'Expanded width fills the container instead of 260px (collapsed stays 60).' },
        { name: 'flat', type: 'boolean', optional: true, description: 'Removes the floating panel treatment (a sidebar revealed beneath mobile content).' },
        { name: 'showThemeToggle', type: 'boolean', optional: true, description: 'Shows `ThemeToggle` above the secondary rows. Defaults to true.' },
        { name: 'showSearch', type: 'boolean', optional: true, description: 'Quick search over the rows. Defaults to true.' },
        { name: 'searchShortcutLabel', type: 'string', optional: true, description: 'Shortcut hint on the quick-search button. Defaults to "⌘L".' },
        { name: 'searchShortcut', type: 'boolean', optional: true, description: 'Binds ⌘L / Ctrl+L on web. Defaults to true.' },
        { name: 'searchLabel', type: 'string', optional: true },
        { name: 'searchPlaceholder', type: 'string', optional: true },
        { name: 'noResultsLabel', type: 'string', optional: true },
        { name: 'account', type: 'SidebarAccount', optional: true },
        { name: 'team', type: 'SidebarTeam', optional: true },
        { name: 'tree', type: 'SidebarTree', optional: true, description: 'A labelled tree of expandable folders under the primary rows (the AI chat\'s "Repositories"). Quick search filters it too. With a tree, the header and search stay put and only the rows scroll. Hidden while collapsed.' },
        { name: 'selectedTreeItem', type: 'string', optional: true, description: 'Key of the selected tree row.' },
        { name: 'onTreeItemPress', type: '(item: SidebarTreeItem, folder: SidebarTreeFolder) => void', optional: true },
        { name: 'plan', type: 'SidebarPlan', optional: true, description: 'The plan card at the foot of the rail, in place of the team card.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'SidebarFolderProps': {
      props: [
        { name: 'folder', type: 'SidebarTreeFolder', optional: false },
        { name: 'open', type: 'boolean', optional: true, description: 'Controlled expansion.' },
        { name: 'onOpenChange', type: '(open: boolean) => void', optional: true },
        { name: 'forceOpen', type: 'boolean', optional: true, description: 'Hold the folder open regardless (a search is filtering it).' },
        { name: 'selectedItem', type: 'string', optional: true },
        { name: 'onItemPress', type: '(item: SidebarTreeItem, folder: SidebarTreeFolder) => void', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'SidebarItemProps': {
      props: [
        { name: 'icon', type: 'SidebarIcon', optional: false },
        { name: 'label', type: 'string', optional: false },
        { name: 'href', type: 'string', optional: true },
        { name: 'badge', type: 'ReactNode', optional: true },
        { name: 'selected', type: 'boolean', optional: true },
        { name: 'collapsed', type: 'boolean', optional: true, description: 'Icon-only 36px square (the collapsed rail).' },
        { name: 'onPress', type: '() => void', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'SidebarPlanCardProps': {
      props: [
        { name: 'plan', type: 'SidebarPlan', optional: false },
        { name: 'collapsed', type: 'boolean', optional: true, description: 'The 36px avatar-only form for a collapsed rail.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Repaints the card (the flat variant sits it on the panel colour).' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'SidebarRailItemProps': {
      props: [
        { name: 'icon', type: 'SidebarIcon', optional: false },
        { name: 'activeIcon', type: 'SidebarIcon', optional: true, description: 'The glyph while selected (e.g. the filled icon); defaults to `icon`.' },
        { name: 'label', type: 'string', optional: false },
        { name: 'href', type: 'string', optional: true },
        { name: 'badge', type: 'ReactNode', optional: true, description: "Sits over the indicator's top-right corner." },
        { name: 'selected', type: 'boolean', optional: true },
        { name: 'onPress', type: '() => void', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'SidebarTeamMenuProps': {
      props: [
        { name: 'team', type: 'SidebarTeam', optional: false },
        { name: 'collapsed', type: 'boolean', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Repaints the expanded card (the flat mobile variant).' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'SidebarAccountMenuContent': {
      props: [
        { name: 'account', type: 'SidebarAccount', optional: false },
        { name: 'onSelect', type: '() => void', optional: false },
      ],
    },
    'SidebarUserMenuProps': {
      props: [
        { name: 'account', type: 'SidebarAccount', optional: false },
        { name: 'collapsed', type: 'boolean', optional: true },
        { name: 'suppressHover', type: 'boolean', optional: true, description: 'Suppresses the hover pill until the pointer next leaves (set after expanding).' },
        { name: 'onHoverSuppressionEnd', type: '() => void', optional: true },
        { name: 'avatarBackground', type: 'string', optional: true, description: 'Background of the 32px avatar (the flat mobile variant repaints it).' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Sidebar', propsType: 'SidebarProps' },
    { name: 'SidebarFolder', propsType: 'SidebarFolderProps' },
    { name: 'SidebarItem', propsType: 'SidebarItemProps' },
    { name: 'SidebarPlanCard', propsType: 'SidebarPlanCardProps' },
    { name: 'SidebarRailItem', propsType: 'SidebarRailItemProps' },
    { name: 'SidebarTeamMenu', propsType: 'SidebarTeamMenuProps' },
    { name: 'SidebarAccountMenuContent', propsType: 'SidebarAccountMenuContent' },
    { name: 'SidebarUserMenu', propsType: 'SidebarUserMenuProps' },
  ],
}
