// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'skeleton',
  propTypes: {
    'Text': {
      props: [
        { name: 'style', type: 'TextStyle | TextStyle[]', optional: true },
        { name: 'blend', type: 'boolean', optional: true },
      ],
    },
    'Circle': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'size', type: 'number', optional: false },
        { name: 'blend', type: 'boolean', optional: true },
        { name: 'style', type: 'ViewStyle | ViewStyle[]', optional: true },
      ],
    },
    'Pill': {
      props: [
        { name: 'size', type: 'number', optional: false },
        { name: 'blend', type: 'boolean', optional: true },
        { name: 'style', type: 'ViewStyle | ViewStyle[]', optional: true },
      ],
    },
    'Box': {
      props: [
        { name: 'width', type: 'DimensionValue', optional: true, description: 'Width as a number, percentage string, or any valid RN dimension.' },
        { name: 'height', type: 'DimensionValue', optional: true, description: 'Height as a number, percentage string, or any valid RN dimension.' },
        { name: 'borderRadius', type: "ViewStyle['borderRadius']", optional: true, description: 'Corner radius — number or percentage string. Defaults to 8. Pass 0 for sharp corners.' },
        { name: 'blend', type: 'boolean', optional: true, description: 'When true, dampens shimmer opacity (use for nested skeletons).' },
        { name: 'style', type: 'ViewStyle | ViewStyle[]', optional: true },
      ],
    },
    'Col': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'style', type: 'ViewStyle | ViewStyle[]', optional: true },
      ],
    },
  },
  components: [
    { name: 'Text', propsType: 'Text' },
    { name: 'Circle', propsType: 'Circle' },
    { name: 'Pill', propsType: 'Pill' },
    { name: 'Box', propsType: 'Box' },
    { name: 'Col', propsType: 'Col' },
    { name: 'Row', propsType: 'Col' },
  ],
}
