// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'slider',
  propTypes: {
    'SliderProps': {
      props: [
        { name: 'value', type: 'number', optional: false, description: 'Current value (controlled).' },
        { name: 'onValueChange', type: '(value: number) => void', optional: false, description: 'Fired continuously as the user drags / steps the thumb.' },
        { name: 'onSlidingComplete', type: '(value: number) => void', optional: true, description: 'Fired once when the drag gesture ends.' },
        { name: 'min', type: 'number', optional: true, description: 'Minimum value. Defaults to `0`.' },
        { name: 'max', type: 'number', optional: true, description: 'Maximum value. Defaults to `100`.' },
        { name: 'step', type: 'number', optional: true, description: 'Step granularity. Defaults to `1`. Use a fractional step for fine control.' },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'trackHeight', type: 'number', optional: true, description: 'Track thickness in px. Defaults to `4`.' },
        { name: 'thumbSize', type: 'number', optional: true, description: 'Thumb diameter in px. Defaults to `20`.' },
        { name: 'minimumTrackTintColor', type: 'string', optional: true, description: 'Override the filled-track color. Defaults to the theme primary.' },
        { name: 'maximumTrackTintColor', type: 'string', optional: true, description: 'Override the unfilled-track color. Defaults to the theme border.' },
        { name: 'thumbTintColor', type: 'string', optional: true, description: 'Override the thumb color. Defaults to the theme primary.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: "The slider's accessible NAME — what the value applies to." },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Slider', propsType: 'SliderProps' },
  ],
}
