// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'sortable-media',
  propTypes: {
    'SortablePhotoGridProps': {
      props: [
        { name: 'photos', type: 'ReadonlyArray<SortablePhoto>', optional: false, description: 'The photos, in order. The first is the cover.' },
        { name: 'onReorder', type: '(photos: SortablePhoto[]) => void', optional: false, description: 'Called with the whole list in its new order after a drag or a move button.' },
        { name: 'onRemove', type: '(id: string) => void', optional: true, description: "Draws each photo's remove button. Called with the photo's id." },
        { name: 'onRetry', type: '(id: string) => void', optional: true, description: "Draws the retry button on a failed photo. Called with the photo's id." },
        { name: 'onAdd', type: '() => void', optional: true, description: "Draws the add tile after the photos; open the app's picker here." },
        { name: 'maxPhotos', type: 'number', optional: true, description: 'Hides the add tile once this many photos are in the list.' },
        { name: 'addHint', type: 'string', optional: true, description: 'A line under "Add photos" on the add tile ("JPG or PNG, up to 20 MB").' },
        { name: 'columns', type: 'number', optional: true, description: 'A fixed column count. Default: 4 from 640 wide, 3 below.' },
        { name: 'photoVariant', type: 'string', optional: true, description: 'The `ImageResolver` rendition for an id `uri`.' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Stops reordering, removing and adding.' },
        { name: 'labels', type: 'Partial<SortablePhotoGridLabels>', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the grid. Default `"Photos"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'SortablePhotoGrid', propsType: 'SortablePhotoGridProps' },
  ],
}
