// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'sticker',
  propTypes: {
    'StickerProps': {
      props: [
        { name: 'animation', type: 'string', optional: true, description: 'URL of the Lottie animation (JSON or `.lottie`). Omit it for a still sticker; the `fallback` is then the sticker.' },
        { name: 'fallback', type: 'MessageMediaSource', optional: false, description: 'The still image of the same sticker. Shown while the animation loads, when it cannot play (no Lottie player installed, the file failed), and always when the person asked for reduced motion.' },
        { name: 'size', type: 'number', optional: true, description: 'Square edge. Default 128.' },
        { name: 'loop', type: 'boolean', optional: true, description: 'Default true.' },
        { name: 'paused', type: 'boolean', optional: true, description: 'Hold the current frame — e.g. while the sticker is scrolled out of view.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'A sticker IS its meaning; with no name it announces "Sticker" and conveys nothing. Pass what the pack author gave it — its emoji or its word.' },
        { name: 'decorative', type: 'boolean', optional: true, description: 'Hide it from assistive technology because its container already names it — `StickerMessage` does, on its pressable. Default false.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Sticker', propsType: 'StickerProps' },
  ],
}
