// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'subtle-hover',
  propTypes: {
    'SubtleHoverProps': {
      props: [
        { name: 'active', type: 'boolean', optional: true, description: 'JS-driven visibility for a coordinated highlight — e.g. every post of one thread lighting up together. When omitted, the wash instead follows CSS `group-hover` on web with ZERO React state: the parent element must carry `className="group"`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Extra style merged last — e.g. `borderRadius` to match the parent.' },
        { name: 'native', type: 'boolean', optional: true, description: 'Render on native too (default `false`). Hover is a web pointer affordance, so the CSS `group-hover` mode is web-only; native only shows the wash in the JS `active` mode, and only when this is set.' },
      ],
    },
  },
  components: [
    { name: 'SubtleHover', propsType: 'SubtleHoverProps' },
  ],
}
