// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'switch',
  propTypes: {
    'SwitchProps': {
      props: [
        { name: 'checked', type: 'boolean', optional: true, description: 'Current on/off state' },
        { name: 'defaultChecked', type: 'boolean', optional: true, description: 'Initial state for an uncontrolled switch.' },
        { name: 'onCheckedChange', type: '(checked: boolean) => void', optional: true, description: 'Called when the user toggles the switch' },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Whether the switch is disabled' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Container style' },
        { name: 'size', type: 'BloomSize', options: ['xs', 'sm', 'md', 'lg'], optional: true, description: 'Size variant' },
        { name: 'tone', type: 'BloomTone', options: ['neutral', 'accent', 'support', 'action', 'success', 'warning', 'danger', 'info'], optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: "The switch's accessible NAME, and the only way to give it one." },
        { name: 'nativeID', type: 'string', optional: true, description: "The switch's id. Inside a `Field` the field supplies one, so the label's `htmlFor` points at the control on web." },
        { name: 'testID', type: 'string', optional: true },
      ],
      inheritsFrom: ['RefAttributes<View>'],
    },
  },
  components: [
    { name: 'Switch', propsType: 'SwitchProps' },
  ],
}
