// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'tab-bar',
  propTypes: {
    'TabBarProps': {
      props: [
        { name: 'activeIndex', type: 'number', optional: true, description: 'CONTROLLED path — the index of the focused tab. The bar owns the sliding highlight and springs it here whenever this changes. Use this when there is no router in play; the router adapter uses the per-button `isFocused` path instead (see TabBarButtonProps.isFocused) and must NOT pass this.' },
        { name: 'onIndexChange', type: '(index: number) => void', optional: true, description: 'Called with the chosen index when a tab is picked by tap, by scrub release, or by keyboard/assistive-technology activation of a `TabBarButton`.' },
        { name: 'onIndexLongPress', type: '(index: number) => void', optional: true, description: 'Called with the index under the finger when a tab is pressed and HELD.' },
        { name: 'theme', type: 'Partial<TabBarTheme>', optional: true, description: "Partial override of the theme resolved from Bloom's color tokens." },
        { name: 'haptics', type: 'boolean', optional: true, description: "Haptic tick as the scrub crosses tab boundaries. Defaults to `true`. Runs through Bloom's `useHaptics`, so it is already a no-op on web and when the optional `expo-haptics` peer is absent." },
        { name: 'blur', type: 'boolean | { intensity?: number; }', optional: true, description: 'The progressive blur rising from the bottom edge of the screen behind the pill. Defaults to `true`; `{ intensity }` tunes its strength.' },
        { name: 'maxWidth', type: 'number', optional: true, description: 'Maximum width of the pill, in points. No default — omit it and the bar spans the window exactly as it always has.' },
      ],
      inheritsFrom: ['ViewProps'],
    },
    'TabBarButtonProps': {
      props: [
        { name: 'item', type: 'TabBarItem', optional: false },
        { name: 'index', type: 'number', optional: false, description: 'Position in the bar. Drives the highlight target and the glyph crossfade.' },
        { name: 'isFocused', type: 'boolean', optional: true, description: "FOCUS-DRIVEN path — supplied by the `expo-router` adapter from the tab trigger's own focus state. When present it wins over the bar's `activeIndex`, and this button (not the bar) drives the highlight, which is what makes programmatic navigation, deep links and back gestures move it." },
      ],
      inheritsFrom: ['PressableProps'],
    },
    'TabBarMinimizeProvider': {
      props: [],
      inheritsFrom: ['PropsWithChildren'],
    },
  },
  components: [
    { name: 'TabBar', propsType: 'TabBarProps' },
    { name: 'TabBarButton', propsType: 'TabBarButtonProps' },
    { name: 'TabBarMinimizeProvider', propsType: 'TabBarMinimizeProvider' },
  ],
}
