// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'tabs',
  propTypes: {
    'TabsProps': {
      props: [
        { name: 'value', type: 'string', optional: true, description: 'The currently selected tab value — the CONTROLLED path, where the bar owns the underline and reports presses through TabsProps.onValueChange.' },
        { name: 'onValueChange', type: '(value: string) => void', optional: true, description: 'Called when a tab is selected. Controlled path only.' },
        { name: 'hasSelection', type: 'boolean', optional: true, description: 'Focus-driven path only: whether ANY trigger is currently focused.' },
        { name: 'variant', type: 'TabsVariant', options: ['underline', 'filled', 'outlined'], optional: true, description: 'Visual variant for the tab bar.' },
        { name: 'fullWidth', type: 'boolean', optional: true, description: 'When true, the tab bar spans the full container width and each trigger takes an equal share of it (edge to edge), instead of the default content-sized, horizontally scrollable layout. Best for a small, fixed set of tabs (e.g. 2–3). Defaults to `false`.' },
        { name: 'children', type: 'React.ReactNode', optional: false, description: 'The tab items. Must be TabsTrigger components.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
      inheritsFrom: ['RefAttributes<TabsDragController>'],
    },
    'TabsTriggerProps': {
      props: [
        { name: 'value', type: 'string', optional: false, description: 'Unique value identifying this tab.' },
        { name: 'label', type: 'string', optional: false, description: 'Tab label text.' },
        { name: 'icon', type: 'React.ReactNode', optional: true, description: 'Icon rendered before the label.' },
        { name: 'count', type: 'number', optional: true, description: "Optional tally rendered as a small muted number beside the label. Omitted (or `0`) renders nothing. The underline tracks the trigger's measured width, so a count never changes where it sits." },
        { name: 'isFocused', type: 'boolean', optional: true, description: "Whether the ROUTER considers this tab focused — the focus-driven path. Supplying it makes this trigger, not the bar, the writer of the shared underline, and suppresses TabsProps.onValueChange on press because navigation is then the caller's job. Leave it `undefined` on the controlled path." },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Whether this tab is disabled.' },
        { name: 'onPress', type: '() => void', optional: true, description: 'Extra press handler. Runs on both paths, before any selection is reported.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'textStyle', type: 'StyleProp<TextStyle>', optional: true },
      ],
    },
    'TabsContentProps': {
      props: [
        { name: 'value', type: 'string', optional: false, description: 'The tab value this panel corresponds to.' },
        { name: 'children', type: 'React.ReactNode', optional: false, description: 'Panel content.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
      ],
    },
  },
  components: [
    { name: 'Tabs', propsType: 'TabsProps' },
    { name: 'TabsTrigger', propsType: 'TabsTriggerProps' },
    { name: 'TabsContent', propsType: 'TabsContentProps' },
  ],
}
