// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'text-field',
  propTypes: {
    'TextFieldProps': {
      props: [
        { name: 'isInvalid', type: 'boolean', optional: true },
        { name: 'radius', type: 'number', optional: true },
        { name: 'style', type: 'ViewStyle | ViewStyle[]', optional: true },
      ],
      inheritsFrom: ['React.PropsWithChildren<…>'],
    },
    'TextFieldInputProps': {
      props: [
        { name: 'label', type: 'string', optional: false },
        { name: 'value', type: 'string', optional: true },
        { name: 'onChangeText', type: '(value: string) => void', optional: true },
        { name: 'isInvalid', type: 'boolean', optional: true },
        { name: 'inputRef', type: 'React.RefObject<TextInput | null> | React.ForwardedRef<TextInput>', optional: true },
        { name: 'placeholder', type: 'string | null', optional: true },
        { name: 'floatingLabel', type: 'boolean', optional: true, description: 'Render the field with a Material-style floating label. When `true`, the label sits inside the field as the placeholder while the input is empty AND unfocused; on focus OR when a value is present it animates up to a small caption pinned to the top of the field and the typed value shows below it. Opt-in — the default (`false`) keeps the existing chrome where the label lives above the field (`TextFieldLabel`) and the placeholder is plain.' },
      ],
      inheritsFrom: ["Omit<TextInputProps, 'value' | 'onChangeText' | 'placeholder'>"],
    },
    'PropsWithChildren<{ nativeID?: string | undefined; }>': {
      props: [
        { name: 'nativeID', type: 'string', optional: true },
      ],
      inheritsFrom: ['React.PropsWithChildren<{ nativeID?: string; }>'],
    },
    'TextFieldIcon': {
      props: [
        { name: 'icon', type: 'React.ComponentType<SVGIconProps>', optional: false },
      ],
    },
    'PropsWithChildren<…>': {
      props: [
        { name: 'style', type: 'TextStyle | TextStyle[]', optional: true },
        { name: 'label', type: 'string', optional: false },
        { name: 'accessibilityHint', type: "AccessibilityProps['accessibilityHint']", optional: true },
      ],
      inheritsFrom: ['React.PropsWithChildren<…>'],
    },
    'TextFieldGhost': {
      props: [
        { name: 'children', type: 'string', optional: false },
        { name: 'value', type: 'string', optional: false },
      ],
    },
  },
  components: [
    { name: 'TextField', propsType: 'TextFieldProps' },
    { name: 'TextFieldInput', propsType: 'TextFieldInputProps' },
    { name: 'TextFieldLabel', propsType: 'PropsWithChildren<{ nativeID?: string | undefined; }>' },
    { name: 'TextFieldIcon', propsType: 'TextFieldIcon' },
    { name: 'TextFieldSuffix', propsType: 'PropsWithChildren<…>' },
    { name: 'TextFieldGhost', propsType: 'TextFieldGhost' },
  ],
}
