// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'textarea',
  propTypes: {
    'TextareaProps': {
      props: [
        { name: 'style', type: 'ViewStyle | ViewStyle[]', optional: true },
        { name: 'label', type: 'string', optional: true, description: "Visible label above the field, and the input's accessible name. When omitted, pass `accessibilityLabel` (or at least a `placeholder`, which is used as the fallback name)." },
        { name: 'hint', type: 'string', optional: true, description: 'Caption under the field; painted in the error colour when invalid.' },
        { name: 'placeholder', type: 'string', optional: true },
        { name: 'value', type: 'string', optional: true },
        { name: 'defaultValue', type: 'string', optional: true },
        { name: 'onValueChange', type: '(value: string) => void', optional: true },
        { name: 'onChangeText', type: '(value: string) => void', optional: true },
        { name: 'size', type: 'TextFieldSize', options: ['medium', 'sm', 'md', 'lg', 'xs', 'small'], optional: true, description: 'Two insets: `md` (default) or `sm`.' },
        { name: 'rows', type: 'number', optional: true, description: 'Resting height in lines, default `3`. Also the floor when `autoResize` is on.' },
        { name: 'autoResize', type: 'boolean', optional: true, description: 'Grow with the content instead of scrolling at `rows`.' },
        { name: 'maxRows', type: 'number', optional: true, description: 'Ceiling for `autoResize`, in lines. Past it the field scrolls.' },
        { name: 'resize', type: 'TextareaResize', options: ['none', 'vertical'], optional: true, description: "Web's native grab handle, default `vertical`. Forced `none` under `autoResize`." },
        { name: 'maxLength', type: 'number', optional: true, description: 'Hard character limit.' },
        { name: 'showCount', type: 'boolean', optional: true, description: 'Show the character counter under the field (`12/280` with `maxLength`).' },
        { name: 'invalid', type: 'boolean', optional: true },
        { name: 'isInvalid', type: 'boolean', optional: true },
        { name: 'disabled', type: 'boolean', optional: true },
        { name: 'required', type: 'boolean', optional: true, description: 'Append the required asterisk to the label.' },
        { name: 'tooltip', type: 'boolean', optional: true, description: 'Show the info glyph after the label.' },
        { name: 'inputStyle', type: "TextStyleProp['style']", optional: true, description: 'Style for the `TextInput` itself (the outer `style` is the whole field).' },
        { name: 'inputRef', type: 'React.RefObject<TextInput | null> | React.ForwardedRef<TextInput>', optional: true },
      ],
      inheritsFrom: ['Omit<…>'],
    },
  },
  components: [
    { name: 'Textarea', propsType: 'TextareaProps' },
  ],
}
