// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'theme',
  propTypes: {
    'BloomThemeProviderProps': {
      props: [
        { name: 'mode', type: 'ThemeMode', options: ['light', 'dark', 'system', 'adaptive'], optional: true, description: "Controlled mode. Omit to use Bloom's internal state (with optional persistence)." },
        { name: 'colorPreset', type: 'AppColorName', options: ['sky', 'teal', 'blue', 'green', 'yellow', 'red', 'purple', 'pink', 'orange', 'mint', 'oxy', 'faircoin', 'pumpkin', 'gray', 'brown', 'peach', 'rose', 'mono', 'grove', 'ember', 'merlot', 'cobalt', 'jade', 'pine', 'olive', 'lagoon', 'navy', 'azure', 'violet', 'lavender', 'plum', 'cherry', 'chocolate', 'graphite', 'forest-fire', 'malachite-rush', 'moss-voltage', 'viridian-orbit', 'acid-canopy', 'pacific-flare', 'reef-pulse', 'electric-tide', 'arctic-signal', 'ultramarine-gold', 'midnight-citrus', 'persimmon-wave', 'solar-flux', 'paprika-current', 'crimson-spark', 'flamenco-sun', 'saffron-depth', 'clay-current', 'bronze-neon', 'copper-field', 'umber-signal', 'amethyst-current', 'ruby-current', 'orchid-flare', 'garnet-acid', 'indigo-ember', 'raspberry-gold', 'ink-orange', 'charcoal-lime', 'pewter-current'], optional: true, description: "Controlled color preset. Omit to use Bloom's internal state." },
        { name: 'defaultMode', type: 'ThemeMode', options: ['light', 'dark', 'system', 'adaptive'], optional: true, description: 'Initial mode when uncontrolled and nothing is persisted yet.' },
        { name: 'defaultColorPreset', type: 'AppColorName', options: ['sky', 'teal', 'blue', 'green', 'yellow', 'red', 'purple', 'pink', 'orange', 'mint', 'oxy', 'faircoin', 'pumpkin', 'gray', 'brown', 'peach', 'rose', 'mono', 'grove', 'ember', 'merlot', 'cobalt', 'jade', 'pine', 'olive', 'lagoon', 'navy', 'azure', 'violet', 'lavender', 'plum', 'cherry', 'chocolate', 'graphite', 'forest-fire', 'malachite-rush', 'moss-voltage', 'viridian-orbit', 'acid-canopy', 'pacific-flare', 'reef-pulse', 'electric-tide', 'arctic-signal', 'ultramarine-gold', 'midnight-citrus', 'persimmon-wave', 'solar-flux', 'paprika-current', 'crimson-spark', 'flamenco-sun', 'saffron-depth', 'clay-current', 'bronze-neon', 'copper-field', 'umber-signal', 'amethyst-current', 'ruby-current', 'orchid-flare', 'garnet-acid', 'indigo-ember', 'raspberry-gold', 'ink-orange', 'charcoal-lime', 'pewter-current'], optional: true, description: 'Initial color preset when uncontrolled and nothing is persisted yet.' },
        { name: 'onModeChange', type: '(mode: ThemeMode) => void', optional: true },
        { name: 'onColorPresetChange', type: '(preset: AppColorName) => void', optional: true },
        { name: 'persistKey', type: 'string', optional: true, description: "Persist mode + preset under this storage key. Bloom becomes the single source of truth — apps don't need their own theme store. Has no effect without `storage`." },
        { name: 'storage', type: 'BloomThemeStorage', optional: true, description: 'Storage adapter paired with `persistKey`. Use `webLocalStorage` on web, or pass an `AsyncStorage`-compatible adapter on native.' },
        { name: 'awaitHydration', type: 'boolean', optional: true, description: "Block rendering until persisted state has been read. Default `true` when both `persistKey` and `storage` are provided, ensuring native apps don't flash the default palette. Web hydrates synchronously so this is a no-op there." },
        { name: 'onHydrating', type: 'React.ReactNode', optional: true, description: 'Rendered while async hydration is pending.' },
        { name: 'fonts', type: 'boolean', optional: true, description: "Load and inject Bloom's font system. Default `true`." },
        { name: 'onFontsLoading', type: 'React.ReactNode', optional: true, description: 'Rendered while native fonts load. Ignored on web.' },
        { name: 'nativeWrapperStyle', type: 'StyleProp<ViewStyle>', optional: true, description: "Style applied to the native `<View>` wrapper that carries the preset's CSS vars. Defaults to `{ flex: 1 }`. Ignored on web (the provider writes vars to `document.documentElement` instead of using a wrapper)." },
        { name: 'secondaryColor', type: 'string', optional: true, description: "Optional app-wide secondary-accent colour, `#rrggbb`. When set, the whole theme's secondary family (`--secondary`, `bg-secondary`, `colors.secondary`, plus the container / on-colour roles) is PINNED to this brand colour instead of the derived hue-rotation of the active preset's seed — for a brand with a distinct accent (e.g. blue primary + yellow secondary). M3 role tones still apply. Omit to keep the preset's derived accent." },
        { name: 'tertiaryColor', type: 'string', optional: true, description: 'Optional app-wide tertiary-accent colour, `#rrggbb`. Same semantics as BloomThemeProviderProps.secondaryColor for the tertiary family.' },
        { name: 'seed', type: 'string', optional: true, description: "Optional DYNAMIC seed colour, `#rrggbb`. When set, the WHOLE app themes from this seed instead of the named `colorPreset` (via the same colour engine the preset path uses) — driving app-wide dynamic theming (e.g. tint everything to the artwork the user is viewing/hovering). `secondaryColor`/`tertiaryColor` act as this seed's pinned secondary/tertiary accents (e.g. the 2nd/3rd colours extracted from that artwork). Omit / pass `undefined` to fall back to the preset — so clearing it restores the app's default theme." },
        { name: 'children', type: 'React.ReactNode', optional: false },
      ],
    },
    'BloomColorScopeProps': {
      props: [
        { name: 'colorPreset', type: 'AppColorName | undefined', options: ['sky', 'teal', 'blue', 'green', 'yellow', 'red', 'purple', 'pink', 'orange', 'mint', 'oxy', 'faircoin', 'pumpkin', 'gray', 'brown', 'peach', 'rose', 'mono', 'grove', 'ember', 'merlot', 'cobalt', 'jade', 'pine', 'olive', 'lagoon', 'navy', 'azure', 'violet', 'lavender', 'plum', 'cherry', 'chocolate', 'graphite', 'forest-fire', 'malachite-rush', 'moss-voltage', 'viridian-orbit', 'acid-canopy', 'pacific-flare', 'reef-pulse', 'electric-tide', 'arctic-signal', 'ultramarine-gold', 'midnight-citrus', 'persimmon-wave', 'solar-flux', 'paprika-current', 'crimson-spark', 'flamenco-sun', 'saffron-depth', 'clay-current', 'bronze-neon', 'copper-field', 'umber-signal', 'amethyst-current', 'ruby-current', 'orchid-flare', 'garnet-acid', 'indigo-ember', 'raspberry-gold', 'ink-orange', 'charcoal-lime', 'pewter-current'], optional: false, description: "Preset to apply within this subtree. When `undefined`, the scope is a no-op and children inherit the parent scope's preset unchanged." },
        { name: 'asChild', type: 'boolean', optional: true, description: "When `true`, do not render a wrapping `<div>`. The single child is cloned with the scope's CSS vars merged into its `style` prop (Radix-style)." },
        { name: 'style', type: 'React.CSSProperties', optional: true, description: 'Additional style applied to the wrapping `<div>` (or merged into the cloned child with `asChild`).' },
        { name: 'children', type: 'React.ReactNode', optional: false },
      ],
    },
    'BloomSeedScopeProps': {
      props: [
        { name: 'seed', type: 'string | undefined', optional: false, description: "The seed colour (`#rrggbb`) to derive this subtree's palette from. When `undefined`, the scope is a no-op and children inherit the parent scope unchanged — pass `undefined` to fall back to the app preset (e.g. on mouse-leave/blur when restoring the default theme)." },
        { name: 'secondarySeed', type: 'string', optional: true, description: 'Optional explicit secondary-accent seed (`#rrggbb`). Pins the secondary palette to a distinct brand/artwork colour instead of the derived rotation — e.g. pass `seedsFromImagePixels(pixels)[1]` for a richer artwork theme.' },
        { name: 'tertiarySeed', type: 'string', optional: true, description: 'Optional explicit tertiary-accent seed (`#rrggbb`). Same semantics.' },
        { name: 'variant', type: 'SchemeVariant', options: ['vivid', 'vibrant', 'expressive', 'tonalSpot', 'neutral', 'monochrome'], optional: true, description: "Tonal scheme variant. Defaults to `'vibrant'` (matches Bloom presets)." },
        { name: 'contrastLevel', type: 'number', optional: true, description: '−1 (low) … 0 (normal) … 1 (high). Defaults to 0.' },
        { name: 'asChild', type: 'boolean', optional: true, description: "When `true`, do not render a wrapping `<div>`. The single child is cloned with the scope's CSS vars merged into its `style` prop (Radix-style)." },
        { name: 'style', type: 'React.CSSProperties', optional: true, description: 'Additional style applied to the wrapping `<div>` (or merged into the cloned child with `asChild`).' },
        { name: 'children', type: 'React.ReactNode', optional: false },
      ],
    },
  },
  components: [
    { name: 'BloomThemeProvider', propsType: 'BloomThemeProviderProps' },
    { name: 'BloomColorScope', propsType: 'BloomColorScopeProps' },
    { name: 'BloomSeedScope', propsType: 'BloomSeedScopeProps' },
  ],
}
