// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'tooltip',
  propTypes: {
    'Tooltip': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false },
        { name: 'position', type: "'top' | 'bottom'", options: ['top', 'bottom'], optional: true },
        { name: 'visible', type: 'boolean', optional: false },
        { name: 'onVisibleChange', type: '(visible: boolean) => void', optional: false },
      ],
    },
    'TooltipTrigger': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false },
      ],
    },
    'TooltipContent': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: false },
        { name: 'label', type: 'string', optional: false },
      ],
    },
  },
  components: [
    { name: 'Tooltip', propsType: 'Tooltip' },
    { name: 'TooltipTrigger', propsType: 'TooltipTrigger' },
    { name: 'TooltipContent', propsType: 'TooltipContent' },
    { name: 'TooltipTextBubble', propsType: 'TooltipTrigger' },
  ],
}
