// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'typography',
  propTypes: {
    'Text': {
      props: [
        { name: 'className', type: 'string', optional: true },
      ],
      inheritsFrom: ['TextProps'],
    },
    'TextProps': {
      props: [
        { name: 'className', type: 'string', optional: true },
      ],
      inheritsFrom: ['RNTextProps'],
    },
    'BlockquoteProps': {
      props: [
        { name: 'children', type: 'React.ReactNode', optional: true },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'The container — the left rule and its indent.' },
        { name: 'textStyle', type: 'StyleProp<TextStyle>', optional: true, description: 'The quotation itself.' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'Text', propsType: 'Text' },
    { name: 'Span', propsType: 'Text' },
    { name: 'H1', propsType: 'TextProps' },
    { name: 'H2', propsType: 'TextProps' },
    { name: 'H3', propsType: 'TextProps' },
    { name: 'H4', propsType: 'TextProps' },
    { name: 'H5', propsType: 'TextProps' },
    { name: 'H6', propsType: 'TextProps' },
    { name: 'P', propsType: 'TextProps' },
    { name: 'Lead', propsType: 'TextProps' },
    { name: 'Large', propsType: 'TextProps' },
    { name: 'Small', propsType: 'TextProps' },
    { name: 'Muted', propsType: 'TextProps' },
    { name: 'Blockquote', propsType: 'BlockquoteProps' },
  ],
}
