// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'user-hover-card',
  propTypes: {
    'UserHoverCardProps': {
      props: [
        { name: 'avatar', type: 'string | null', optional: true, description: "Avatar image source. Accepts a full image URL OR a resolver-handled id (e.g. an Oxy file ID) — it is routed into Avatar 's `source` prop, so non-URL strings resolve through the consumer's ImageResolver. Null/undefined falls back to the deterministic name-based placeholder." },
        { name: 'variant', type: 'string', optional: true, description: "Rendition variant forwarded to Avatar 's `variant` prop when `avatar` is a bare file ID. Omit for the full-size rendition (the default for this larger identity avatar)." },
        { name: 'displayName', type: 'string', optional: false, description: 'Canonical, already-resolved display name (an API contract — render directly).' },
        { name: 'username', type: 'string', optional: true, description: 'Handle without the leading `@` (the component prefixes it).' },
        { name: 'bio', type: 'string', optional: true, description: 'Optional short biography; truncated to a few lines.' },
        { name: 'stats', type: 'UserHoverCardStat[]', optional: true, description: 'Optional metrics row (e.g. Following / Followers).' },
        { name: 'verified', type: 'boolean', optional: true, description: 'Whether to show the verified badge next to the display name.' },
        { name: 'onPressProfile', type: '() => void', optional: true, description: 'Makes the identity area (avatar + name + handle) pressable.' },
        { name: 'action', type: 'ReactNode', optional: true, description: "Slot for a consumer-injected action — typically the app's SDK FollowButton. Bloom does NOT implement follow logic; it only renders the card." },
        { name: 'footer', type: 'ReactNode', optional: true, description: 'Trailing content region, rendered after the stats row and spanning the full inner width — the slot for whatever this app knows about a person that Bloom does not (a contribution graph, a shared-followers strip, a mutual-friends line). Bloom adds the vertical rhythm and nothing else: no label, no divider, no clip.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true, description: 'Container style override.' },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'UserHoverCard', propsType: 'UserHoverCardProps' },
  ],
}
