// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'vehicle-picker',
  propTypes: {
    'VehiclePickerProps<T>': {
      props: [
        { name: 'value', type: 'T | null', optional: false, description: 'The chosen vehicle, or `null` while none is. Fully controlled.' },
        { name: 'onValueChange', type: '(value: T) => void', optional: false, description: 'Called with the chosen vehicle. Never called with the value already chosen.' },
        { name: 'options', type: 'readonly VehicleOption<T>[]', optional: true, description: 'The vehicles, in the order they should be read. Default VEHICLE_OPTIONS .' },
        { name: 'title', type: 'string', optional: true, description: "A heading over the list, drawn the way a search panel's pickers draw theirs — `body-semibold` over a `body-2-regular` description. Without it the caller owns the heading and the picker starts at its first option." },
        { name: 'description', type: 'string', optional: true },
        { name: 'disabled', type: 'boolean', optional: true, description: 'Dims and stops every option, whatever each one says.' },
        { name: 'labels', type: 'VehiclePickerLabels', optional: true },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'Names the group. Default `"Vehicle"` — and it matters even when `title` is drawn, because a heading beside a group is a sibling, not a label.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true, description: 'Derives `-<value>` for each option.' },
      ],
    },
  },
  components: [
    { name: 'VehiclePicker', propsType: 'VehiclePickerProps<T>' },
  ],
}
