// Generated by scripts/generate-bloom-catalog.ts. Do not edit.

import type { BloomSurfaceProps } from '../bloom-catalog'

export const props: BloomSurfaceProps = {
  subpath: 'wizard',
  propTypes: {
    'WizardFooterProps': {
      props: [
        { name: 'onBack', type: '() => void', optional: true, description: 'Called by the Back action. Omit it (the first step) to hide Back.' },
        { name: 'backLabel', type: 'string', optional: true, description: 'Default `"Back"`.' },
        { name: 'backDisabled', type: 'boolean', optional: true },
        { name: 'onNext', type: '() => void', optional: false, description: 'Called by the primary action.' },
        { name: 'nextLabel', type: 'string', optional: true, description: 'Default `"Next"`; pass `"Publish"` on the last step.' },
        { name: 'nextDisabled', type: 'boolean', optional: true },
        { name: 'loading', type: 'boolean', optional: true, description: "The primary action's own loading state: spinner, width kept, presses ignored." },
        { name: 'status', type: 'string', optional: true, description: 'A short line between the actions ("Saved a minute ago"). Hidden below 480 wide.' },
        { name: 'sticky', type: 'boolean', optional: true, description: 'Pins the bar to the bottom of its scroll container on web (`position: sticky`). Native has no sticky positioning: render the footer after the `ScrollView`, outside it, and it stays put. Default `true`.' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
    'WizardProgressProps': {
      props: [
        { name: 'steps', type: 'ReadonlyArray<WizardStep>', optional: false, description: 'Every step, in order. One bar segment each.' },
        { name: 'current', type: 'number', optional: false, description: "The current step's index, 0-based. Clamped to the steps." },
        { name: 'currentProgress', type: 'number', optional: true, description: 'How much of the current step is done, 0..1 — its segment fills this far. Default `0.5`, so the current step always reads as "under way". Pass `0` for an empty current segment, `1` once the step can be left.' },
        { name: 'formatStepCount', type: '(position: number, total: number) => string', optional: true, description: 'The count line. Default `` (position, total) => `Step ${position} of ${total}` ``.' },
        { name: 'hideTitle', type: 'boolean', optional: true, description: 'Hides the title and description, leaving the bar and the count — for a screen whose own heading already names the step.' },
        { name: 'action', type: 'ReactNode', optional: true, description: 'Right of the count line, e.g. a "Save and exit" button.' },
        { name: 'headingLevel', type: 'number', optional: true, description: 'The heading level of the title on web. Default `1`.' },
        { name: 'accessibilityLabel', type: 'string', optional: true, description: 'The bar\'s accessible name. Default: the count line plus the title ("Step 3 of 8, Photos").' },
        { name: 'style', type: 'StyleProp<ViewStyle>', optional: true },
        { name: 'testID', type: 'string', optional: true },
      ],
    },
  },
  components: [
    { name: 'WizardFooter', propsType: 'WizardFooterProps' },
    { name: 'WizardProgress', propsType: 'WizardProgressProps' },
  ],
}
