/**
 * The shape of the generated Bloom catalog, and the one rule that turns a
 * prop into a playground control.
 *
 * The DATA is generated by `scripts/generate-bloom-catalog.ts` from the
 * installed `@oxy.so/bloom` package — its `exports` map, its README component
 * table and its shipped `.d.ts` files — and lands in two places:
 *
 *   - `bloom-catalog.generated.ts` — the index. Subpaths, categories and
 *     component names, small enough to import eagerly, plus the loader for
 *     everything below.
 *   - `bloom-catalog-props/<subpath>.ts` — one module per surface, holding
 *     that surface's props. Reached only through `loadBloomSurfaceProps`, so
 *     Vite code-splits them and a component page downloads only its own.
 *
 * Nothing in this file is derived from Bloom; nothing in those files is
 * written by hand.
 */

export interface BloomProp {
  /** Prop name exactly as declared, e.g. `variant`. */
  name: string
  /**
   * The type as Bloom spells it, e.g. `ButtonVariant` or `StyleProp<ViewStyle>`
   * — the declared text, not the resolved union, so a named type stays named.
   * An optional prop's redundant `| undefined` is stripped: `optional` carries
   * that fact once.
   */
  type: string
  /**
   * Members of the string-literal union `type` resolves to, when it is one.
   * Resolved through the alias, so `ButtonVariant` still yields its members.
   */
  options?: readonly string[]
  optional: boolean
  /** First paragraph of the prop's JSDoc, whitespace collapsed. */
  description?: string
}

/**
 * One props type, and every prop Bloom declares on it.
 *
 * A surface holds these once each and its components point at them by name,
 * because ten of Bloom's button components take the same `ButtonProps` and a
 * copy per component was a fifth of the whole catalog. Sharing it is also the
 * more truthful shape: "these ten components take the same props" is a fact a
 * component page can now state, where ten identical tables hid it.
 */
export interface BloomPropType {
  /** Props Bloom itself declares. */
  props: readonly BloomProp[]
  /**
   * The types these props reach outside Bloom, as Bloom writes them —
   * `ViewProps`, `Omit<SvgProps, "size" | "style">`, `RefAttributes<View>`.
   *
   * Their props are deliberately NOT listed: they are the platform's surface,
   * not Bloom's, and there are 3807 of them against Bloom's own 1335. A props
   * table renders the list above and a line naming these. Every prop left out
   * is attributable to a name here — the generator fails if one is not.
   */
  inheritsFrom?: readonly string[]
}

export interface BloomComponentProps {
  /** Exported name, e.g. `Button`. */
  name: string
  /**
   * Key into the surface's `propTypes` — the name Bloom gives the type, e.g.
   * `ButtonProps` or `Omit<ButtonProps, "variant">`. Absent when the component
   * declares no props and inherits none, the only case with nothing to point at.
   *
   * Bloom writes some props inline, with no name to take (its icons are
   * `ForwardRefExoticComponent<{…}>`). Those key off a component's name instead,
   * so the key is a grouping handle rather than a type a reader could look up.
   * The two are told apart without another field: a key that matches the `name`
   * of a component on the same surface is a handle. Print it as a type name only
   * when it does not.
   */
  propsType?: string
}

/** One surface's props, loaded on demand by `loadBloomSurfaceProps`. */
export interface BloomSurfaceProps {
  subpath: string
  /**
   * Every distinct props type on the surface, keyed by the name Bloom gives it.
   * Several components may share one key; that they do is the point.
   */
  propTypes: Readonly<Record<string, BloomPropType>>
  components: readonly BloomComponentProps[]
}

export interface BloomComponentEntry {
  /** Exported name, e.g. `Button`. */
  name: string
  /** First paragraph of the component's JSDoc, whitespace collapsed. */
  description?: string
}

export interface BloomSurfaceEntry {
  /** Export subpath without its leading `./`, e.g. `button`, `tabs/expo-router`. */
  subpath: string
  /** What a consumer imports from, e.g. `@oxy.so/bloom/button`. */
  importPath: string
  /** Group name from Bloom's own README component table. */
  category: string
  /**
   * Every exported component on the surface. Empty for a surface that publishes
   * only hooks, adapters or constants — `image-aspect-ratio-cache` is a real
   * component surface by category and exports no component at all.
   */
  components: readonly BloomComponentEntry[]
}

export interface BloomCategory {
  /** Group name, in the order Bloom's README lists it. */
  name: string
  /**
   * True for the groups that publish infrastructure rather than surfaces a
   * reader can look at — providers, tokens, fonts. They get no component card.
   */
  utility: boolean
}

/**
 * `text-field` -> `TextField`, `tabs/expo-router` -> `Tabs/ExpoRouter`.
 *
 * The one rule tying a Bloom subpath to the name everything else calls it by:
 * the demo file that demonstrates it (`Skeleton.tsx` for `skeleton`), the title
 * its page carries, the `<title>` its prerendered HTML ships, and the principal
 * export on 60 of the 87 surfaces. It lives beside the catalog because a page
 * and the prerender that gives that page its head must agree by construction —
 * two implementations of this would drift silently, and only a crawler would
 * ever notice. Stays one-to-one, so `tabs/expo-router` derives
 * `Tabs/ExpoRouter` and cannot claim the `tabs` demo.
 */
export function pascalPath(subpath: string): string {
  return subpath
    .split('/')
    .map((segment) =>
      segment
        .split('-')
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(''),
    )
    .join('/')
}

/** A `<BloomPlayground>` control, derived from a prop's declared type. */
export type BloomKnob =
  | { kind: 'select'; options: readonly string[] }
  | { kind: 'boolean' }
  | { kind: 'text' }
  | { kind: 'number' }

/**
 * The single mapping from a prop to the control that edits it, used by the
 * playground, the component grid and the props table alike. `null` means the
 * prop is not editable from a control — a render prop, a style object, a
 * `ReactNode`. Deriving it here rather than storing a `kind` on every prop
 * keeps one answer to "is this knobbable" instead of one per generation.
 */
export function knobFor(prop: BloomProp): BloomKnob | null {
  if (prop.options) return { kind: 'select', options: prop.options }
  if (prop.type === 'boolean') return { kind: 'boolean' }
  if (prop.type === 'string') return { kind: 'text' }
  if (prop.type === 'number') return { kind: 'number' }
  return null
}
