// Generated by scripts/generate-bloom-catalog.ts. Do not edit.
//
// Source: @oxy.so/bloom@1.0.7 — its exports map, its README component
// table and its shipped .d.ts files.
// 92 surfaces, 200 components, 156 distinct
// props types carrying 1080 props
// (3810 more reach them from outside Bloom and are named
// per component as `inheritsFrom` rather than listed).
//
// Upstream drift, reported rather than enforced:
//   Bloom's README says it publishes 88 subpath exports; its exports map has 95 (92 of them declare types).
//   5 typed surface(s) are absent from Bloom's README component table and remain visible under Uncategorized: layout, level-picker, media-flight, teleport, zoomable-media-gallery.

import type { BloomCategory, BloomSurfaceEntry } from './bloom-catalog'

/**
 * The `@oxy.so/bloom` version every component page below describes.
 *
 * The docs sidebar's version selector reads a separate typedoc sync that can
 * lag the installed package by whole majors, and a reader has no way to tell
 * which half of that disagreement they are looking at. This is the half that
 * matches what the site actually ships.
 */
export const bloomVersion = '1.0.7'

/** Bloom's component groups, in the order its README lists them. */
export const bloomCategories: readonly BloomCategory[] = [
  { name: 'Providers and theme', utility: true },
  { name: 'Overlays', utility: false },
  { name: 'Actions', utility: false },
  { name: 'Forms', utility: false },
  { name: 'Layout and lists', utility: false },
  { name: 'Identity and media', utility: false },
  { name: 'Feedback and data', utility: false },
  { name: 'Charts and motion', utility: false },
  { name: 'Assets', utility: true },
  { name: 'Uncategorized', utility: false },
]

/** Every subpath Bloom publishes types for, sorted by subpath. */
export const bloomIndex: readonly BloomSurfaceEntry[] = [
  {
    subpath: 'accordion',
    importPath: '@oxy.so/bloom/accordion',
    category: 'Layout and lists',
    components: [
      { name: 'Accordion' },
      { name: 'AccordionItem' },
      { name: 'AccordionTrigger' },
      { name: 'AccordionContent' },
    ],
  },
  {
    subpath: 'activity-heatmap',
    importPath: '@oxy.so/bloom/activity-heatmap',
    category: 'Charts and motion',
    components: [
      { name: 'ActivityHeatmap' },
    ],
  },
  {
    subpath: 'admonition',
    importPath: '@oxy.so/bloom/admonition',
    category: 'Feedback and data',
    components: [
      { name: 'AdmonitionIcon' },
      { name: 'AdmonitionContent' },
      { name: 'AdmonitionText' },
      { name: 'AdmonitionButton' },
      { name: 'AdmonitionRow' },
      { name: 'AdmonitionRoot' },
      { name: 'Admonition', description: 'Simple all-in-one Admonition component for common use cases. For more control, compose with AdmonitionRoot, AdmonitionRow, AdmonitionIcon, AdmonitionContent, AdmonitionText, and AdmonitionButton.' },
    ],
  },
  {
    subpath: 'alert-dialog',
    importPath: '@oxy.so/bloom/alert-dialog',
    category: 'Overlays',
    components: [
      { name: 'AlertDialog', description: 'Web variant of the `./alert-dialog` barrel — see `./index.ts`.' },
    ],
  },
  {
    subpath: 'animated-check',
    importPath: '@oxy.so/bloom/animated-check',
    category: 'Charts and motion',
    components: [
      { name: 'AnimatedCheck', description: "A draw-on checkmark: a ring strokes on, then the check strokes in. Expose a ref and call `ref.current?.play()` to (re)play — e.g. on a successful submit. Ported from Bluesky's `AnimatedCheck`." },
    ],
  },
  {
    subpath: 'aspect-ratio',
    importPath: '@oxy.so/bloom/aspect-ratio',
    category: 'Layout and lists',
    components: [
      { name: 'AspectRatio' },
    ],
  },
  {
    subpath: 'avatar',
    importPath: '@oxy.so/bloom/avatar',
    category: 'Identity and media',
    components: [
      { name: 'Avatar' },
      { name: 'AvatarPlaceholderProvider' },
    ],
  },
  {
    subpath: 'avatar-group',
    importPath: '@oxy.so/bloom/avatar-group',
    category: 'Identity and media',
    components: [
      { name: 'AvatarGroup' },
    ],
  },
  {
    subpath: 'badge',
    importPath: '@oxy.so/bloom/badge',
    category: 'Feedback and data',
    components: [
      { name: 'Badge' },
    ],
  },
  {
    subpath: 'benefit-list',
    importPath: '@oxy.so/bloom/benefit-list',
    category: 'Assets',
    components: [
      { name: 'BenefitRow' },
      { name: 'BenefitList' },
    ],
  },
  {
    subpath: 'bottom-sheet',
    importPath: '@oxy.so/bloom/bottom-sheet',
    category: 'Overlays',
    components: [
      { name: 'BottomSheet' },
    ],
  },
  {
    subpath: 'button',
    importPath: '@oxy.so/bloom/button',
    category: 'Actions',
    components: [
      { name: 'Button' },
      { name: 'PrimaryButton' },
      { name: 'SecondaryButton' },
      { name: 'IconButton' },
      { name: 'GhostButton' },
      { name: 'TextButton' },
      { name: 'InverseButton' },
      { name: 'OutlineButton' },
      { name: 'LinkButton' },
      { name: 'DestructiveButton' },
    ],
  },
  {
    subpath: 'card',
    importPath: '@oxy.so/bloom/card',
    category: 'Layout and lists',
    components: [
      { name: 'Card' },
      { name: 'CardHeader' },
      { name: 'CardBody' },
      { name: 'CardFooter' },
      { name: 'CardTitle' },
      { name: 'CardDescription' },
    ],
  },
  {
    subpath: 'checkbox',
    importPath: '@oxy.so/bloom/checkbox',
    category: 'Forms',
    components: [
      { name: 'Checkbox' },
    ],
  },
  {
    subpath: 'chip',
    importPath: '@oxy.so/bloom/chip',
    category: 'Feedback and data',
    components: [
      { name: 'Chip' },
    ],
  },
  {
    subpath: 'code',
    importPath: '@oxy.so/bloom/code',
    category: 'Feedback and data',
    components: [
      { name: 'Code' },
      { name: 'Pre' },
    ],
  },
  {
    subpath: 'color-presets',
    importPath: '@oxy.so/bloom/color-presets',
    category: 'Providers and theme',
    components: [],
  },
  {
    subpath: 'combobox',
    importPath: '@oxy.so/bloom/combobox',
    category: 'Forms',
    components: [
      { name: 'Combobox' },
    ],
  },
  {
    subpath: 'command',
    importPath: '@oxy.so/bloom/command',
    category: 'Forms',
    components: [
      { name: 'Command' },
    ],
  },
  {
    subpath: 'composition-bar',
    importPath: '@oxy.so/bloom/composition-bar',
    category: 'Charts and motion',
    components: [
      { name: 'CompositionBar' },
    ],
  },
  {
    subpath: 'connection-dots',
    importPath: '@oxy.so/bloom/connection-dots',
    category: 'Feedback and data',
    components: [
      { name: 'ConnectionDots' },
    ],
  },
  {
    subpath: 'connection-status',
    importPath: '@oxy.so/bloom/connection-status',
    category: 'Feedback and data',
    components: [
      { name: 'ConnectionStatusToasts', description: 'Mount once at the app root. Renders nothing.' },
    ],
  },
  {
    subpath: 'content-panel',
    importPath: '@oxy.so/bloom/content-panel',
    category: 'Layout and lists',
    components: [
      { name: 'ContentPanel' },
    ],
  },
  {
    subpath: 'context-menu',
    importPath: '@oxy.so/bloom/context-menu',
    category: 'Overlays',
    components: [
      { name: 'ContextMenu' },
      { name: 'ContextMenuTrigger' },
      { name: 'ContextMenuContent' },
    ],
  },
  {
    subpath: 'design-tokens',
    importPath: '@oxy.so/bloom/design-tokens',
    category: 'Providers and theme',
    components: [],
  },
  {
    subpath: 'dialog',
    importPath: '@oxy.so/bloom/dialog',
    category: 'Overlays',
    components: [
      { name: 'Dialog', description: 'Web variant of `<Dialog>`.' },
    ],
  },
  {
    subpath: 'divider',
    importPath: '@oxy.so/bloom/divider',
    category: 'Layout and lists',
    components: [
      { name: 'Divider' },
    ],
  },
  {
    subpath: 'dot-grid-meter',
    importPath: '@oxy.so/bloom/dot-grid-meter',
    category: 'Charts and motion',
    components: [
      { name: 'DotGridMeter' },
    ],
  },
  {
    subpath: 'dropdown-menu',
    importPath: '@oxy.so/bloom/dropdown-menu',
    category: 'Overlays',
    components: [
      { name: 'DropdownMenu' },
      { name: 'DropdownMenuTrigger' },
      { name: 'DropdownMenuContent' },
    ],
  },
  {
    subpath: 'error-boundary',
    importPath: '@oxy.so/bloom/error-boundary',
    category: 'Feedback and data',
    components: [
      { name: 'ErrorBoundary' },
    ],
  },
  {
    subpath: 'fab',
    importPath: '@oxy.so/bloom/fab',
    category: 'Actions',
    components: [
      { name: 'Fab' },
    ],
  },
  {
    subpath: 'field',
    importPath: '@oxy.so/bloom/field',
    category: 'Forms',
    components: [
      { name: 'Field' },
    ],
  },
  {
    subpath: 'fill',
    importPath: '@oxy.so/bloom/fill',
    category: 'Identity and media',
    components: [
      { name: 'Fill' },
    ],
  },
  {
    subpath: 'fonts',
    importPath: '@oxy.so/bloom/fonts',
    category: 'Assets',
    components: [
      { name: 'FontLoader', description: "Web font loader. Applies the Bloom `@font-face` rules and CSS variables to `:root` on first render, before the first paint, using the same `useRef`-during-render pattern as `BloomThemeProvider`'s color application." },
    ],
  },
  {
    subpath: 'frosted-icon-button',
    importPath: '@oxy.so/bloom/frosted-icon-button',
    category: 'Actions',
    components: [
      { name: 'FrostedIconButton' },
    ],
  },
  {
    subpath: 'grid',
    importPath: '@oxy.so/bloom/grid',
    category: 'Layout and lists',
    components: [
      { name: 'Row' },
      { name: 'Col' },
    ],
  },
  {
    subpath: 'hooks',
    importPath: '@oxy.so/bloom/hooks',
    category: 'Providers and theme',
    components: [
      { name: 'BloomHapticsProvider', description: 'Optional provider that toggles haptic feedback for its subtree — e.g. to honour a user "reduce haptics" preference. `useHaptics` defaults to enabled when no provider is present.' },
    ],
  },
  {
    subpath: 'icon-circle',
    importPath: '@oxy.so/bloom/icon-circle',
    category: 'Charts and motion',
    components: [
      { name: 'IconCircle' },
    ],
  },
  {
    subpath: 'icons',
    importPath: '@oxy.so/bloom/icons',
    category: 'Assets',
    components: [
      { name: 'AndroidLogo' },
      { name: 'AppleLogo' },
      { name: 'Bookmark' },
      { name: 'BookmarkFilled' },
      { name: 'BookmarkDeleteLarge' },
      { name: 'Full' },
      { name: 'Mark' },
      { name: 'Newskie' },
      { name: 'Reply' },
      { name: 'ReplyFilled' },
      { name: 'StarterPack' },
      { name: 'VerifiedCheck' },
      { name: 'VerifierCheck' },
    ],
  },
  {
    subpath: 'image-aspect-ratio-cache',
    importPath: '@oxy.so/bloom/image-aspect-ratio-cache',
    category: 'Identity and media',
    components: [],
  },
  {
    subpath: 'image-resolver',
    importPath: '@oxy.so/bloom/image-resolver',
    category: 'Identity and media',
    components: [
      { name: 'ImageResolverProvider' },
    ],
  },
  {
    subpath: 'input-group',
    importPath: '@oxy.so/bloom/input-group',
    category: 'Forms',
    components: [
      { name: 'InputGroup' },
      { name: 'InputGroupAddon' },
    ],
  },
  {
    subpath: 'item',
    importPath: '@oxy.so/bloom/item',
    category: 'Layout and lists',
    components: [
      { name: 'Item' },
    ],
  },
  {
    subpath: 'kbd',
    importPath: '@oxy.so/bloom/kbd',
    category: 'Feedback and data',
    components: [
      { name: 'Kbd' },
    ],
  },
  {
    subpath: 'label',
    importPath: '@oxy.so/bloom/label',
    category: 'Forms',
    components: [
      { name: 'Label' },
    ],
  },
  {
    subpath: 'layout',
    importPath: '@oxy.so/bloom/layout',
    category: 'Uncategorized',
    components: [
      { name: 'BottomEdgeProvider', description: 'Wrap the app once — `BloomProvider` already does. Rendering a second one scopes a nested subtree to its own claims, which is a real (if rare) thing to want: a bottom-edge surface inside a full-screen modal should not be offset by the tab bar the modal is covering.' },
    ],
  },
  {
    subpath: 'level-picker',
    importPath: '@oxy.so/bloom/level-picker',
    category: 'Uncategorized',
    components: [
      { name: 'LevelPicker' },
    ],
  },
  {
    subpath: 'link-preview',
    importPath: '@oxy.so/bloom/link-preview',
    category: 'Feedback and data',
    components: [
      { name: 'LinkPreviewCard' },
    ],
  },
  {
    subpath: 'list',
    importPath: '@oxy.so/bloom/list',
    category: 'Layout and lists',
    components: [
      { name: 'VirtualList' },
    ],
  },
  {
    subpath: 'loading',
    importPath: '@oxy.so/bloom/loading',
    category: 'Feedback and data',
    components: [
      { name: 'Loading' },
      { name: 'SpinnerIcon' },
    ],
  },
  {
    subpath: 'media-flight',
    importPath: '@oxy.so/bloom/media-flight',
    category: 'Uncategorized',
    components: [
      { name: 'MediaFlightLayer' },
      { name: 'MediaFlightHost', description: "The web host publishes its slot to the layer, which paints every shared node through one non-generic `MediaSurface`. Widening is sound for the same reason as the native host's `widenSlot`: the only player Bloom ever hands a slot is the one it took out of that slot's own `content`. Bloom transports the object; it never substitutes one." },
      { name: 'MediaSurface', description: 'A still image, or a video fed by a player the CONSUMER owns.' },
      { name: 'MediaPoster', description: "The STILL of a media item — a video's poster, or the image itself — and never a video view." },
      { name: 'EmptyMediaSurface', description: 'A box with no media at all — what a gallery page renders for a video item whose poster is unknown, so the layout never collapses.' },
    ],
  },
  {
    subpath: 'media-inset-border',
    importPath: '@oxy.so/bloom/media-inset-border',
    category: 'Identity and media',
    components: [
      { name: 'MediaInsetBorder', description: 'A theme-aware hairline border painted just inside a media box (image, avatar, embed) to separate it from the surrounding background. Absolutely positioned to fill its parent (built on Fill ) and non-interactive.' },
    ],
  },
  {
    subpath: 'menubar',
    importPath: '@oxy.so/bloom/menubar',
    category: 'Overlays',
    components: [
      { name: 'Menubar' },
      { name: 'MenubarMenu' },
      { name: 'MenubarTrigger' },
      { name: 'MenubarContent' },
    ],
  },
  {
    subpath: 'motion',
    importPath: '@oxy.so/bloom/motion',
    category: 'Charts and motion',
    components: [
      { name: 'ScreenTransition', description: "Wraps `children` in a Reanimated layout-animated view that slides in directionally on native and (optionally) cross-fades on web. Ported from Bluesky's `ScreenTransition`." },
    ],
  },
  {
    subpath: 'overlay',
    importPath: '@oxy.so/bloom/overlay',
    category: 'Overlays',
    components: [
      { name: 'OverlayRoot', description: 'Outermost node of a portaled surface. Three jobs:' },
      { name: 'Backdrop', description: 'Full-bleed blur + dim that dismisses the surface when pressed.' },
    ],
  },
  {
    subpath: 'popover',
    importPath: '@oxy.so/bloom/popover',
    category: 'Overlays',
    components: [
      { name: 'Popover' },
      { name: 'PopoverTrigger' },
      { name: 'PopoverContent' },
    ],
  },
  {
    subpath: 'portal',
    importPath: '@oxy.so/bloom/portal',
    category: 'Overlays',
    components: [
      { name: 'Portal' },
      { name: 'PortalProvider' },
      { name: 'PortalOutlet' },
    ],
  },
  {
    subpath: 'preset-vars',
    importPath: '@oxy.so/bloom/preset-vars',
    category: 'Providers and theme',
    components: [],
  },
  {
    subpath: 'pressable-scale',
    importPath: '@oxy.so/bloom/pressable-scale',
    category: 'Actions',
    components: [
      { name: 'PressableScale', description: "A drop-in `Pressable` that springs to a smaller scale on press-in and back on release. The scale is applied to the pressable node itself, so a consumer's `className` / layout styles (e.g. `flex-row items-center`) land on the same node that animates." },
    ],
  },
  {
    subpath: 'profile-card',
    importPath: '@oxy.so/bloom/profile-card',
    category: 'Identity and media',
    components: [
      { name: 'ProfileCard' },
    ],
  },
  {
    subpath: 'progressive-blur',
    importPath: '@oxy.so/bloom/progressive-blur',
    category: 'Identity and media',
    components: [
      { name: 'ProgressiveBlur', description: 'WEB fork of ProgressiveBlur — ONE element instead of the native ten-layer stack.' },
    ],
  },
  {
    subpath: 'prompt-input',
    importPath: '@oxy.so/bloom/prompt-input',
    category: 'Forms',
    components: [
      { name: 'PromptInput', description: 'Web `PromptInput` — same chrome, bound to the web textarea fork.' },
      { name: 'PromptInputTextarea' },
      { name: 'PromptInputActions' },
      { name: 'PromptInputAttachments' },
      { name: 'PromptInputSubmitButton' },
    ],
  },
  {
    subpath: 'provider',
    importPath: '@oxy.so/bloom/provider',
    category: 'Providers and theme',
    components: [
      { name: 'BloomProvider' },
    ],
  },
  {
    subpath: 'radio',
    importPath: '@oxy.so/bloom/radio',
    category: 'Forms',
    components: [
      { name: 'Radio' },
      { name: 'RadioGroup' },
    ],
  },
  {
    subpath: 'radio-indicator',
    importPath: '@oxy.so/bloom/radio-indicator',
    category: 'Charts and motion',
    components: [
      { name: 'RadioIndicator' },
    ],
  },
  {
    subpath: 'scroll',
    importPath: '@oxy.so/bloom/scroll',
    category: 'Layout and lists',
    components: [
      { name: 'ScrollRestorationProvider', description: 'Holds the offset map and the router binding for the subtree. One provider near the app root is enough; the store lives as long as the provider, so offsets survive navigating away and back (including browser Back/Forward).' },
    ],
  },
  {
    subpath: 'scroll/expo-router',
    importPath: '@oxy.so/bloom/scroll/expo-router',
    category: 'Layout and lists',
    components: [],
  },
  {
    subpath: 'search',
    importPath: '@oxy.so/bloom/search',
    category: 'Forms',
    components: [
      { name: 'Search' },
    ],
  },
  {
    subpath: 'segmented-control',
    importPath: '@oxy.so/bloom/segmented-control',
    category: 'Forms',
    components: [
      { name: 'SegmentedControl', description: 'Segmented control component.' },
      { name: 'SegmentedControlItem' },
      { name: 'SegmentedControlItemText' },
    ],
  },
  {
    subpath: 'select',
    importPath: '@oxy.so/bloom/select',
    category: 'Forms',
    components: [
      { name: 'Select' },
      { name: 'SelectTrigger', description: 'Opens the dropdown, and is the box it anchors to.' },
      { name: 'SelectValue' },
      { name: 'SelectIcon' },
      { name: 'SelectContent' },
      { name: 'SelectItem' },
      { name: 'SelectItemText' },
      { name: 'SelectItemIndicator' },
      { name: 'SelectSeparator' },
      { name: 'SelectGroup', description: 'A set of related options, so a screen reader announces them as one.' },
      { name: 'SelectLabel', description: 'The heading of a `SelectGroup`.' },
      { name: 'SelectScrollUpButton' },
      { name: 'SelectScrollDownButton' },
    ],
  },
  {
    subpath: 'settings-list',
    importPath: '@oxy.so/bloom/settings-list',
    category: 'Layout and lists',
    components: [
      { name: 'SettingsListItem' },
      { name: 'SettingsListGroup' },
      { name: 'SettingsListDivider' },
    ],
  },
  {
    subpath: 'skeleton',
    importPath: '@oxy.so/bloom/skeleton',
    category: 'Feedback and data',
    components: [
      { name: 'Text' },
      { name: 'Circle' },
      { name: 'Pill' },
      { name: 'Box', description: 'Generic rectangular shimmering placeholder. Use for image/card/banner placeholders where neither Pill (forced `borderRadius.full`) nor Circle fit. Defaults to a small borderRadius (8). Pass `0` for sharp corners or any larger number / percentage string for custom shapes.' },
      { name: 'Col' },
      { name: 'Row' },
    ],
  },
  {
    subpath: 'slider',
    importPath: '@oxy.so/bloom/slider',
    category: 'Forms',
    components: [
      { name: 'Slider' },
    ],
  },
  {
    subpath: 'stat-bar',
    importPath: '@oxy.so/bloom/stat-bar',
    category: 'Charts and motion',
    components: [
      { name: 'StatBar' },
    ],
  },
  {
    subpath: 'styles',
    importPath: '@oxy.so/bloom/styles',
    category: 'Providers and theme',
    components: [],
  },
  {
    subpath: 'subtle-hover',
    importPath: '@oxy.so/bloom/subtle-hover',
    category: 'Actions',
    components: [
      { name: 'SubtleHover', description: 'An absolutely-positioned, non-interactive contrast wash. Two modes:' },
    ],
  },
  {
    subpath: 'surfaces',
    importPath: '@oxy.so/bloom/surfaces',
    category: 'Overlays',
    components: [
      { name: 'SurfaceHost', description: 'Web variant of the surface stack barrel. Identical surface area to the native `./index.ts` — it just binds the web-fork `Dialog` (`Dialog.web.tsx`, a pure-DOM overlay) instead of the native `BottomSheet`-backed one. The store, imperative API, hook, and types are shared, platform-agnostic modules.' },
      { name: 'SurfaceProvider' },
    ],
  },
  {
    subpath: 'switch',
    importPath: '@oxy.so/bloom/switch',
    category: 'Forms',
    components: [
      { name: 'Switch' },
    ],
  },
  {
    subpath: 'tab-bar',
    importPath: '@oxy.so/bloom/tab-bar',
    category: 'Layout and lists',
    components: [
      { name: 'TabBar' },
      { name: 'TabBarButton' },
      { name: 'TabBarMinimizeProvider', description: 'Wrap the tab tree once. Screens then call `useMinimizeOnScroll()` and the bar reads the same progress, so scrolling any screen minimizes the bar.' },
    ],
  },
  {
    subpath: 'tab-bar/expo-router',
    importPath: '@oxy.so/bloom/tab-bar/expo-router',
    category: 'Layout and lists',
    components: [
      { name: 'RouterTabBar', description: "The bar, as expo-router's `<TabList asChild>` child." },
      { name: 'RouterTabBarButton', description: "One trigger, as expo-router's `<TabTrigger asChild>` child. The trigger supplies `isFocused` and `onPress`; the button uses the first to drive the highlight and the second to navigate on keyboard / assistive-technology activation." },
    ],
  },
  {
    subpath: 'tabs',
    importPath: '@oxy.so/bloom/tabs',
    category: 'Layout and lists',
    components: [
      { name: 'Tabs' },
      { name: 'TabsTrigger' },
      { name: 'TabsContent' },
    ],
  },
  {
    subpath: 'tabs/expo-router',
    importPath: '@oxy.so/bloom/tabs/expo-router',
    category: 'Layout and lists',
    components: [
      { name: 'RouterTabs', description: 'A tab strip whose selection IS the route.' },
    ],
  },
  {
    subpath: 'tailwind-preset',
    importPath: '@oxy.so/bloom/tailwind-preset',
    category: 'Providers and theme',
    components: [],
  },
  {
    subpath: 'teleport',
    importPath: '@oxy.so/bloom/teleport',
    category: 'Uncategorized',
    components: [
      { name: 'PortalHost', description: 'PortalHost is a component that acts as an anchor for the portals. You can define multiple portal hosts in your app and use them to render different portals. Each portal host has a unique name that you can use to identify a necessary one among the others.' },
      { name: 'Portal', description: 'Portal helps you to render a component in a different place in the view hierarchy. This is useful when you need a view to visually “break out” of its parent container (for example: modals, toasts, floating UI, popovers).' },
      { name: 'PortalProvider', description: 'Wraps your app with this component to use the teleport API.' },
    ],
  },
  {
    subpath: 'text-field',
    importPath: '@oxy.so/bloom/text-field',
    category: 'Forms',
    components: [
      { name: 'TextField' },
      { name: 'TextFieldInput' },
      { name: 'TextFieldLabel' },
      { name: 'TextFieldIcon' },
      { name: 'TextFieldSuffix' },
      { name: 'TextFieldGhost' },
    ],
  },
  {
    subpath: 'theme',
    importPath: '@oxy.so/bloom/theme',
    category: 'Providers and theme',
    components: [
      { name: 'BloomThemeProvider' },
      { name: 'BloomColorScope' },
      { name: 'BloomSeedScope', description: "Web `<BloomSeedScope>`: scopes a subtree to an ARBITRARY seed colour's palette (the dynamic counterpart of `<BloomColorScope>`). It (1) writes every canonical `--x` token plus the Tailwind v4 `--color-x` aliases (already resolved to `rgb(...)`) onto the wrapping element's inline `style`, so NativeWind classes inside resolve against the seed palette instead of the document root, and (2) publishes a matching JS `theme` on `BloomThemeContext` so `useTheme()`/`useBloomTheme()` consumers inside the subtree re-theme too. The `colorPreset` field is left as the parent's (a seed is not a named preset)." },
    ],
  },
  {
    subpath: 'toast',
    importPath: '@oxy.so/bloom/toast',
    category: 'Feedback and data',
    components: [
      { name: 'Toaster' },
      { name: 'ToastOutlet', description: 'The toast stack. Mount this ONCE near the app root — `OxyProvider` already does, so most apps never write it themselves.' },
    ],
  },
  {
    subpath: 'tooltip',
    importPath: '@oxy.so/bloom/tooltip',
    category: 'Overlays',
    components: [
      { name: 'Tooltip' },
      { name: 'TooltipTrigger' },
      { name: 'TooltipContent' },
      { name: 'TooltipTextBubble' },
    ],
  },
  {
    subpath: 'typography',
    importPath: '@oxy.so/bloom/typography',
    category: 'Assets',
    components: [
      { name: 'Text' },
      { name: 'Span' },
      { name: 'H1' },
      { name: 'H2' },
      { name: 'H3' },
      { name: 'H4' },
      { name: 'H5' },
      { name: 'H6' },
      { name: 'P' },
      { name: 'Lead', description: 'An intro paragraph — larger than body text and set in the secondary colour.' },
      { name: 'Large', description: "Emphasised body text — a form section's opening line, a callout's first row." },
      { name: 'Small', description: 'A dense label — form hints, table headers, metadata rows.' },
      { name: 'Muted', description: 'De-emphasised supporting text.' },
      { name: 'Blockquote', description: 'A quotation, with the rule down its left edge.' },
    ],
  },
  {
    subpath: 'user-hover-card',
    importPath: '@oxy.so/bloom/user-hover-card',
    category: 'Identity and media',
    components: [
      { name: 'UserHoverCard' },
    ],
  },
  {
    subpath: 'zoomable-image-gallery',
    importPath: '@oxy.so/bloom/zoomable-image-gallery',
    category: 'Identity and media',
    components: [
      { name: 'ZoomableMediaGallery' },
    ],
  },
  {
    subpath: 'zoomable-media-gallery',
    importPath: '@oxy.so/bloom/zoomable-media-gallery',
    category: 'Uncategorized',
    components: [
      { name: 'ZoomableMediaGallery' },
    ],
  },
]
