/**
 * Writes `src/styles/theme.generated.css` — the palette the page paints before
 * JavaScript runs.
 *
 * Bloom's `theme.css` ships the alias layer (`--color-background:
 * var(--background)`) and says nothing about what `--background` is;
 * `BloomThemeProvider` writes that at startup. Every page here is prerendered,
 * so between first paint and hydration the browser shows whatever this
 * stylesheet declares. Written by hand, that becomes a second palette that
 * drifts from the one the app actually applies — which is exactly what it had
 * become: `--secondary` was a light grey where the preset resolves to teal, and
 * `--card` was missing entirely, leaving every `bg-fill` transparent until React
 * mounted.
 *
 * So it is derived, from the same Bloom functions the runtime uses:
 *
 *   - Document root (`:root`, `.dark`, and the host-stamped `[data-brand]`
 *     apex): `getPresetVars`, canonical tokens only. The alias layer is already
 *     declared at `:root` by Bloom's `theme.css`, and resolves against these.
 *   - Scoped blocks (a brand page, a forced-dark region): `buildSeedScopeVars`,
 *     which also emits the `--color-x` aliases. A scope needs them because an
 *     alias substitutes where it is DECLARED — overriding `--background` inside
 *     `.tnp-theme` does not move a `--color-background` declared at `:root`.
 *     This is the whole reason the hand-written brand themes wrote every colour
 *     twice, in two namespaces, and why they could disagree.
 *
 * Run by `predev` / `prebuild`; the output is committed so a plain `vite build`
 * is never left without a palette.
 */

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { APP_COLOR_PRESETS } from '@oxyhq/bloom/color-presets'
import { getPresetVars, buildSeedScopeVars } from '@oxyhq/bloom/design-tokens'

import {
  BRAND_SURFACES,
  HOST_BRANDS,
  SITE_PRESET,
  type BrandSurface,
} from '../src/theme/brands'

const OUTPUT = join(import.meta.dir, '..', 'src', 'styles', 'theme.generated.css')

function block(selector: string, vars: Record<string, string>, extra?: string): string {
  const body = Object.entries(vars)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n')
  return `${selector} {\n${body}${extra ? `\n  ${extra}` : ''}\n}`
}

/** A document-root block: the alias layer at `:root` already resolves against it. */
function rootBlock(selector: string, preset: Parameters<typeof getPresetVars>[0], mode: 'light' | 'dark'): string {
  return block(selector, getPresetVars(preset, mode))
}

/** A scoped block: carries the `--color-x` aliases too, or utilities miss it. */
function scopeBlock(selector: string, seed: string, mode: 'light' | 'dark', extra?: string): string {
  return block(selector, buildSeedScopeVars({ seed, mode }), extra)
}

function brandBlocks(surface: BrandSurface): string[] {
  const heading = `/* ${surface.label} — seed ${surface.seed} */`
  if (surface.mode === 'dark') {
    return [`${heading}\n${scopeBlock(surface.selector, surface.seed, 'dark', 'color-scheme: dark;')}`]
  }
  return [
    `${heading}\n${scopeBlock(surface.selector, surface.seed, 'light')}`,
    scopeBlock(`${surface.selector}:is(.dark, .dark *)`, surface.seed, 'dark'),
  ]
}

const sections: string[] = [
  `/*
 * AUTO-GENERATED by scripts/generate-theme-css.ts — DO NOT EDIT.
 * Source of truth: src/theme/brands.ts + @oxyhq/bloom/design-tokens.
 * Re-run \`bun run generate:theme\` (or any \`bun run dev\` / \`bun run build\`).
 */`,
  `/* The site palette, before BloomThemeProvider applies the same one. */\n${rootBlock(':root', SITE_PRESET, 'light')}`,
  rootBlock('.dark', SITE_PRESET, 'dark'),
]

for (const [brand, preset] of Object.entries(HOST_BRANDS)) {
  sections.push(
    `/* ${brand} apex — index.html stamps data-brand from the hostname pre-paint. */\n${rootBlock(
      `:root[data-brand='${brand}']`,
      preset,
      'light',
    )}`,
    rootBlock(`:root[data-brand='${brand}'].dark`, preset, 'dark'),
  )
}

sections.push(
  `/* A region that stays dark inside a light page (hero art, product shots). */\n${scopeBlock(
    '.force-dark',
    APP_COLOR_PRESETS[SITE_PRESET].hex,
    'dark',
    'color-scheme: dark;',
  )}`,
)

for (const surface of BRAND_SURFACES) sections.push(...brandBlocks(surface))

writeFileSync(OUTPUT, `${sections.join('\n\n')}\n`)
console.log(`[generate-theme-css] wrote ${OUTPUT}`)
