#!/usr/bin/env bun

/**
 * Writes the scope a `<BloomPlayground>` snippet is evaluated against: every
 * module the demos in `src/content/bloom-demos/` import as a VALUE.
 *
 * ## Why generated
 *
 * The playground compiles the reader's snippet in the browser and answers its
 * `require` calls from a fixed map of specifier → module namespace. That map
 * cannot be the whole of `@oxy.so/bloom`: `vite.config.ts` sends every
 * `node_modules/@oxy.so/*` module to the `vendor-oxy` chunk, the entry HTML
 * preloads that chunk on every route, and chunk assignment is static — so even
 * a lazy `import('@oxy.so/bloom')` reached only from that page lands there.
 * Measured, importing the barrel added 260.90 kB (75.82 kB gzipped) to the
 * first paint of every page of the site, to serve one docs page.
 *
 * What it can be for free is the set the demos already import, because those
 * bytes are in `vendor-oxy` either way. Written by hand that is a list nobody
 * maintains: a seventeenth demo importing a surface the map lacks does not
 * compile, and the only thing that says so is a reader opening the page. So it
 * is derived from the demos themselves and there is no list to fall behind.
 *
 * ## What counts as an import
 *
 * The TypeScript parser, not a regex — `import type` and per-specifier `type`
 * modifiers have to be told from value imports exactly, because Sucrase elides
 * them and a type-only import that reached the map would put a surface in
 * `vendor-oxy` for nothing. `import './x'` with no clause is a value import: it
 * has no bindings but the module still runs.
 *
 * A RELATIVE value import throws. It is site-internal by construction — no
 * reader could write it in their own app — so a snippet containing one could
 * not run wherever the map sent it, and emitting a plausible scope around it
 * would hide that.
 *
 * ## What fails the build
 *
 * A relative value import, two specifiers whose derived identifiers collide,
 * and either vacuity floor. The floors are the check that "I found less" and
 * "there is less" do not read the same: a glob that stopped matching, or a
 * parser handed the wrong `ScriptKind`, emits a nearly empty scope and looks
 * perfectly healthy — every demo would simply fail to compile, on a page the
 * build never opens.
 *
 * Guarded by `validate-bloom-live-scope.ts`, which is itself mutation-tested by
 * `test-validate-bloom-live-scope.ts`.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import ts from 'typescript'

const ROOT = join(import.meta.dir, '..')

/** The demos the scope is derived from. */
export const DEMOS_DIR = join(ROOT, 'src/content/bloom-demos')

/** The module the playground runtime imports. */
export const SCOPE_PATH = join(ROOT, 'src/components/docs/BloomLiveScope.generated.ts')

/**
 * Required by the compiled output rather than by any demo: Sucrase emits the
 * automatic JSX runtime, so every snippet requires this whether or not a demo
 * names it. It is the one entry the demos cannot imply, and leaving it out
 * fails every snippet at once.
 */
const RUNTIME_SPECIFIERS = ['react/jsx-runtime']

/**
 * Below these the generator throws rather than emit a short scope. Both sit
 * well under today's numbers and well above what a broken walk would produce.
 */
const FLOORS = { demos: 10, specifiers: 10 }

const DO_NOT_EDIT = '// Generated by scripts/generate-bloom-live-scope.ts. Do not edit.'

export interface ScopeStats {
  demos: number
  specifiers: number
}

export interface BuildOptions {
  /** Defaults to the repository's demo directory. */
  demosDir?: string
  /** Relaxed by the mutation test, whose fixture is deliberately tiny. */
  floors?: { demos: number; specifiers: number }
}

export interface BuildResult {
  /** The emitted module source. */
  scope: string
  /** Every specifier in the map, sorted — the same order the module emits. */
  specifiers: string[]
  stats: ScopeStats
}

/** Demo files, sorted, so two runs over one directory emit the same bytes. */
export function listDemoFiles(dir: string = DEMOS_DIR): string[] {
  return readdirSync(dir)
    .filter((name) => /^[A-Z][^.]*\.tsx$/.test(name))
    .sort()
}

/**
 * Specifiers this file imports as values. A declaration counts when it is not
 * `import type` and either binds something that is not itself `type`-modified,
 * or binds nothing at all (a side-effect import still runs the module).
 */
export function valueImportsOf(fileName: string, source: string): string[] {
  const parsed = ts.createSourceFile(fileName, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX)
  const specifiers: string[] = []
  for (const statement of parsed.statements) {
    if (!ts.isImportDeclaration(statement)) continue
    if (!ts.isStringLiteral(statement.moduleSpecifier)) continue
    const clause = statement.importClause
    if (clause) {
      if (clause.isTypeOnly) continue
      const bindings = clause.namedBindings
      const bindsAValue =
        clause.name !== undefined ||
        (bindings !== undefined &&
          (ts.isNamespaceImport(bindings) ||
            bindings.elements.some((element) => !element.isTypeOnly)))
      if (!bindsAValue) continue
    }
    specifiers.push(statement.moduleSpecifier.text)
  }
  return specifiers
}

/**
 * The local name a specifier is imported under: its path with any npm scope
 * dropped, camel-cased. `@oxy.so/bloom/text-field` → `bloomTextField`,
 * `react/jsx-runtime` → `reactJsxRuntime`, `react` → `react`.
 *
 * Two specifiers can in principle derive the same name (`a/b` and `a-b`), so
 * collisions throw rather than silently drop an entry. A specifier that derived
 * a reserved word would emit a module that does not parse, which `tsc -b` names
 * — loudly, and with the file in hand.
 */
export function identifierFor(specifier: string): string {
  const parts = specifier.replace(/^@[^/]+\//, '').split(/[^A-Za-z0-9]+/).filter(Boolean)
  return parts
    .map((part, index) =>
      index === 0
        ? part.charAt(0).toLowerCase() + part.slice(1)
        : part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join('')
}

export function buildBloomLiveScope(options: BuildOptions = {}): BuildResult {
  const demosDir = options.demosDir ?? DEMOS_DIR
  const floors = options.floors ?? FLOORS

  const files = listDemoFiles(demosDir)
  const specifiers = new Set<string>(RUNTIME_SPECIFIERS)
  for (const file of files) {
    for (const specifier of valueImportsOf(file, readFileSync(join(demosDir, file), 'utf8'))) {
      if (specifier.startsWith('.') || specifier.startsWith('/')) {
        throw new Error(
          `${file} imports "${specifier}" as a value. The playground scope can only hold modules a `
          + 'reader could import from their own app, so a relative import cannot be in it — move '
          + 'what the demo needs into the demo, or make the import `import type`.',
        )
      }
      specifiers.add(specifier)
    }
  }

  const sorted = [...specifiers].sort()

  const identifiers = new Map<string, string>()
  for (const specifier of sorted) {
    const identifier = identifierFor(specifier)
    const claimed = identifiers.get(identifier)
    if (claimed !== undefined) {
      throw new Error(
        `"${specifier}" and "${claimed}" both derive the local name "${identifier}".`,
      )
    }
    identifiers.set(identifier, specifier)
  }

  if (files.length < floors.demos) {
    throw new Error(
      `Found ${files.length} demos in ${demosDir}, expected at least ${floors.demos}. `
      + 'A walk that stopped early emits a scope in which every snippet fails to compile.',
    )
  }
  if (sorted.length < floors.specifiers) {
    throw new Error(
      `Found ${sorted.length} modules across ${files.length} demos, expected at least `
      + `${floors.specifiers}. A parser handed the wrong ScriptKind reports every file as importing `
      + 'nothing, which looks exactly like demos that import nothing.',
    )
  }

  const byIdentifier = new Map([...identifiers].map(([name, specifier]) => [specifier, name]))
  const imports = sorted.map(
    (specifier) => `import * as ${byIdentifier.get(specifier) as string} from '${specifier}'`,
  )
  const entries = sorted.map((specifier) => {
    const name = byIdentifier.get(specifier) as string
    return name === specifier ? `  ${name},` : `  '${specifier}': ${name},`
  })

  const scope = [
    DO_NOT_EDIT,
    '//',
    `// The modules a playground snippet may import: every one the ${files.length} demos in`,
    '// src/content/bloom-demos/ import as a VALUE, plus the JSX runtime Sucrase\'s',
    '// output requires. See scripts/generate-bloom-live-scope.ts for why the scope is',
    '// this set and not the whole of @oxy.so/bloom.',
    '',
    ...imports,
    '',
    '/** Specifier → module namespace, exactly as a bundler would resolve it. */',
    'export const SNIPPET_MODULES: Readonly<Record<string, object>> = {',
    ...entries,
    '}',
    '',
  ].join('\n')

  return { scope, specifiers: sorted, stats: { demos: files.length, specifiers: sorted.length } }
}

export function writeBloomLiveScope(built: BuildResult, path: string = SCOPE_PATH): void {
  writeFileSync(path, built.scope)
}

if (import.meta.main) {
  const built = buildBloomLiveScope()
  writeBloomLiveScope(built)
  console.log(
    `[generate-bloom-live-scope] wrote ${SCOPE_PATH}`
    + ` (${built.stats.specifiers} modules from ${built.stats.demos} demos)`,
  )
}
