import { MCP_TOOL_ACCESS } from '../mcpAccess.js'
import { describeAccess, TOOLS } from './catalog.js'

/* ──────────────────────────────────────────────
 * The public tool reference, rendered from the catalog itself.
 *
 * `src/content/mcp/tools.mdx` embeds this between its TOOL_REFERENCE markers;
 * `bun server/scripts/generate-mcp-tool-reference.ts` rewrites it and
 * `server/mcp/reference.test.ts` fails when the page and the catalog disagree,
 * so the docs cannot drift from the tools again.
 * ──────────────────────────────────────────── */

export const REFERENCE_START = '{/* TOOL_REFERENCE:START — generated by server/scripts/generate-mcp-tool-reference.ts; do not edit */}'
export const REFERENCE_END = '{/* TOOL_REFERENCE:END */}'

const DOMAIN_TITLES: Record<string, string> = {
  discovery: 'Discovery and status',
  site: 'Pages, navigation, hero and settings',
  newsroom: 'Newsroom',
  'academy-and-help': 'Academy and Help Center',
  careers: 'Careers and team',
  products: 'Products and categories',
  pricing: 'Pricing and testimonials',
  changelog: 'Changelog and tracked repositories',
  media: 'Media',
  localization: 'Locales and translations',
  referrals: 'Referrals',
}

/** MDX treats braces and angle brackets as code; a description is prose. */
function mdxText(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/[{}<>]/g, (char) => `\\${char}`).replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim()
}

function access(name: string): string {
  const kind = MCP_TOOL_ACCESS[name]?.kind
  return kind === 'write' ? 'Write (admin)' : kind === 'admin-read' ? 'Read (admin)' : kind === 'public-read' ? 'Read' : 'Read (any account)'
}

export function renderToolReference(): string {
  const described = describeAccess({ actorId: '' }).domains as Record<string, { name: string; supportsDryRun: boolean; supportsExpectedUpdatedAt: boolean; supportsLocale: boolean; acceptsIdempotencyKey: boolean; undo: string | null }[]>
  const lines = [REFERENCE_START, '']
  for (const [domain, tools] of Object.entries(described)) {
    lines.push(`## ${DOMAIN_TITLES[domain] ?? domain}`, '', '| Tool | Access | Options | What it does |', '|---|---|---|---|')
    for (const tool of tools) {
      const definition = TOOLS.find((candidate) => candidate.name === tool.name)
      const options = [
        tool.supportsLocale && '`locale`',
        tool.supportsExpectedUpdatedAt && '`expectedUpdatedAt`',
        tool.supportsDryRun && '`dryRun`',
        tool.acceptsIdempotencyKey && '`idempotencyKey`',
      ].filter(Boolean).join(', ') || '—'
      lines.push(`| \`${tool.name}\` | ${access(tool.name)} | ${options} | ${mdxText(definition?.description ?? '')} |`)
    }
    lines.push('')
  }
  lines.push(REFERENCE_END)
  return lines.join('\n')
}

/** `source` with its reference block replaced by the current one. */
export function withToolReference(source: string): string {
  const start = source.indexOf(REFERENCE_START)
  const end = source.indexOf(REFERENCE_END)
  if (start === -1 || end === -1 || end < start) throw new Error('tools.mdx is missing its TOOL_REFERENCE markers')
  return source.slice(0, start) + renderToolReference() + source.slice(end + REFERENCE_END.length)
}
