export interface NewsroomProductRef {
  _id: string
  productId: string
  name: string
}

/** Lightweight public list shape. Article Markdown and editorial fields stay on detail. */
export interface NewsroomPostSummary {
  _id?: string
  slug: string
  title: string
  resume: string
  coverImage?: string
  /** Width-described thumbnail candidates generated by the media service. */
  coverImageSrcSet?: string
  imageAlt?: string
  categories: string[]
  featured: boolean
  /** Bloom recipe persisted per post; legacy rows may omit it until migrated. */
  themePreset?: string
  publishedAt: string
}

export interface NewsroomPost extends NewsroomPostSummary {
  description?: string
  content: string
  oxyUserId?: string
  authorUsername?: string
  tags: string[]
  /** Product `_id` strings when editing; populated `{ _id, productId, name }` on detail. */
  products: Array<string | NewsroomProductRef>
  colorPrimary?: string
  colorSecondary?: string
  dark?: boolean
  status: 'draft' | 'published'
  metaTitle?: string
  metaDescription?: string
  ogImage?: string
  createdAt: string
  updatedAt: string
}

export const newsCategories = [
  'Company',
  'Research',
  'Product',
  'Safety',
  'Engineering',
  'Security',
  'Tips',
  'All',
] as const

export type NewsCategory = (typeof newsCategories)[number]
